/**
 * Taxonomy classification of the pre-existing template families.
 *
 * New template families declare `manifestation` inline. The families written
 * before the taxonomy existed are classified here instead of editing thousands
 * of lines, so the coverage audit can measure them the same way.
 *
 * Values are manifestation ids from `ced-taxonomy.ts`.
 */
export const TEMPLATE_MANIFESTATION: Record<string, string> = {
  /* Unit 1 */
  "u1-removable": "evaluating-limits-algebraically:removable-factor",
  "u1-conjugate": "evaluating-limits-algebraically:conjugate",
  "u1-end-behavior": "limits-at-infinity:rational-degrees",
  "u1-horizontal-asymptote-rational": "limits-at-infinity:rational-degrees",
  "u1-horizontal-asymptote-exponential": "limits-at-infinity:exp-log-growth",
  "u1-horizontal-asymptote-radical": "limits-at-infinity:radical-end",
  "u1-piecewise-continuity": "continuity-and-discontinuity:piecewise-parameter",
  "u1-trig-limit": "squeeze-theorem:bounded-oscillation",
  "u1-ivt": "intermediate-value-theorem:guaranteed-value",
  "u1-table-limit": "limits-from-graphs-and-tables:table-estimate",
  "x1-piecewise-onesided": "limits-from-graphs-and-tables:graph-one-sided",
  "x1-table-estimate": "limits-from-graphs-and-tables:table-estimate",
  "x1-squeeze-bounds": "squeeze-theorem:explicit-bounds",
  "x1-continuity-solve-k": "continuity-and-discontinuity:removable-repair",
  "x1-discontinuity-type": "continuity-and-discontinuity:classify",
  "x1-ivt-guarantee": "intermediate-value-theorem:hypotheses",

  /* Unit 2 */
  "u2-power-rule": "power-rule:evaluate-at-point",
  "u2-definition": "definition-of-the-derivative:evaluate-quotient",
  "u2-product-rule": "product-and-quotient-rules:product-symbolic",
  "u2-quotient-rule": "product-and-quotient-rules:quotient-symbolic",
  "u2-elementary": "derivatives-of-trig-exp-log:standard",
  "u2-differentiability": "differentiability-and-continuity:corner-cusp",
  "x2-definition-recognize": "definition-of-the-derivative:recognize-limit",
  "x2-symmetric-difference": "definition-of-the-derivative:table-estimate",
  "x2-power-negative-radical": "power-rule:negative-fractional",
  "x2-tangent-line": "definition-of-the-derivative:tangent-line",
  "x2-trig-exp-value": "derivatives-of-trig-exp-log:combined",
  "x2-differentiable-piecewise": "differentiability-and-continuity:piecewise-parameters",
  "x2-quotient-value": "product-and-quotient-rules:quotient-symbolic",
  "x2-name-variation": "product-and-quotient-rules:product-symbolic",

  /* Unit 3 */
  "u3-chain-power": "chain-rule:single-composition",
  "u3-chain-trig": "chain-rule:nested-double",
  "x3-chain-log": "chain-rule:single-composition",
  "u3-implicit-circle": "implicit-differentiation:solve-dydx",
  "u3-implicit-product": "implicit-differentiation:with-product",
  "x3-implicit-tangent-slope": "implicit-differentiation:solve-dydx",
  "u3-inverse-derivative": "derivatives-of-inverse-functions:formula-at-point",
  "x3-inverse-function-value": "derivatives-of-inverse-functions:formula-at-point",
  "u3-arctan": "inverse-trig-derivatives:with-chain",
  "x3-inverse-trig-chain": "inverse-trig-derivatives:with-chain",
  "u3-higher-order": "higher-order-derivatives:compute-second",
  "x3-second-derivative-trig": "higher-order-derivatives:compute-second",

  /* Unit 4 */
  "u4-related-rates-circle": "related-rates:geometric-area",
  "u4-related-rates-ladder": "related-rates:pythagorean",
  "x4-related-rates-cone": "related-rates:volume",
  "u4-motion": "rectilinear-motion:velocity-acceleration",
  "x4-motion-direction": "rectilinear-motion:direction-change",
  "u4-linearization": "linearization:approximate-value",
  "x4-linearization-numeric": "linearization:approximate-value",
  "u4-lhopital": "lhopitals-rule:zero-over-zero",
  "x4-lhopital-exp": "lhopitals-rule:zero-over-zero",
  "u4-rate-context": "rates-of-change-in-context:second-derivative",
  "x4-rate-interpretation": "rates-of-change-in-context:meaning",

  /* Unit 5 */
  "u5-local-min": "first-derivative-test:sign-chart",
  "x5-first-derivative-test-sign": "first-derivative-test:sign-chart",
  "u5-mvt": "mean-value-theorem:find-c",
  "x5-mvt-find-c": "mean-value-theorem:find-c",
  "u5-inflection": "second-derivative-test:inflection",
  "x5-concavity-interval": "second-derivative-test:concavity-intervals",
  "u5-candidates": "local-and-global-extrema:candidates-test",
  "x5-absolute-extremum": "local-and-global-extrema:candidates-test",
  "u5-second-derivative-test": "critical-points:locate",
  "x5-critical-count": "critical-points:locate",
  "u5-sign-chart": "curve-sketching:from-sign-chart",
  "x5-curve-sketching-from-derivative": "curve-sketching:from-sign-chart",
  "u5-optimization-box": "optimization:geometry-constraint",
  "x5-optimization-rectangle": "optimization:geometry-constraint",

  /* Unit 6 */
  "u6-definite-poly": "fundamental-theorem-of-calculus:ftc2-evaluate",
  "x6-definite-numeric": "fundamental-theorem-of-calculus:ftc2-evaluate",
  "u6-average-value": "fundamental-theorem-of-calculus:ftc2-evaluate",
  "u6-ftc-chain": "fundamental-theorem-of-calculus:ftc1-chain",
  "u6-usub": "u-substitution:polynomial-inner",
  "x6-usub-trig": "u-substitution:trig-inner",
  "u6-riemann": "riemann-sums:left-right",
  "x6-trapezoid-table": "riemann-sums:trapezoidal-unequal",
  "u6-accumulation": "accumulation-functions:context-total",
  "x6-accumulation-derivative": "fundamental-theorem-of-calculus:ftc1-basic",
  "u6-parts-xexp": "integration-by-parts:polynomial-exp",
  "x6-parts-xln": "integration-by-parts:logarithm",
  "u6-partial-fractions": "partial-fractions:distinct-linear",
  "x6-partial-fractions-log": "partial-fractions:definite",
  "u6-improper": "improper-integrals:infinite-bound",
  "x6-improper-p-test": "improper-integrals:p-integral",

  /* Unit 7 */
  "u7-exponential": "exponential-growth-and-decay:doubling",
  "u7-half-life": "exponential-growth-and-decay:half-life",
  "x7-decay-context": "exponential-growth-and-decay:half-life",
  "u7-separable-xy": "separable-differential-equations:solve-initial",
  "u7-separable-poly": "separable-differential-equations:solve-initial",
  "x7-separable-initial": "separable-differential-equations:implicit-solution",
  "u7-euler": "eulers-method:multi-step",
  "x7-euler-two-steps": "eulers-method:multi-step",
  "u7-logistic": "logistic-growth:fastest-growth",
  "x7-logistic-fastest": "logistic-growth:fastest-growth",
  "u7-slope-field": "slope-fields:slope-at-point",
  "u7-slope-field-identify": "slope-fields:match-equation",
  "x7-slope-field-match-linear": "slope-fields:match-equation",

  /* Unit 8 */
  "u8-average-value": "average-value:compute",
  "x8-average-value-poly": "average-value:compute",
  "u8-area-between": "area-between-curves:intersections",
  "x8-area-between-numeric": "area-between-curves:dx-setup",
  "u8-disk": "volume-disks-and-washers:disk-x-axis",
  "x8-washer-setup": "volume-disks-and-washers:setup-only",
  "u8-cross-sections": "volume-known-cross-sections:square",
  "x8-cross-section-square": "volume-known-cross-sections:square",
  "u8-arc-length-setup": "arc-length:setup",
  "x8-arc-length-numeric": "arc-length:calculator-value",
  "u8-distance": "accumulation-in-context:total-vs-net",
  "u8-net-change": "accumulation-in-context:in-out-rates",
  "x8-accumulation-context": "accumulation-in-context:in-out-rates",

  /* Unit 9 */
  "u9-parametric-slope": "parametric-derivatives:dydx",
  "u9-second-derivative": "parametric-derivatives:second",
  "x9-parametric-vertical-tangent": "parametric-derivatives:horizontal-vertical",
  "u9-parametric-arc-length": "parametric-arc-length:compute",
  "x9-parametric-arc-numeric": "parametric-arc-length:calculator",
  "u9-speed": "vector-valued-functions:speed",
  "u9-vector-motion": "vector-valued-functions:velocity-acceleration",
  "x9-vector-acceleration": "vector-valued-functions:velocity-acceleration",
  "u9-polar-derivative": "polar-derivatives:r-increasing",
  "x9-polar-slope-setup": "polar-derivatives:slope",
  "u9-polar-petal": "polar-area:single-region",
  "u9-polar-setup": "polar-area:setup-only",
  "x9-polar-area-circle": "polar-area:single-region",

  /* Unit 10 */
  "u10-nth-term-test": "nth-term-test:apply",
  "x10-nth-term-conclusion": "nth-term-test:apply",
  "u10-geometric": "geometric-and-p-series:sum",
  "x10-geometric-sum-value": "geometric-and-p-series:sum",
  "u10-p-series": "geometric-and-p-series:p-series",
  "u10-comparison": "comparison-tests:direct-comparison",
  "x10-limit-comparison": "comparison-tests:choose-comparison",
  "u10-ratio-radius": "ratio-test:radius",
  "x10-ratio-test-factorial": "ratio-test:factorial",
  "u10-alternating-error": "alternating-series-test:error-bound",
  "x10-alternating-conditional": "alternating-series-test:absolute-vs-conditional",
  "u10-taylor-coefficient": "taylor-and-maclaurin-series:build-from-derivatives",
  "x10-maclaurin-term": "taylor-and-maclaurin-series:build-from-derivatives",
  "u10-lagrange-error": "lagrange-error-bound:compute-bound",
  "x10-lagrange-bound-numeric": "lagrange-error-bound:compute-bound",
  "u10-power-series-sub": "power-series-operations:substitute",
  "x10-power-series-interval": "power-series-operations:interval-after-operation",
};
