import { createFileRoute } from "@tanstack/react-router";
import { Download } from "lucide-react";
import { PageShell } from "@/components/PageShell";
import { LaTeX } from "@/components/LaTeX";
import { SubjectContentGate } from "@/components/SubjectContentGate";

const PDF_URL = "https://drive.google.com/file/d/1O6iD6MP3R_p4NZzZ4vt-7kVAHrUBYtdJ/view?usp=drive_open";

type Item = { title: string; body: string };
type GuideSection = { id: string; title: string; items: Item[] };

const sections: GuideSection[] = [
  { id: "limits", title: "Limits", items: [
    { title: "Evaluation Techniques", body: `Start with direct substitution. If it produces a determinate value, you are done. If it produces an indeterminate form such as $\\frac00$, rewrite before evaluating again.\n\nCommon moves: factor and cancel, rationalize with a conjugate, combine fractions, use trig identities, or recognize a standard limit.\n\n*note: $\\frac00$ is an indeterminate form — it is not the value of the limit.` },
    { title: "Limit Existence + Continuity", body: `$$\\lim_{x\\to a}f(x)=L\\iff\\lim_{x\\to a^-}f(x)=\\lim_{x\\to a^+}f(x)=L$$\nA function is continuous at $a$ if\n\n1. $f(a)$ exists\n2. $\\lim_{x\\to a}f(x)$ exists\n3. $\\lim_{x\\to a}f(x)=f(a)$\n\n*strategy: for a piecewise function, check the left-hand limit, right-hand limit, and function value separately.` },
    { title: "Types of Discontinuities", body: `Removable: $\\lim_{x\\to a}f(x)$ exists and is finite, but $f(a)$ is undefined or does not equal the limit.\n\nJump: the finite one-sided limits exist but are unequal.\n\nInfinite: at least one one-sided limit is $+\\infty$ or $-\\infty$. If this occurs at $x=a$, then $x=a$ is a vertical asymptote.\n\n*note: factoring may reveal a removable discontinuity, but factoring is not what defines one.` },
    { title: "Things that Break Differentiability", body: `$$\\text{differentiable at }a\\Rightarrow\\text{continuous at }a$$\nTherefore every discontinuity breaks differentiability. A function can also be continuous but not differentiable at a corner, cusp, or vertical tangent.\n\n$$\\text{continuous}\\nRightarrow\\text{differentiable}$$` },
    { title: "Special Trig Limits", body: `Angles must be in radians.\n$$\\lim_{x\\to0}\\frac{\\sin x}{x}=1,\\qquad \\lim_{x\\to0}\\frac{\\tan x}{x}=1$$\n$$\\lim_{x\\to0}\\frac{\\sin(ax)}{bx}=\\frac ab$$\n$$\\lim_{x\\to0}\\frac{1-\\cos x}{x}=0$$\n*strategy: rewrite the expression until a standard limit appears; the first limit can be established with the Squeeze Theorem.` },
    { title: "Intermediate Value Theorem + Mean Value Theorem", body: `IVT. If $f$ is continuous on $[a,b]$ and $N$ lies between $f(a)$ and $f(b)$, then there exists at least one $c\\in(a,b)$ such that $f(c)=N$.\n\n*FRQ: state continuity, show that the target value lies between the endpoint values, then invoke IVT. IVT guarantees existence, not uniqueness.\n\nMVT. If $f$ is continuous on $[a,b]$ and differentiable on $(a,b)$, then there exists at least one $c\\in(a,b)$ such that\n$$f'(c)=\\frac{f(b)-f(a)}{b-a}.$$\n*FRQ: explicitly verify both hypotheses before invoking MVT.` },
    { title: "Horizontal Asymptotes", body: `If $\\lim_{x\\to\\infty}f(x)=L$ or $\\lim_{x\\to-\\infty}f(x)=L$, then $y=L$ is a horizontal asymptote in that direction.\n\nFor expressions involving radicals, remember\n$$\\sqrt{x^2}=|x|.$$\nFor $b>0$,\n$$\\lim_{x\\to\\infty}\\frac{ax}{\\sqrt{bx^2+c}}=\\frac{a}{\\sqrt b},\\qquad \\lim_{x\\to-\\infty}\\frac{ax}{\\sqrt{bx^2+c}}=-\\frac{a}{\\sqrt b}.$$` },
    { title: "L’Hôpital’s Rule", body: `If a quotient has indeterminate form $\\frac00$ or $\\frac{\\pm\\infty}{\\pm\\infty}$ and the hypotheses of L’Hôpital’s Rule are satisfied, then\n$$\\lim_{x\\to a}\\frac{f(x)}{g(x)}=\\lim_{x\\to a}\\frac{f'(x)}{g'(x)}$$\nprovided the derivative-ratio limit exists or diverges appropriately.\n\n*FRQ: first establish the indeterminate form by evaluating the numerator and denominator limits separately. Do not use L’Hôpital’s Rule merely because an expression is a fraction.` },
  ]},
  { id: "derivatives", title: "Derivatives", items: [
    { title: "Limit Definition", body: `$$f'(x)=\\lim_{h\\to0}\\frac{f(x+h)-f(x)}h\\qquad\\text{formal definition}$$\n$$f'(a)=\\lim_{x\\to a}\\frac{f(x)-f(a)}{x-a}\\qquad\\text{alternate definition}$$\n*strategy: if a limit structurally matches one of these forms, identify it as a derivative before doing algebra.` },
    { title: "Trig, Inverse Trig, and Exponential/Logarithmic", body: `| Function | Derivative | Function | Derivative |\n|---|---|---|---|\n| $\\sin x$ | $\\cos x$ | $\\arcsin x$ | $\\frac1{\\sqrt{1-x^2}}$ |\n| $\\cos x$ | $-\\sin x$ | $\\arccos x$ | $-\\frac1{\\sqrt{1-x^2}}$ |\n| $\\tan x$ | $\\sec^2x$ | $\\arctan x$ | $\\frac1{1+x^2}$ |\n| $\\cot x$ | $-\\csc^2x$ | $e^x$ | $e^x$ |\n| $\\sec x$ | $\\sec x\\tan x$ | $a^x$ | $a^x\\ln a$ |\n| $\\csc x$ | $-\\csc x\\cot x$ | $\\ln x$ | $\\frac1x$ |\n| $x^n$ | $nx^{n-1}$ | $\\log_a x$ | $\\frac1{x\\ln a}$ |\n\n*note: when the input is a function rather than just $x$, apply the Chain Rule.` },
    { title: "Product / Quotient Rules", body: `$$\\frac d{dx}[f(x)g(x)]=f(x)g'(x)+f'(x)g(x)$$\n$$\\frac d{dx}\\left[\\frac{f(x)}{g(x)}\\right]=\\frac{f'(x)g(x)-f(x)g'(x)}{[g(x)]^2}$$` },
    { title: "Chain Rule + Inverse Functions", body: `$$\\frac d{dx}[f(g(x))]=f'(g(x))g'(x)$$\nCommon patterns:\n$$\\frac d{dx}e^{g(x)}=e^{g(x)}g'(x),\\qquad \\frac d{dx}\\ln(g(x))=\\frac{g'(x)}{g(x)}$$\n$$\\frac d{dx}\\sin(g(x))=\\cos(g(x))g'(x)$$\nFor an inverse function,\n$$[f^{-1}]'(x)=\\frac1{f'(f^{-1}(x))}.$$\nIf $f(a)=b$, then\n$$[f^{-1}]'(b)=\\frac1{f'(a)}.$$` },
    { title: "Implicit Differentiation", body: `Differentiate both sides with respect to $x$, treating $y$ as a function of $x$. Every differentiated term containing $y$ requires the Chain Rule.\n$$\\frac d{dx}(y^2)=2y\\frac{dy}{dx}$$\n*strategy: collect all terms containing $dy/dx$ on one side, factor out $dy/dx$, then solve. In related rates, differentiate with respect to $t$ instead.` },
  ]},
  { id: "applications-derivatives", title: "Applications of Derivatives", items: [
    { title: "Extrema + Derivative Tests", body: `• Critical numbers: values $c$ in the domain of $f$ where $f'(c)=0$ or $f'(c)$ does not exist.\n\n• Inflection points: points where the graph changes concavity. Values where $f''(c)=0$ or $f''(c)$ does not exist are candidates — a sign change must be verified.\n\nExtreme Value Theorem: If $f$ is continuous on $[a,b]$, then $f$ attains at least one absolute maximum value and at least one absolute minimum value on $[a,b]$.\n\nClosed-Interval Method: evaluate $f$ at every critical number in $(a,b)$ and at both endpoints; compare the values.\n\n1st Derivative Test: $+\\to-\\Rightarrow$ local max; $-\\to+\\Rightarrow$ local min; no sign change $\\Rightarrow$ neither.\n\nConcavity: $f''>0\\Rightarrow$ concave up; $f''<0\\Rightarrow$ concave down.\n\n2nd Derivative Test: if $f'(c)=0$, then $f''(c)<0\\Rightarrow$ local max and $f''(c)>0\\Rightarrow$ local min. If $f''(c)=0$, the test is inconclusive.` },
    { title: "Related Rates + Optimization", body: `Related Rates Plan:\n1. Draw and label a diagram when useful.\n2. Write an equation relating the changing quantities.\n3. Differentiate with respect to $t$ before substituting instantaneous values.\n4. Substitute known values and rates.\n5. Solve, include units, and interpret the sign.\n\nOptimization Plan:\n1. Define variables and the quantity to optimize.\n2. Use the constraint to write the objective as a function of one variable.\n3. Determine the relevant domain.\n4. Find critical numbers and check endpoints when appropriate.\n5. Justify the maximum/minimum and answer the contextual question with units.` },
    { title: "Position, Velocity, Acceleration", body: `$$s(t)=\\text{position},\\quad v(t)=s'(t),\\quad a(t)=v'(t)=s''(t)$$\n$$\\text{speed}=|v(t)|,\\qquad \\text{displacement}=\\int_a^b v(t)dt,\\qquad \\text{total distance}=\\int_a^b|v(t)|dt$$\n$v>0$: moving in the positive direction. $v<0$: moving in the negative direction.\n\nA particle speeds up when $v$ and $a$ have the same sign and slows down when they have opposite signs.\n\n*strategy: for total distance, split the integral wherever $v(t)=0$ and changes sign.` },
    { title: "Linearization", body: `$$L(x)=f(a)+f'(a)(x-a),\\qquad f(x)\\approx L(x)\\text{ near }x=a$$\nIf $f''>0$ near $a$, the tangent-line approximation is locally an underestimate; if $f''<0$, it is locally an overestimate.` },
  ]},
  { id: "integrals", title: "Integrals", items: [
    { title: "Riemann Sums", body: `General form:\n$$\\sum_{i=1}^n f(x_i^*)\\Delta x_i\\approx\\int_a^b f(x)dx$$\nFor equal widths, $\\Delta x=\\frac{b-a}{n}$.\n$$L_n=\\Delta x[f(x_0)+\\cdots+f(x_{n-1})],\\qquad R_n=\\Delta x[f(x_1)+\\cdots+f(x_n)]$$\n$$M_n=\\Delta x[f(\\bar x_1)+\\cdots+f(\\bar x_n)]$$\n$$T_n=\\frac{\\Delta x}{2}[f(x_0)+2f(x_1)+\\cdots+2f(x_{n-1})+f(x_n)]$$\n\n| Function Property | Left | Right |\n|---|---|---|\n| Increasing | Underestimate | Overestimate |\n| Decreasing | Overestimate | Underestimate |\n\n| Function Property | Midpoint | Trapezoidal |\n|---|---|---|\n| Concave Up | Underestimate | Overestimate |\n| Concave Down | Overestimate | Underestimate |\n\n*FRQ: table problems often use unequal subintervals. Think geometrically: each rectangle or trapezoid uses its own width.` },
    { title: "Antiderivatives + Pattern Recognition", body: `| Integral | Result | Integral | Result |\n|---|---|---|---|\n| $\\int\\sin x\\,dx$ | $-\\cos x+C$ | $\\int\\cos x\\,dx$ | $\\sin x+C$ |\n| $\\int\\sec^2x\\,dx$ | $\\tan x+C$ | $\\int\\csc^2x\\,dx$ | $-\\cot x+C$ |\n| $\\int\\sec x\\tan x\\,dx$ | $\\sec x+C$ | $\\int\\csc x\\cot x\\,dx$ | $-\\csc x+C$ |\n| $\\int e^x dx$ | $e^x+C$ | $\\int a^x dx$ | $\\frac{a^x}{\\ln a}+C$ |\n| $\\int\\frac1x dx$ | $\\ln|x|+C$ | $\\int x^n dx$ | $\\frac{x^{n+1}}{n+1}+C,\\ n\\ne-1$ |\n| $\\int\\frac{dx}{1+x^2}$ | $\\arctan x+C$ | $\\int\\frac{dx}{\\sqrt{1-x^2}}$ | $\\arcsin x+C$ |\n\nHigh-value patterns:\n$$\\int\\frac{f'(x)}{f(x)}dx=\\ln|f(x)|+C,\\qquad \\int f'(x)e^{f(x)}dx=e^{f(x)}+C$$` },
    { title: "Substitution (Reverse Chain Rule)", body: `$$\\int f(g(x))g'(x)dx=\\int f(u)du\\quad\\text{where }u=g(x)$$\n*strategy: choose $u$ so that the remaining factor becomes $du$. For a definite integral, either change the bounds to $u$-values and stay in $u$, or return completely to $x$ before using the original bounds.` },
    { title: "Integration by Parts — BC", body: `$$\\int u\\,dv=uv-\\int v\\,du$$\n*strategy: choose $u$ so that differentiating it simplifies the problem. LIATE can be a useful heuristic, not a theorem.` },
    { title: "Fundamental Theorem of Calculus", body: `$$\\frac d{dx}\\int_a^x f(t)dt=f(x)$$\n$$\\frac d{dx}\\int_a^{g(x)}f(t)dt=f(g(x))g'(x)$$\n$$\\frac d{dx}\\int_{g(x)}^{h(x)}f(t)dt=f(h(x))h'(x)-f(g(x))g'(x)$$\n$$\\int_a^b f(x)dx=F(b)-F(a)\\quad\\text{where }F'=f$$\n*strategy: accumulation functions inherit increasing/decreasing behavior from the sign of the integrand and concavity from how the integrand is changing.` },
    { title: "Partial Fractions — BC", body: `For distinct linear factors,\n$$\\frac{P(x)}{(x-a)(x-b)}=\\frac A{x-a}+\\frac B{x-b}.$$\nIf a linear factor repeats, include a term for every power of that factor.\n\n*strategy: first use long division if the rational function is improper. Cover-up can be efficient for distinct linear factors; coefficient comparison is more general.` },
    { title: "Improper Integrals — BC", body: `$$\\int_a^\\infty f(x)dx=\\lim_{b\\to\\infty}\\int_a^b f(x)dx$$\n$$\\int_{-\\infty}^b f(x)dx=\\lim_{a\\to-\\infty}\\int_a^b f(x)dx$$\nIf there is an infinite discontinuity at $c\\in(a,b)$, split the integral and use one-sided limits.\n\nAn improper integral converges only when every required defining limit exists and is finite.\n\n*FRQ: never substitute $\\infty$ as though it were a number; write the defining limit.` },
  ]},
  { id: "applications-integrals", title: "Applications of Integrals", items: [
    { title: "Average Value + Net Change", body: `$$f_{\\mathrm{avg}}=\\frac1{b-a}\\int_a^b f(x)dx$$\n$$F(b)-F(a)=\\int_a^b F'(x)dx$$\n*note: an average value has the same units as the original function. A definite integral of a rate has units of the accumulated quantity.` },
    { title: "Area / Volume", body: `Area with vertical slices:\n$$A=\\int_a^b(\\text{top}-\\text{bottom})dx$$\nArea with horizontal slices:\n$$A=\\int_c^d(\\text{right}-\\text{left})dy$$\nDisk / washer method:\n$$V=\\pi\\int_a^b(R(x)^2-r(x)^2)dx$$\nwhere $R$ and $r$ are distances from the axis of revolution.\n\nKnown cross sections:\n$$V=\\int_a^b A(x)dx$$\n*strategy: first identify the base length of each cross section, then build its area formula. For a semicircle with diameter $s$, $A=\\frac{\\pi s^2}{8}$; for a square, $A=s^2$.\n\n*note: cylindrical shells can be a useful calculus technique, but they are not a required AP Calculus AB/BC method, so they are omitted from the core formula set.` },
    { title: "Arc Length — BC", body: `For a smooth graph $y=f(x)$,\n$$L=\\int_a^b\\sqrt{1+[f'(x)]^2}dx.$$\nFor $x=g(y)$,\n$$L=\\int_c^d\\sqrt{1+[g'(y)]^2}dy.$$\n*strategy: on AP problems, setting up the correct integral may be more important than finding a closed-form antiderivative.` },
  ]},
  { id: "differential-equations", title: "Differential Equations", items: [
    { title: "Slope Fields + Euler’s Method — Euler BC", body: `For $\\frac{dy}{dx}=F(x,y)$, the slope field assigns slope $F(x,y)$ at each point $(x,y)$.\n\nEuler’s Method:\n$$y_{n+1}=y_n+F(x_n,y_n)\\Delta x$$\n*strategy: use the current point to find the current slope, then take one tangent-line step. Repeat from the newly approximated point.` },
    { title: "Separable Differential Equations", body: `$$\\frac{dy}{dx}=g(x)h(y)\\Rightarrow\\frac1{h(y)}dy=g(x)dx$$\nThen integrate both sides and use an initial condition when one is given.\n\n*FRQ: show the separation and integration steps; do not forget the constant of integration. When dividing by an expression involving $y$, be alert to equilibrium solutions that division could exclude.` },
    { title: "Exponential Growth / Decay", body: `$$\\frac{dy}{dt}=ky\\Rightarrow y(t)=Ce^{kt}$$\nWith $y(0)=y_0$,\n$$y(t)=y_0e^{kt}.$$\n$k>0$ gives growth; $k<0$ gives decay.` },
    { title: "Logistic Growth Model — BC", body: `$$\\frac{dP}{dt}=kP\\left(1-\\frac PM\\right)$$\n$M$ is the carrying capacity, and the growth rate is greatest when $P=M/2$. For the standard positive-growth model,\n$$P(t)=\\frac{M}{1+Ae^{-kt}}.$$\n*strategy: identify equilibrium solutions from $dP/dt=0$ and use the sign of $dP/dt$ to reason about growth without solving the equation.` },
  ]},
  { id: "polar-parametric", title: "Polar/Parametric — BC", items: [
    { title: "Parametric Equations", body: `$$\\frac{dy}{dx}=\\frac{dy/dt}{dx/dt},\\qquad \\frac{d^2y}{dx^2}=\\frac{\\frac d{dt}(dy/dx)}{dx/dt}$$\n$$L=\\int_a^b\\sqrt{\\left(\\frac{dx}{dt}\\right)^2+\\left(\\frac{dy}{dt}\\right)^2}dt$$\n*strategy: horizontal tangents usually require $dy/dt=0$ with $dx/dt\\ne0$; vertical tangents usually require $dx/dt=0$ with $dy/dt\\ne0$.` },
    { title: "Polar Equations", body: `$$x=r\\cos\\theta,\\quad y=r\\sin\\theta,\\quad x^2+y^2=r^2$$\n$$A=\\frac12\\int_\\alpha^\\beta[r(\\theta)]^2d\\theta$$\nBetween two polar curves:\n$$A=\\frac12\\int_\\alpha^\\beta([R(\\theta)]^2-[r(\\theta)]^2)d\\theta$$\n$$L=\\int_\\alpha^\\beta\\sqrt{r^2+\\left(\\frac{dr}{d\\theta}\\right)^2}d\\theta$$\n*strategy: determine bounds from intersections, symmetry, or where the curve reaches the pole. For inner loops, trace the curve rather than guessing the interval.` },
    { title: "Vector-Valued Motion", body: `position: $\\langle x(t),y(t)\\rangle$\n\nvelocity: $\\langle x'(t),y'(t)\\rangle$\n\nacceleration: $\\langle x''(t),y''(t)\\rangle$\n\n$$\\text{speed}=\\sqrt{[x'(t)]^2+[y'(t)]^2}$$\n$$\\text{distance traveled}=\\int_a^b\\sqrt{[x'(t)]^2+[y'(t)]^2}dt$$` },
  ]},
  { id: "series", title: "Series — BC", items: [
    { title: "Sequences, Series + Partial Sums", body: `A series converges to $S$ when its sequence of partial sums converges to $S$.\n$$S_N=\\sum_{n=1}^N a_n,\\qquad \\sum_{n=1}^\\infty a_n=\\lim_{N\\to\\infty}S_N$$\n*note: convergence of the terms $a_n$ to zero is necessary for a series to converge, but it is not sufficient.` },
    { title: "Geometric Series", body: `$$\\sum_{n=0}^\\infty ar^n=\\frac{a}{1-r}\\quad\\text{if }|r|<1$$\nThe series diverges if $|r|\\ge1$.\n\n*strategy: if the index starts somewhere else, identify the actual first term rather than assuming it is $a$.` },
    { title: "Power Series, Taylor Series, and Maclaurin Series", body: `Power series centered at $a$:\n$$\\sum_{n=0}^\\infty c_n(x-a)^n$$\nTaylor series for $f$ centered at $a$:\n$$\\sum_{n=0}^\\infty\\frac{f^{(n)}(a)}{n!}(x-a)^n$$\nMaclaurin series is the Taylor series centered at $0$:\n$$\\sum_{n=0}^\\infty\\frac{f^{(n)}(0)}{n!}x^n$$` },
    { title: "Common Maclaurin Series", body: `$$e^x=\\sum_{n=0}^\\infty\\frac{x^n}{n!}$$\n$$\\sin x=\\sum_{n=0}^\\infty\\frac{(-1)^nx^{2n+1}}{(2n+1)!},\\qquad \\cos x=\\sum_{n=0}^\\infty\\frac{(-1)^nx^{2n}}{(2n)!}$$\n$$\\frac1{1-x}=\\sum_{n=0}^\\infty x^n,\\qquad |x|<1$$\n$$\\ln(1+x)=\\sum_{n=1}^\\infty\\frac{(-1)^{n-1}x^n}{n},\\qquad -1<x\\le1$$\n$$\\arctan x=\\sum_{n=0}^\\infty\\frac{(-1)^nx^{2n+1}}{2n+1},\\qquad -1\\le x\\le1$$` },
    { title: "Lagrange Error Bound", body: `For the degree-$n$ Taylor polynomial $P_n(x)$ centered at $a$,\n$$|R_n(x)|=|f(x)-P_n(x)|\\le\\frac{M|x-a|^{n+1}}{(n+1)!}$$\nwhere $M$ is an upper bound for $|f^{(n+1)}(z)|$ between $a$ and $x$.\n\n*strategy: the hard part is usually choosing a valid $M$, not using the formula.` },
    { title: "Alternating Series Error Bound", body: `If an alternating series satisfies the Alternating Series Test, then\n$$|S-S_N|\\le a_{N+1}.$$\n*strategy: the first omitted term controls the maximum error. This can also be used to determine how many terms are needed for a requested accuracy.` },
    { title: "Manipulating Known Series", body: `Build new series from known ones by substitution, multiplication by algebraic factors, and term-by-term differentiation or integration within the interval of convergence.\n\n*strategy: substitution can change the center and radius in the $x$-variable — solve the transformed convergence condition rather than assuming the radius stays numerically unchanged.` },
    { title: "Convergence Tests", body: `n-th Term Test: if $\\lim_{n\\to\\infty}a_n\\ne0$ or does not exist, $\\sum a_n$ diverges. If the limit is $0$, the test is inconclusive.\n\np-Series: $\\sum 1/n^p$ converges for $p>1$ and diverges for $p\\le1$.\n\nAlternating Series Test: convergence follows when the magnitudes eventually decrease and approach $0$.\n\nIntegral Test: for positive, continuous, decreasing $f$ with $f(n)=a_n$, $\\sum a_n$ and $\\int f(x)dx$ have the same convergence behavior.\n\nDirect Comparison: compare positive terms with a known benchmark using inequalities in the direction that proves what you need.\n\nLimit Comparison: if $a_n,b_n>0$ and $\\lim a_n/b_n=L$ with $0<L<\\infty$, the two series have the same convergence behavior.\n\nRatio Test: if $L=\\lim|a_{n+1}/a_n|$, then $L<1$ gives absolute convergence, $L>1$ gives divergence, and $L=1$ is inconclusive.` },
    { title: "Absolute vs. Conditional Convergence", body: `$\\sum a_n$ converges absolutely if $\\sum|a_n|$ converges. Absolute convergence implies convergence.\n\n$\\sum a_n$ converges conditionally if $\\sum a_n$ converges but $\\sum|a_n|$ diverges.\n\n*strategy: for an alternating series, test absolute convergence first when the problem asks you to classify the convergence.` },
    { title: "Radius and Interval of Convergence", body: `For a power series centered at $a$, the interval has the form\n$$|x-a|<R$$\nbefore endpoint behavior is checked.\n\nStrategy:\n1. Use the Ratio Test or another appropriate method to solve for the open interval of convergence.\n2. Read the radius $R$ from the distance to the center $a$.\n3. Test each endpoint separately in the original series.\n\n*trap: the Ratio Test generally does not decide endpoint convergence.` },
  ]},
];

export const Route = createFileRoute("/latex-master-sheet")({
  head: () => ({ meta: [
    { title: "Formula and Strategy Guide — AP STEM OS" },
    { name: "description", content: "A navigable web-native AP Calculus BC master guide with the complete printable guide preserved alongside it." },
    { property: "og:title", content: "Formula and Strategy Guide — AP STEM OS" },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: () => <SubjectContentGate><FormulaGuide /></SubjectContentGate>,
});

function FormulaGuide() {
  return (
    <PageShell eyebrow="cram" title="Formula and Strategy Guide" description="The complete AP Calculus BC Master Guide, rendered natively for the web and organized for fast navigation. The printable LaTeX version is still available.">
      <div className="grid min-w-0 grid-cols-[minmax(0,1fr)] gap-8 lg:grid-cols-[220px_minmax(0,1fr)]">
        <aside className="min-w-0 lg:sticky lg:top-24 lg:self-start">
          <div className="rounded-2xl border border-border bg-card p-4 shadow-card">
            <div className="micro-label mb-3">contents</div>
            <nav aria-label="Guide sections" className="space-y-1">
              {sections.map((section, i) => <a key={section.id} href={`#${section.id}`} className="group flex items-center gap-2 rounded-lg px-2.5 py-2 text-[13px] text-muted-foreground transition-colors hover:bg-elevated hover:text-foreground"><span className="num text-[10px] text-subtle">{String(i + 1).padStart(2, "0")}</span><span>{section.title}</span></a>)}
            </nav>
            <a href={PDF_URL} target="_blank" rel="noopener noreferrer" className="mt-4 flex items-center gap-2 border-t border-border px-2.5 pt-4 text-[12px] font-medium text-primary"><Download className="h-3.5 w-3.5" />Printable PDF</a>
          </div>
        </aside>

        <main data-formula-guide-main className="min-w-0 max-w-full space-y-10 overflow-hidden">
          {sections.map((section, sectionIndex) => (
            <section key={section.id} id={section.id} className="scroll-mt-24">
              <div className="mb-5 flex items-baseline gap-3 border-b border-border pb-3"><span className="num text-[11px] text-primary">{String(sectionIndex + 1).padStart(2, "0")}</span><h2 className="font-display text-2xl font-semibold tracking-tight">{section.title}</h2></div>
              <div className="space-y-4">
                {section.items.map((item) => <article key={item.title} className="min-w-0 max-w-full overflow-hidden rounded-2xl border border-border bg-card p-5 shadow-card sm:p-7"><h3 className="font-display text-[17px] font-semibold">{item.title}</h3><div className="formula-guide-card-body mt-4 min-w-0 max-w-full whitespace-pre-line text-[14px] leading-7 text-secondary-foreground"><LaTeX>{item.body}</LaTeX></div></article>)}
              </div>
            </section>
          ))}
        </main>
      </div>
    </PageShell>
  );
}
