/**
 * Unit 3 (composite/implicit/inverse differentiation) and Unit 4 (contextual
 * applications of differentiation) template families.
 *
 * Every family below is an original construction: numbers, functions, and
 * contexts are generated by the RNG, and no College Board wording is reused.
 */

import {
  dec,
  frac,
  pick,
  ri,
  term,
  type QuestionTemplate,
  type RNG,
} from "../question-templates";
import { fitWindow, sampleCurve } from "../figures";

const U3 = "unit-3-differentiation-composite-implicit-inverse";
const U4 = "unit-4-contextual-applications-of-differentiation";

/** Drop a coefficient of 1 (and render -1 as a bare minus) before a body. */
const coefTerm = (c: number, body: string): string => {
  if (c === 1) return body;
  if (c === -1) return `-${body}`;
  return `${c}${body}`;
};

const signedLinear = (m: number, b: number): string => {
  const head = coefTerm(m, "x");
  return `${head}${term(b, "")}`;
};

export const UNIT_03_04_TEMPLATES: QuestionTemplate[] = [
  /* ================================================================== */
  /* Unit 3: chain-rule:with-product                                     */
  /* ================================================================== */
  {
    id: "n3-chain-product-a",
    unit: U3,
    topic: "chain-rule",
    difficulty: "medium",
    manifestation: "chain-rule:with-product",
    mistakes: ["missing-chain-factor"],
    build: (r: RNG) => {
      const a = ri(r, 2, 5);
      const k = ri(r, 2, 4);
      const n = ri(r, 2, 3);
      // f(x) = x^a * (kx+1)^n
      // f'(x) = a x^(a-1) (kx+1)^n + x^a * n k (kx+1)^(n-1)
      const correct = `${a}x^{${a - 1}}(${k}x+1)^{${n}} + ${n * k}x^{${a}}(${k}x+1)^{${n - 1}}`;
      const missingChain = `${a}x^{${a - 1}}(${k}x+1)^{${n}} + ${n}x^{${a}}(${k}x+1)^{${n - 1}}`;
      const productOmitted = `${a}x^{${a - 1}}(${k}x+1)^{${n}}`;
      const sumRuleInstead = `${a}x^{${a - 1}} + ${n * k}(${k}x+1)^{${n - 1}}`;
      return {
        prompt: `If $f(x)=x^{${a}}(${k}x+1)^{${n}}$, what is $f'(x)$?`,
        correct,
        distractors: [missingChain, productOmitted, sumRuleInstead],
        explanation: `Using the product rule with the chain rule on the second factor: $\\frac{d}{dx}[x^{${a}}] = ${a}x^{${a - 1}}$ and $\\frac{d}{dx}[(${k}x+1)^{${n}}] = ${n * k}(${k}x+1)^{${n - 1}}$ (the inner derivative ${k} must be multiplied in). Combining with the product rule gives ${correct}.`,
      };
    },
  },
  {
    id: "n3-chain-product-b",
    unit: U3,
    topic: "chain-rule",
    difficulty: "medium",
    manifestation: "chain-rule:with-product",
    mistakes: ["wrong-derivative-rule"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      const c = ri(r, 1, 5);
      const p = ri(r, 2, 3);
      // g(x) = sin(kx) * (x+c)^p
      // g' = k cos(kx) (x+c)^p + p sin(kx) (x+c)^{p-1}
      const correct = `${k}\\cos(${k}x)(x+${c})^{${p}} + ${p}\\sin(${k}x)(x+${c})^{${p - 1}}`;
      const forgotChain = `\\cos(${k}x)(x+${c})^{${p}} + ${p}\\sin(${k}x)(x+${c})^{${p - 1}}`;
      const swapped = `${k}\\cos(${k}x)(x+${c})^{${p - 1}} + ${p}\\sin(${k}x)(x+${c})^{${p}}`;
      const productSkipped = `${k}\\cos(${k}x)(x+${c})^{${p}}`;
      return {
        prompt: `A physics student models displacement with $g(x)=\\sin(${k}x)(x+${c})^{${p}}$. Determine $g'(x)$.`,
        correct,
        distractors: [forgotChain, swapped, productSkipped],
        explanation: `Apply the product rule: the derivative of $\\sin(${k}x)$ is $${k}\\cos(${k}x)$ by the chain rule, and the derivative of $(x+${c})^{${p}}$ is $${p}(x+${c})^{${p - 1}}$. Combining gives ${correct}.`,
      };
    },
  },
  {
    id: "n3-chain-product-c",
    unit: U3,
    topic: "chain-rule",
    difficulty: "hard",
    manifestation: "chain-rule:with-product",
    mistakes: ["chain-rule-inner-omitted"],
    build: (r: RNG) => {
      const k = ri(r, 2, 3);
      const m = ri(r, 2, 4);
      // h(x) = e^{kx} * x^m
      // h' = k e^{kx} x^m + m e^{kx} x^{m-1}
      const correct = `${k}e^{${k}x}x^{${m}} + ${m}e^{${k}x}x^{${m - 1}}`;
      const noChain = `e^{${k}x}x^{${m}} + ${m}e^{${k}x}x^{${m - 1}}`;
      const wrongPower = `${k}e^{${k}x}x^{${m}} + ${m}e^{${k}x}x^{${m}}`;
      const onlyFirst = `${k}e^{${k}x}x^{${m}}`;
      return {
        prompt: `Suppose the volume of a tank is modeled by $V(x)=e^{${k}x}x^{${m}}$, where $x$ is measured in hours. Find $V'(x)$.`,
        correct,
        distractors: [noChain, wrongPower, onlyFirst],
        explanation: `By the product rule, $V'(x)=\\frac{d}{dx}[e^{${k}x}]\\cdot x^{${m}} + e^{${k}x}\\cdot\\frac{d}{dx}[x^{${m}}]$. The chain rule gives $\\frac{d}{dx}[e^{${k}x}]=${k}e^{${k}x}$, and the power rule gives $${m}x^{${m - 1}}$, so $V'(x)=${correct}$.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: implicit-differentiation:horizontal-vertical                */
  /* ================================================================== */
  {
    id: "n3-implicit-hv-a",
    unit: U3,
    topic: "implicit-differentiation",
    difficulty: "medium",
    manifestation: "implicit-differentiation:horizontal-vertical",
    mistakes: ["confuses-horizontal-vertical"],
    build: (r: RNG) => {
      const a = ri(r, 2, 5);
      const b = ri(r, 2, 5);
      const R = a * a + b * b;
      return {
        prompt: `A curve is given by $x^{2}+y^{2}=${R}$. At which point on the curve does the tangent line have a horizontal tangent, with $y>0$?`,
        correct: `(0, \\sqrt{${R}})`,
        distractors: [
          `(\\sqrt{${R}}, 0)`,
          `(${a}, ${b})`,
          `(-\\sqrt{${R}}, 0)`,
        ],
        explanation: `Differentiating implicitly, $2x+2y y'=0$, so $y'=-\\dfrac{x}{y}$. A horizontal tangent needs $y'=0$, which requires $x=0$ (with $y\\ne 0$), giving the point $(0,\\sqrt{${R}})$. Points with $y=0$ instead give vertical tangents.`,
      };
    },
  },
  {
    id: "n3-implicit-hv-b",
    unit: U3,
    topic: "implicit-differentiation",
    difficulty: "medium",
    manifestation: "implicit-differentiation:horizontal-vertical",
    mistakes: ["sets-numerator-zero-for-vertical"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      // curve: y^2 = x^3 - k x  -> classify tangent type at a chosen point where derivative undefined
      // 2y y' = 3x^2 - k -> y' = (3x^2-k)/(2y). Vertical tangent when y=0 (denominator 0), provided numerator nonzero.
      return {
        prompt: `For the curve $y^{2}=x^{3}-${k}x$, implicit differentiation gives $y'=\\dfrac{3x^{2}-${k}}{2y}$. At a point on the curve where $y=0$ and $3x^{2}-${k}\\ne 0$, what type of tangent line does the curve have?`,
        correct: `\\text{A vertical tangent line}`,
        distractors: [
          `\\text{A horizontal tangent line}`,
          `\\text{No tangent line exists there}`,
          `\\text{A tangent line with slope } 0`,
        ],
        explanation: `When $y=0$ the denominator of $y'$ is zero while the numerator is nonzero, so $y'$ is undefined (behaves like division by zero) — this signals a vertical tangent line, not a horizontal one.`,
      };
    },
  },
  {
    id: "n3-implicit-hv-c",
    unit: U3,
    topic: "implicit-differentiation",
    difficulty: "hard",
    manifestation: "implicit-differentiation:horizontal-vertical",
    mistakes: ["wrong-derivative-solve"],
    build: (r: RNG) => {
      const c = ri(r, 2, 6);
      // curve: x^2 - x y + y^2 = c  ; find horizontal tangent points
      // differentiate: 2x - y - x y' + 2y y' = 0 -> y'(2y - x) = y - 2x -> y' = (y-2x)/(2y-x)
      // horizontal: y = 2x. Sub into curve: x^2 - x(2x) + (2x)^2 = c -> x^2 -2x^2+4x^2 = 3x^2 = c
      return {
        prompt: `A curve satisfies $x^{2}-xy+y^{2}=${3 * c * c}$. Implicit differentiation shows $y'=\\dfrac{y-2x}{2y-x}$. Which point on the curve has a horizontal tangent line, using positive coordinates?`,
        correct: `(${c}, ${2 * c})`,
        distractors: [
          `(${2 * c}, ${c})`,
          `(${c}, ${c})`,
          `(-${c}, -${2 * c})`,
        ],
        explanation: `A horizontal tangent requires $y'=0$, so the numerator $y-2x=0$, meaning $y=2x$. Substituting into the curve equation $x^2-xy+y^2=${3 * c * c}$ gives $3x^2=${3 * c * c}$, so $x=${c}$ and $y=${2 * c}$, the point $(${c},${2 * c})$.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: implicit-differentiation:second-derivative                  */
  /* ================================================================== */
  {
    id: "n3-implicit-2nd-a",
    unit: U3,
    topic: "implicit-differentiation",
    difficulty: "hard",
    manifestation: "implicit-differentiation:second-derivative",
    mistakes: ["forgets-to-resubstitute-y-prime"],
    build: (r: RNG) => {
      const k = ri(r, 2, 6);
      // x^2 + y^2 = k^2. y' = -x/y. y'' = -(y - x y')/y^2 = -(y - x(-x/y))/y^2 = -(y + x^2/y)/y^2 = -(y^2+x^2)/y^3 = -k^2/y^3
      return {
        prompt: `If $x^{2}+y^{2}=${k * k}$, what is $\\dfrac{d^{2}y}{dx^{2}}$ in terms of $y$?`,
        correct: `-\\dfrac{${k * k}}{y^{3}}`,
        distractors: [
          `-\\dfrac{x}{y^{3}}`,
          `\\dfrac{${k * k}}{y^{3}}`,
          `-\\dfrac{${k * k}}{y^{2}}`,
        ],
        explanation: `Differentiating $2x+2yy'=0$ gives $y'=-\\frac{x}{y}$. Differentiating again, $2+2(y')^{2}+2yy''=0$, so $y''=-\\frac{1+(y')^{2}}{y}$. Substituting $y'=-x/y$ and using $x^2+y^2=${k * k}$ simplifies to $y''=-\\dfrac{${k * k}}{y^{3}}$.`,
      };
    },
  },
  {
    id: "n3-implicit-2nd-b",
    unit: U3,
    topic: "implicit-differentiation",
    difficulty: "hard",
    manifestation: "implicit-differentiation:second-derivative",
    mistakes: ["sign-slip-second-diff"],
    build: (r: RNG) => {
      const a = ri(r, 2, 4);
      // xy = a. y = a/x. y' = -a/x^2. y'' = 2a/x^3
      return {
        prompt: `Given $xy=${a}$, a student finds $y'=-\\dfrac{${a}}{x^{2}}$ by implicit differentiation. What is $y''$?`,
        correct: `\\dfrac{${2 * a}}{x^{3}}`,
        distractors: [
          `-\\dfrac{${2 * a}}{x^{3}}`,
          `\\dfrac{${a}}{x^{3}}`,
          `-\\dfrac{${a}}{x^{2}}`,
        ],
        explanation: `Differentiate $y'=-${a}x^{-2}$ using the power rule: $y''=(-2)(-${a})x^{-3}=\\dfrac{${2 * a}}{x^{3}}$. A sign slip on the exponent's negative coefficient produces the negative distractor.`,
      };
    },
  },
  {
    id: "n3-implicit-2nd-c",
    unit: U3,
    topic: "implicit-differentiation",
    difficulty: "hard",
    manifestation: "implicit-differentiation:second-derivative",
    mistakes: ["omits-product-rule-in-second-pass"],
    build: (r: RNG) => {
      const k = ri(r, 2, 5);
      // y^2 = kx. 2y y' = k -> y' = k/(2y). y'' = -k/(2y^2) y' = -k/(2y^2) * k/(2y) = -k^2/(4y^3)
      return {
        prompt: `A curve satisfies $y^{2}=${k}x$. Find $\\dfrac{d^{2}y}{dx^{2}}$ in terms of $y$.`,
        correct: `-\\dfrac{${k * k}}{4y^{3}}`,
        distractors: [
          `\\dfrac{${k * k}}{4y^{3}}`,
          `-\\dfrac{${k}}{4y^{3}}`,
          `-\\dfrac{${k * k}}{2y^{3}}`,
        ],
        explanation: `From $2yy'=${k}$, $y'=\\dfrac{${k}}{2y}$. Differentiating with the quotient rule, $y''=-\\dfrac{${k}}{2y^{2}}y'=-\\dfrac{${k}}{2y^{2}}\\cdot\\dfrac{${k}}{2y}=-\\dfrac{${k * k}}{4y^{3}}$. Skipping the chain factor $y'$ in the second differentiation yields the wrong-sign or wrong-coefficient distractors.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: derivatives-of-inverse-functions:reciprocal-concept          */
  /* ================================================================== */
  {
    id: "n3-inv-reciprocal-a",
    unit: U3,
    topic: "derivatives-of-inverse-functions",
    difficulty: "medium",
    manifestation: "derivatives-of-inverse-functions:reciprocal-concept",
    mistakes: ["uses-f-prime-of-x-instead-of-inverse"],
    build: (r: RNG) => {
      const name = pick(r, ["f", "g", "h"]);
      return {
        prompt: `Suppose ${name} is differentiable and invertible everywhere, with ${name}'(x)\\ne 0$ for all $x$. Which expression correctly gives the derivative of ${name}^{-1}$ at a point $x$?`,
        correct: `\\text{the reciprocal of } ${name}'(${name}^{-1}(x))`,
        distractors: [
          `\\text{the reciprocal of } ${name}'(x)`,
          `${name}'(${name}^{-1}(x))`,
          `\\text{the reciprocal of } ${name}(${name}^{-1}(x))`,
        ],
        explanation: `Because $${name}(${name}^{-1}(x))=x$, differentiating both sides with the chain rule gives $${name}'(${name}^{-1}(x))\\cdot(${name}^{-1})'(x)=1$, so $(${name}^{-1})'(x)$ is the reciprocal of $${name}'(${name}^{-1}(x))$ — evaluated at $${name}^{-1}(x)$, not at $x$ itself.`,
      };
    },
  },
  {
    id: "n3-inv-reciprocal-b",
    unit: U3,
    topic: "derivatives-of-inverse-functions",
    difficulty: "medium",
    manifestation: "derivatives-of-inverse-functions:reciprocal-concept",
    mistakes: ["forgets-inverse-in-composition"],
    build: (r: RNG) => {
      return {
        prompt: `A student claims that if $f$ is invertible and differentiable, then $(f^{-1})'(x) = \\dfrac{1}{f'(x)}$ for every $x$ in the domain of $f^{-1}$. Is this claim correct?`,
        correct: `\\text{No, the denominator must be } f'(f^{-1}(x)), \\text{ not } f'(x)`,
        distractors: [
          `\\text{Yes, this is always correct}`,
          `\\text{No, the correct formula is } (f^{-1})'(x) = f'(x)`,
          `\\text{No, the correct formula has no reciprocal at all}`,
        ],
        explanation: `The identity $f(f^{-1}(x))=x$ differentiates to $f'(f^{-1}(x))(f^{-1})'(x)=1$, so $(f^{-1})'(x)=\\dfrac{1}{f'(f^{-1}(x))}$. Using $f'(x)$ in the denominator instead of $f'(f^{-1}(x))$ is a common error since the argument must first pass through the inverse.`,
      };
    },
  },
  {
    id: "n3-inv-reciprocal-c",
    unit: U3,
    topic: "derivatives-of-inverse-functions",
    difficulty: "easy",
    manifestation: "derivatives-of-inverse-functions:reciprocal-concept",
    mistakes: ["inverts-wrong-quantity"],
    build: (r: RNG) => {
      const a = ri(r, 2, 8);
      return {
        prompt: `If $f$ is invertible, differentiable, and $f'(x) \\ne 0$ everywhere, which statement correctly describes the relationship between the slope of $f$ at $x=${a}$ and the slope of $f^{-1}$ at the corresponding point?`,
        correct: `\\text{They are reciprocals of each other}`,
        distractors: [
          `\\text{They are equal}`,
          `\\text{They are opposites (negatives) of each other}`,
          `\\text{They are always both equal to } 1`,
        ],
        explanation: `Since $f(f^{-1}(x))=x$, the chain rule gives $f'(f^{-1}(x))\\cdot(f^{-1})'(x)=1$. This means the slope of $f^{-1}$ at the point corresponding to $x=${a}$ is the reciprocal of the slope of $f$ at $x=${a}$, not equal to it or its negative.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: derivatives-of-inverse-functions:graph-reflection            */
  /* ================================================================== */
  {
    id: "n3-inv-graph-a",
    unit: U3,
    topic: "derivatives-of-inverse-functions",
    difficulty: "medium",
    manifestation: "derivatives-of-inverse-functions:graph-reflection",
    mistakes: ["reads-slope-at-wrong-point"],
    build: (r: RNG) => {
      const a = ri(r, 1, 3);
      const b = a * a + 1; // point (a,b) on f, so (b,a) on f^{-1}
      const f = (x: number) => x * x + 1;
      const curvePts = sampleCurve(f, 0, 3);
      const reflectedPts = curvePts.map(([x, y]) => [y, x] as [number, number]);
      const window = fitWindow([...curvePts, ...reflectedPts, [-1, -1]], 1);
      const slopeAtA = 2 * a;
      return {
        prompt: `The graph shows $y=f(x)$ (solid) and its reflection $y=f^{-1}(x)$ (dashed) across the line $y=x$. Given $f(${a})=${b}$ and $f'(${a})=${slopeAtA}$, find $(f^{-1})'(${b})$.`,
        correct: frac(1, slopeAtA),
        distractors: [
          `${slopeAtA}`,
          `${-slopeAtA}`,
          frac(-1, slopeAtA),
        ],
        explanation: `The point $(${a},${b})$ on $f$ reflects to $(${b},${a})$ on $f^{-1}$. Since $(f^{-1})'(${b})=\\dfrac{1}{f'(${a})}=\\dfrac{1}{${slopeAtA}}$, the reflected curve's slope is the reciprocal of the original slope, not the slope itself or its negative.`,
        figure: {
          kind: "graph",
          curves: [
            { label: "f", points: curvePts, smooth: true, tone: 0 },
            { label: "f^{-1}", points: reflectedPts, smooth: true, dashed: true, tone: 1 },
            { points: [[window.xMin, window.xMin], [window.xMax, window.xMax]], smooth: false, dashed: true, tone: 1 },
          ],
          window,
          markers: [
            { x: a, y: b, kind: "closed", label: `(${a},${b})` },
            { x: b, y: a, kind: "closed", label: `(${b},${a})` },
          ],
          caption: "y = f(x) and its reflection y = f^{-1}(x) across y = x",
        },
      };
    },
  },
  {
    id: "n3-inv-graph-b",
    unit: U3,
    topic: "derivatives-of-inverse-functions",
    difficulty: "medium",
    manifestation: "derivatives-of-inverse-functions:graph-reflection",
    mistakes: ["confuses-reflection-with-negation"],
    build: (r: RNG) => {
      const f = (x: number) => Math.pow(x, 3) / 3 + 1;
      const curvePts = sampleCurve(f, -2, 2);
      const reflectedPts = curvePts.map(([x, y]) => [y, x] as [number, number]);
      const window = fitWindow([...curvePts, ...reflectedPts], 1);
      return {
        prompt: `The solid curve below is $y=f(x)$, and the dashed curve is obtained by reflecting it across $y=x$. What function does the dashed curve represent?`,
        correct: `\\text{The inverse function } f^{-1}`,
        distractors: [
          `\\text{The negative function } -f`,
          `\\text{The derivative function } f'`,
          `\\text{A horizontal translation of } f`,
        ],
        explanation: `Reflecting the graph of a one-to-one function $f$ across the line $y=x$ swaps the roles of $x$ and $y$, which produces the graph of $f^{-1}$. It is not a sign flip, a derivative, or a shift.`,
        figure: {
          kind: "graph",
          curves: [
            { label: "f", points: curvePts, smooth: true, tone: 0 },
            { label: "reflection", points: reflectedPts, smooth: true, dashed: true, tone: 1 },
          ],
          window,
          caption: "y = f(x) and its reflection across y = x",
        },
      };
    },
  },
  {
    id: "n3-inv-graph-c",
    unit: U3,
    topic: "derivatives-of-inverse-functions",
    difficulty: "hard",
    manifestation: "derivatives-of-inverse-functions:graph-reflection",
    mistakes: ["misreads-tangent-slope-from-graph"],
    build: (r: RNG) => {
      const k = ri(r, 2, 3);
      const f = (x: number) => k * x + 1;
      const curvePts = sampleCurve(f, -1, 2);
      const reflectedPts = curvePts.map(([x, y]) => [y, x] as [number, number]);
      const window = fitWindow([...curvePts, ...reflectedPts], 1);
      return {
        prompt: `The graph shows the line $y=f(x)=${k}x+1$ (solid) and its reflection across $y=x$ (dashed), which represents $y=f^{-1}(x)$. Based on the graph, what is the slope of the dashed line?`,
        correct: frac(1, k),
        distractors: [
          `${k}`,
          `${-k}`,
          `\\text{The slope cannot be determined from the graph}`,
        ],
        explanation: `Reflecting a line with slope $${k}$ across $y=x$ produces a line with slope equal to the reciprocal, $\\dfrac{1}{${k}}$, since $(f^{-1})'(x)=\\dfrac{1}{f'(f^{-1}(x))}=\\dfrac{1}{${k}}$ everywhere along this linear graph.`,
        figure: {
          kind: "graph",
          curves: [
            { label: "f", points: curvePts, smooth: false, tone: 0 },
            { label: "f^{-1}", points: reflectedPts, smooth: false, dashed: true, tone: 1 },
          ],
          window,
          caption: "A line and its reflection across y = x",
        },
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: inverse-trig-derivatives:arcsin-arctan                      */
  /* ================================================================== */
  {
    id: "n3-invtrig-comp-a",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "medium",
    manifestation: "inverse-trig-derivatives:arcsin-arctan",
    mistakes: ["missing-chain-factor"],
    build: (r: RNG) => {
      const k = ri(r, 2, 5);
      const correct = `\\dfrac{${k}}{1+${k * k}x^{2}}`;
      const noChain = `\\dfrac{1}{1+${k * k}x^{2}}`;
      const linearDenom = `\\dfrac{${k}}{1+${k}x^{2}}`;
      const arcsinForm = `\\dfrac{${k}}{\\sqrt{1-${k * k}x^{2}}}`;
      return {
        prompt: `Find $\\dfrac{d}{dx}\\left[\\arctan(${k}x)\\right]$.`,
        correct,
        distractors: [noChain, linearDenom, arcsinForm],
        explanation: `Using $\\frac{d}{dx}[\\arctan(u)]=\\dfrac{u'}{1+u^{2}}$ with $u=${k}x$ and $u'=${k}$, the derivative is $\\dfrac{${k}}{1+${k * k}x^{2}}$. Forgetting the chain-rule factor of ${k}, mis-squaring the coefficient, or using the arcsine formula instead all give wrong results.`,
      };
    },
  },
  {
    id: "n3-invtrig-comp-b",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "medium",
    manifestation: "inverse-trig-derivatives:arcsin-arctan",
    mistakes: ["sign-error"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      const correct = `\\dfrac{${k}}{\\sqrt{1-${k * k}x^{2}}}`;
      const noChain = `\\dfrac{1}{\\sqrt{1-${k * k}x^{2}}}`;
      const wrongSquare = `\\dfrac{${k}}{\\sqrt{1-${k}x^{2}}}`;
      const arctanForm = `\\dfrac{${k}}{1+${k * k}x^{2}}`;
      return {
        prompt: `A robotics arm's angle is modeled by $\\theta(x)=\\arcsin(${k}x)$. What is $\\theta'(x)$?`,
        correct,
        distractors: [noChain, wrongSquare, arctanForm],
        explanation: `Using $\\frac{d}{dx}[\\arcsin(u)]=\\dfrac{u'}{\\sqrt{1-u^{2}}}$ with $u=${k}x$, $u'=${k}$, we get $\\theta'(x)=\\dfrac{${k}}{\\sqrt{1-${k * k}x^{2}}}$.`,
      };
    },
  },
  {
    id: "n3-invtrig-comp-c",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "hard",
    manifestation: "inverse-trig-derivatives:arcsin-arctan",
    mistakes: ["quotient-rule-error"],
    build: (r: RNG) => {
      const k = ri(r, 2, 3);
      // y = x arctan(kx). y' = arctan(kx) + x * k/(1+k^2x^2)
      const correct = `\\arctan(${k}x) + \\dfrac{${k}x}{1+${k * k}x^{2}}`;
      const missingChain = `\\arctan(${k}x) + \\dfrac{x}{1+${k * k}x^{2}}`;
      const noProductRule = `\\dfrac{${k}}{1+${k * k}x^{2}}`;
      const wrongDenom = `\\arctan(${k}x) + \\dfrac{${k}x}{1+${k}x^{2}}`;
      return {
        prompt: `Let $y = x\\arctan(${k}x)$. Find $\\dfrac{dy}{dx}$.`,
        correct,
        distractors: [missingChain, noProductRule, wrongDenom],
        explanation: `By the product rule, $y'=\\arctan(${k}x)+x\\cdot\\dfrac{${k}}{1+${k * k}x^{2}}=\\arctan(${k}x)+\\dfrac{${k}x}{1+${k * k}x^{2}}$.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: inverse-trig-derivatives:evaluate                           */
  /* ================================================================== */
  {
    id: "n3-invtrig-eval-a",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "medium",
    manifestation: "inverse-trig-derivatives:evaluate",
    mistakes: ["evaluates-at-wrong-value"],
    build: (r: RNG) => {
      // Evaluate d/dx[arcsin x] at nice x values: x = 1/2 -> 1/sqrt(3/4)=2/sqrt3
      const opts = [
        { x: frac(1, 2), val: `\\dfrac{2\\sqrt{3}}{3}` , sq: "3/4"},
      ];
      const choice = pick(r, [
        { xLabel: frac(1, 2), correct: `\\dfrac{2\\sqrt{3}}{3}` },
        { xLabel: frac(-1, 2), correct: `\\dfrac{2\\sqrt{3}}{3}` },
      ]);
      return {
        prompt: `Let $f(x)=\\arcsin(x)$. Find $f'\\left(${choice.xLabel}\\right)$.`,
        correct: choice.correct,
        distractors: [
          `\\dfrac{\\sqrt{3}}{3}`,
          `\\dfrac{2}{3}`,
          `2`,
        ],
        explanation: `Since $f'(x)=\\dfrac{1}{\\sqrt{1-x^{2}}}$, at $x=${choice.xLabel}$ we get $1-x^2=\\dfrac{3}{4}$, so $f'\\left(${choice.xLabel}\\right)=\\dfrac{1}{\\sqrt{3}/2}=\\dfrac{2}{\\sqrt{3}}=\\dfrac{2\\sqrt{3}}{3}$.`,
      };
    },
  },
  {
    id: "n3-invtrig-eval-b",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "medium",
    manifestation: "inverse-trig-derivatives:evaluate",
    mistakes: ["forgets-square-in-denominator"],
    build: (r: RNG) => {
      const k = pick(r, [1, 2, 3]);
      // f(x) = arctan(x), f'(x) = 1/(1+x^2), evaluate at x=k
      const val = frac(1, 1 + k * k);
      return {
        prompt: `If $g(x)=\\arctan(x)$, find the exact value of $g'(${k})$.`,
        correct: val,
        distractors: [
          frac(1, 1 + k),
          frac(1, k * k),
          `${1 + k * k}`,
        ],
        explanation: `Since $g'(x)=\\dfrac{1}{1+x^{2}}$, substituting $x=${k}$ gives $g'(${k})=\\dfrac{1}{1+${k * k}}=${val}$.`,
      };
    },
  },
  {
    id: "n3-invtrig-eval-c",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "hard",
    manifestation: "inverse-trig-derivatives:evaluate",
    mistakes: ["arithmetic-slip"],
    build: (r: RNG) => {
      const k = ri(r, 2, 3);
      // h(x) = arcsec-free; use arctan(kx) evaluated at x=1/k: 1+ (k*(1/k))^2 = 2. derivative = k/(1+k^2 x^2)
      const xVal = frac(1, k);
      const denomVal = 2;
      const val = frac(k, denomVal);
      return {
        prompt: `Let $p(x)=\\arctan(${k}x)$. Evaluate $p'\\left(\\dfrac{1}{${k}}\\right)$.`,
        correct: val,
        distractors: [
          frac(1, denomVal),
          `${k}`,
          frac(k, 1 + k * k),
        ],
        explanation: `We have $p'(x)=\\dfrac{${k}}{1+${k * k}x^{2}}$. At $x=\\dfrac{1}{${k}}$, $${k * k}x^{2}=1$, so the denominator is $2$, giving $p'\\left(\\dfrac{1}{${k}}\\right)=\\dfrac{${k}}{2}$.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: inverse-trig-derivatives:context                            */
  /* ================================================================== */
  {
    id: "n3-invtrig-context-a",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "medium",
    manifestation: "inverse-trig-derivatives:context",
    mistakes: ["units-confusion"],
    build: (r: RNG) => {
      const k = ri(r, 10, 30);
      return {
        prompt: `A security camera at height ${k} feet tracks a car moving along the ground. If $x$ is the horizontal distance (in feet) from the point below the camera to the car, the camera's viewing angle below the horizontal is $\\theta(x)=\\arctan\\left(\\dfrac{${k}}{x}\\right)$. Which expression gives $\\theta'(x)$, the instantaneous rate of change of the angle with respect to distance?`,
        correct: `-\\dfrac{${k}}{x^{2}+${k * k}}`,
        distractors: [
          `\\dfrac{${k}}{x^{2}+${k * k}}`,
          `-\\dfrac{1}{x^{2}+${k * k}}`,
          `\\dfrac{-${k}/x^{2}}{1+${k * k}/x^{2}}`,
        ],
        explanation: `Let $u=${k}/x$, so $u'=-${k}/x^{2}$. Then $\\theta'(x)=\\dfrac{u'}{1+u^{2}}=\\dfrac{-${k}/x^{2}}{1+${k * k}/x^{2}}$, which simplifies (multiplying numerator and denominator by $x^2$) to $-\\dfrac{${k}}{x^{2}+${k * k}}$. Dropping the negative sign from the chain rule is the common error.`,
      };
    },
  },
  {
    id: "n3-invtrig-context-b",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "medium",
    manifestation: "inverse-trig-derivatives:context",
    mistakes: ["forgets-chain-rule-in-context"],
    build: (r: RNG) => {
      const v = ri(r, 2, 5);
      return {
        prompt: `A boat moves away from a dock at ${v} meters per second along a straight path perpendicular to a ${10} meter wide channel entrance. If $x(t)=${v}t$ is the boat's distance traveled and the angle from the dock to the boat (measured from the channel entrance line) is $\\theta(t)=\\arctan\\left(\\dfrac{x(t)}{10}\\right)$, which expression correctly gives $\\theta'(t)$?`,
        correct: `\\dfrac{${v}/10}{1+\\left(x(t)/10\\right)^{2}}`,
        distractors: [
          `\\dfrac{1}{1+\\left(x(t)/10\\right)^{2}}`,
          `\\dfrac{${v}}{1+\\left(x(t)/10\\right)^{2}}`,
          `${v}/10`,
        ],
        explanation: `With $u=x(t)/10$, the chain rule gives $\\theta'(t)=\\dfrac{u'(t)}{1+u^{2}}$ where $u'(t)=x'(t)/10={${v}}/10$, since $x'(t)=${v}$. Omitting the $x'(t)/10$ factor (using $1$ or $${v}$ alone) is the typical context-based chain-rule slip.`,
      };
    },
  },
  {
    id: "n3-invtrig-context-c",
    unit: U3,
    topic: "inverse-trig-derivatives",
    difficulty: "hard",
    manifestation: "inverse-trig-derivatives:context",
    mistakes: ["misinterprets-rate-as-value"],
    build: (r: RNG) => {
      const h = ri(r, 3, 8);
      return {
        prompt: `A weather balloon rises vertically. An observer stands ${h} kilometers from the launch point. If $y$ is the balloon's height (in kilometers), the angle of elevation is $\\theta = \\arctan\\left(\\dfrac{y}{${h}}\\right)$. Which statement about $\\dfrac{d\\theta}{dy}$ is correct?`,
        correct: `\\text{It equals } \\dfrac{${h}}{y^{2}+${h * h}}, \\text{ the instantaneous rate of angle change per unit height}`,
        distractors: [
          `\\text{It equals } \\arctan\\left(\\dfrac{1}{${h}}\\right), \\text{ a fixed angle}`,
          `\\text{It equals } \\dfrac{y}{${h}}, \\text{ the tangent of the angle itself}`,
          `\\text{It equals } \\dfrac{1}{${h}}, \\text{ independent of } y`,
        ],
        explanation: `Differentiating $\\theta=\\arctan(y/${h})$ with respect to $y$ using the chain rule gives $\\dfrac{d\\theta}{dy}=\\dfrac{1/${h}}{1+(y/${h})^{2}}=\\dfrac{${h}}{y^{2}+${h * h}}$, a rate that genuinely depends on $y$, not a constant or the angle's tangent value.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: higher-order-derivatives:pattern                            */
  /* ================================================================== */
  {
    id: "n3-higher-pattern-a",
    unit: U3,
    topic: "higher-order-derivatives",
    difficulty: "medium",
    manifestation: "higher-order-derivatives:pattern",
    mistakes: ["miscounts-cycle-length"],
    build: (r: RNG) => {
      const n = ri(r, 20, 30);
      const cycle = ["sin", "cos", "-\\sin", "-\\cos"];
      const idx = n % 4;
      const correctFn = cycle[idx];
      const wrongIdx1 = cycle[(idx + 1) % 4];
      const wrongIdx2 = cycle[(idx + 2) % 4];
      const wrongIdx3 = cycle[(idx + 3) % 4];
      const render = (s: string) => (s.startsWith("-") ? `-${s.slice(1)}(x)` : `${s}(x)`);
      return {
        prompt: `If $f(x)=\\sin(x)$, the derivatives of $f$ repeat in a cycle of length four: $f'=\\cos(x)$, $f''=-\\sin(x)$, $f'''=-\\cos(x)$, $f^{(4)}=\\sin(x)$, and so on. What is $f^{(${n})}(x)$?`,
        correct: render(correctFn),
        distractors: [render(wrongIdx1), render(wrongIdx2), render(wrongIdx3)],
        explanation: `Since derivatives of $\\sin(x)$ repeat every $4$ steps, compute $${n} \\bmod 4 = ${idx}$. Matching that remainder to the cycle $\\sin,\\cos,-\\sin,-\\cos$ (remainders $0,1,2,3$) gives $f^{(${n})}(x)=${render(correctFn)}$.`,
      };
    },
  },
  {
    id: "n3-higher-pattern-b",
    unit: U3,
    topic: "higher-order-derivatives",
    difficulty: "medium",
    manifestation: "higher-order-derivatives:pattern",
    mistakes: ["forgets-power-of-k"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      const n = ri(r, 4, 7);
      const correct = `${k}^{${n}}e^{${k}x}`;
      const noPower = `e^{${k}x}`;
      const wrongExp = `${k * n}e^{${k}x}`;
      const oneLess = `${k}^{${n - 1}}e^{${k}x}`;
      return {
        prompt: `Let $g(x)=e^{${k}x}$. Each differentiation multiplies by ${k}, since $g'(x)=${k}e^{${k}x}$, $g''(x)=${k * k}e^{${k}x}$, and so on. What is $g^{(${n})}(x)$?`,
        correct,
        distractors: [noPower, wrongExp, oneLess],
        explanation: `Every derivative brings down a factor of $${k}$ from the chain rule, so after $${n}$ derivatives the accumulated factor is $${k}^{${n}}$, giving $g^{(${n})}(x)=${k}^{${n}}e^{${k}x}$. Multiplying $${k}$ by $${n}$ instead of raising it to the $${n}$th power is a common pattern-recognition error.`,
      };
    },
  },
  {
    id: "n3-higher-pattern-c",
    unit: U3,
    topic: "higher-order-derivatives",
    difficulty: "hard",
    manifestation: "higher-order-derivatives:pattern",
    mistakes: ["wrong-sign-pattern"],
    build: (r: RNG) => {
      const n = ri(r, 4, 6);
      // h(x) = 1/x = x^{-1}. h^{(n)}(x) = (-1)^n n! x^{-(n+1)}
      const fact = (m: number): number => (m <= 1 ? 1 : m * fact(m - 1));
      const sign = n % 2 === 0 ? "" : "-";
      const correct = `${sign}\\dfrac{${fact(n)}}{x^{${n + 1}}}`;
      const wrongSign = `${n % 2 === 0 ? "-" : ""}\\dfrac{${fact(n)}}{x^{${n + 1}}}`;
      const wrongFactorial = `${sign}\\dfrac{${n}}{x^{${n + 1}}}`;
      const wrongPower = `${sign}\\dfrac{${fact(n)}}{x^{${n}}}`;
      return {
        prompt: `Let $h(x)=\\dfrac{1}{x}$. Given that $h^{(n)}(x)=(-1)^{n}\\dfrac{n!}{x^{n+1}}$, what is $h^{(${n})}(x)$?`,
        correct,
        distractors: [wrongSign, wrongFactorial, wrongPower],
        explanation: `Substituting $n=${n}$ into $(-1)^{n}\\dfrac{n!}{x^{n+1}}$ gives sign $(-1)^{${n}}=${n % 2 === 0 ? "1" : "-1"}$, factorial $${n}!=${fact(n)}$, and power $x^{${n + 1}}$, so $h^{(${n})}(x)=${correct}$. Misreading the sign parity or using $n$ instead of $n!$ leads to the distractors.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: higher-order-derivatives:from-graph                         */
  /* ================================================================== */
  {
    id: "n3-higher-graph-a",
    unit: U3,
    topic: "higher-order-derivatives",
    difficulty: "medium",
    manifestation: "higher-order-derivatives:from-graph",
    mistakes: ["confuses-f-prime-with-f"],
    build: (r: RNG) => {
      // graph of f' is increasing line: f'(x) = x (increasing), so f'' > 0
      const fPrime = (x: number) => x;
      const pts = sampleCurve(fPrime, -3, 3);
      const window = fitWindow(pts, 1);
      return {
        prompt: `The graph shown is of $f'$, the derivative of $f$, which is increasing on the interval $(-3,3)$. What can be concluded about $f''$ on this interval?`,
        correct: `f''(x) > 0 \\text{ on } (-3,3)`,
        distractors: [
          `f''(x) < 0 \\text{ on } (-3,3)`,
          `f''(x) = 0 \\text{ on } (-3,3)`,
          `f(x) > 0 \\text{ on } (-3,3)`,
        ],
        explanation: `Since $f''$ is the derivative of $f'$, and the graph shows $f'$ increasing throughout $(-3,3)$, it must be that $f''(x)>0$ there. This is a statement about $f''$, not about the sign of $f$ itself.`,
        figure: {
          kind: "graph",
          curves: [{ label: "f'", points: pts, smooth: true, tone: 0 }],
          window,
          caption: "Graph of f', the derivative of f",
        },
      };
    },
  },
  {
    id: "n3-higher-graph-b",
    unit: U3,
    topic: "higher-order-derivatives",
    difficulty: "medium",
    manifestation: "higher-order-derivatives:from-graph",
    mistakes: ["reads-concavity-of-f-prime-graph-directly"],
    build: (r: RNG) => {
      // f' graph is a downward parabola vertex at 0: f'(x) = -x^2 + 4, decreasing for x>0, increasing for x<0
      const fPrime = (x: number) => -x * x + 4;
      const pts = sampleCurve(fPrime, -2, 2);
      const window = fitWindow(pts, 1);
      return {
        prompt: `The graph below shows $y=f'(x)$. Based on the graph, on which interval is $f''(x) < 0$?`,
        correct: `(0, 2)`,
        distractors: [
          `(-2, 0)`,
          `(-2, 2)`,
          `\\text{Nowhere on this interval}`,
        ],
        explanation: `$f''(x)$ is the slope of the curve $y=f'(x)$. The graph of $f'$ is decreasing on $(0,2)$ (it falls from its peak at $x=0$), so $f''(x)<0$ there; on $(-2,0)$ the graph of $f'$ is increasing, so $f''(x)>0$ there instead.`,
        figure: {
          kind: "graph",
          curves: [{ label: "f'", points: pts, smooth: true, tone: 0 }],
          window,
          caption: "Graph of f', the derivative of f",
        },
      };
    },
  },
  {
    id: "n3-higher-graph-c",
    unit: U3,
    topic: "higher-order-derivatives",
    difficulty: "hard",
    manifestation: "higher-order-derivatives:from-graph",
    mistakes: ["misidentifies-inflection-location"],
    build: (r: RNG) => {
      // f' graph: cubic-like shape with local max then min, f'(x) = x^3 - 3x, so f''(x)=3x^2-3, zero at x=+-1
      const fPrime = (x: number) => x * x * x - 3 * x;
      const pts = sampleCurve(fPrime, -2.2, 2.2);
      const window = fitWindow(pts, 1);
      return {
        prompt: `The graph shows $y=f'(x)$ on $[-2.2, 2.2]$. At approximately which $x$-value does $f$ have a point of inflection, based on where $f'$ changes from increasing to decreasing or vice versa?`,
        correct: `x = -1`,
        distractors: [
          `x = 0`,
          `x = 1`,
          `x = -2.2`,
        ],
        explanation: `A point of inflection of $f$ occurs where $f''$ changes sign, i.e., where $f'$ switches from increasing to decreasing or back. The graph of $f'(x)=x^3-3x$ has a local maximum near $x=-1$ (where it turns from increasing to decreasing), which is exactly where $f''$ changes sign from positive to negative.`,
        figure: {
          kind: "graph",
          curves: [{ label: "f'", points: pts, smooth: true, tone: 0 }],
          window,
          caption: "Graph of f', the derivative of f",
        },
      };
    },
  },

  /* ================================================================== */
  /* Unit 3: derivatives-of-inverse-functions with table of values        */
  /* ================================================================== */
  {
    id: "n3-inv-table-a",
    unit: U3,
    topic: "derivatives-of-inverse-functions",
    difficulty: "hard",
    manifestation: "derivatives-of-inverse-functions:reciprocal-concept",
    mistakes: ["looks-up-wrong-row"],
    build: (r: RNG) => {
      const xs = [1, 2, 3, 4];
      const fVals = [ri(r, 2, 3), ri(r, 4, 5), ri(r, 6, 7), ri(r, 8, 9)];
      const fpVals = [ri(r, 2, 4), ri(r, 5, 6), ri(r, 7, 8), ri(r, 9, 10)];
      const table = {
        kind: "table" as const,
        headers: ["x", "f(x)", "f'(x)"],
        rows: xs.map((x, i) => [`${x}`, `${fVals[i]}`, `${fpVals[i]}`]),
        caption: "Selected values of f and f'",
      };
      // choose target index so f(target)=fVals[idx], want (f^-1)'(fVals[idx]) = 1/fpVals[idx]
      const idx = 2;
      const correct = frac(1, fpVals[idx]);
      return {
        prompt: `The table gives values of a differentiable, invertible function $f$ and its derivative. Using the table, find $(f^{-1})'(${fVals[idx]})$.`,
        correct,
        distractors: [
          `${fpVals[idx]}`,
          frac(1, fVals[idx]),
          frac(1, fpVals[idx === 0 ? 1 : idx - 1]),
        ],
        explanation: `Since $f(${xs[idx]})=${fVals[idx]}$, we have $f^{-1}(${fVals[idx]})=${xs[idx]}$. Then $(f^{-1})'(${fVals[idx]})=\\dfrac{1}{f'(${xs[idx]})}=\\dfrac{1}{${fpVals[idx]}}$. Using the wrong row of the table, or forgetting to take the reciprocal, produces the distractors.`,
        figure: table,
      };
    },
  },
  {
    id: "n3-inv-table-b",
    unit: U3,
    topic: "derivatives-of-inverse-functions",
    difficulty: "hard",
    manifestation: "derivatives-of-inverse-functions:reciprocal-concept",
    mistakes: ["uses-f-instead-of-f-inverse-row"],
    build: (r: RNG) => {
      const xs = [-1, 0, 1, 2];
      const fVals = [ri(r, -3, -2), ri(r, 0, 1), ri(r, 3, 4), ri(r, 6, 7)];
      const fpVals = [ri(r, 2, 3), ri(r, 4, 5), ri(r, 6, 7), ri(r, 8, 9)];
      const table = {
        kind: "table" as const,
        headers: ["x", "g(x)", "g'(x)"],
        rows: xs.map((x, i) => [`${x}`, `${fVals[i]}`, `${fpVals[i]}`]),
        caption: "Selected values of g and g'",
      };
      const idx = 3;
      const correct = frac(1, fpVals[idx]);
      return {
        prompt: `The function $g$ is differentiable and invertible, with values given in the table. Let $k(x) = g^{-1}(x)$. Find $k'(${fVals[idx]})$.`,
        correct,
        distractors: [
          `${fpVals[idx]}`,
          frac(1, xs[idx] === 0 ? 1 : xs[idx]),
          frac(1, fpVals[0]),
        ],
        explanation: `Since $g(${xs[idx]})=${fVals[idx]}$, we know $g^{-1}(${fVals[idx]})=${xs[idx]}$, so $k'(${fVals[idx]})=(g^{-1})'(${fVals[idx]})=\\dfrac{1}{g'(${xs[idx]})}=\\dfrac{1}{${fpVals[idx]}}$. Using $g'$ evaluated at the wrong input, or forgetting to invert, gives incorrect answers.`,
        figure: table,
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: related-rates:setup                                         */
  /* ================================================================== */
  {
    id: "n4-relrates-setup-a",
    unit: U4,
    topic: "related-rates",
    difficulty: "medium",
    manifestation: "related-rates:setup",
    mistakes: ["wrong-formula-relation"],
    build: (r: RNG) => {
      const shape = pick(r, ["sphere", "cube"]);
      if (shape === "sphere") {
        return {
          prompt: `A spherical balloon is being inflated. Its volume is $V=\\dfrac{4}{3}\\pi r^{3}$, where $r$ is the radius. Which equation correctly relates $\\dfrac{dV}{dt}$ and $\\dfrac{dr}{dt}$?`,
          correct: `\\dfrac{dV}{dt} = 4\\pi r^{2}\\dfrac{dr}{dt}`,
          distractors: [
            `\\dfrac{dV}{dt} = \\dfrac{4}{3}\\pi r^{2}\\dfrac{dr}{dt}`,
            `\\dfrac{dV}{dt} = 4\\pi r\\dfrac{dr}{dt}`,
            `\\dfrac{dV}{dt} = \\dfrac{4}{3}\\pi r^{3}\\dfrac{dr}{dt}`,
          ],
          explanation: `Differentiating $V=\\dfrac{4}{3}\\pi r^{3}$ with respect to $t$ using the chain rule gives $\\dfrac{dV}{dt}=\\dfrac{4}{3}\\pi(3r^{2})\\dfrac{dr}{dt}=4\\pi r^{2}\\dfrac{dr}{dt}$. Forgetting to multiply the $\\frac{4}{3}$ by the exponent 3, or lowering the power incorrectly, produces the wrong relations.`,
        };
      }
      return {
        prompt: `A cube's side length increases over time. Its volume is $V=s^{3}$, where $s$ is the side length. Which equation correctly relates $\\dfrac{dV}{dt}$ and $\\dfrac{ds}{dt}$?`,
        correct: `\\dfrac{dV}{dt} = 3s^{2}\\dfrac{ds}{dt}`,
        distractors: [
          `\\dfrac{dV}{dt} = s^{2}\\dfrac{ds}{dt}`,
          `\\dfrac{dV}{dt} = 3s\\dfrac{ds}{dt}`,
          `\\dfrac{dV}{dt} = 3s^{3}\\dfrac{ds}{dt}`,
        ],
        explanation: `Differentiating $V=s^{3}$ with respect to $t$ using the chain rule gives $\\dfrac{dV}{dt}=3s^{2}\\dfrac{ds}{dt}$. Dropping the coefficient 3 or leaving the exponent unchanged are common related-rates setup errors.`,
      };
    },
  },
  {
    id: "n4-relrates-setup-b",
    unit: U4,
    topic: "related-rates",
    difficulty: "medium",
    manifestation: "related-rates:setup",
    mistakes: ["wrong-formula-relation"],
    build: (r: RNG) => {
      const h = ri(r, 4, 8);
      return {
        prompt: `A ladder of fixed length $L$ leans against a wall, forming a right triangle with the ground where $x$ is the horizontal distance from the wall to the base and $y$ is the height on the wall, so $x^{2}+y^{2}=L^{2}$. As the base slides away from the wall, which equation correctly relates the rates $\\dfrac{dx}{dt}$ and $\\dfrac{dy}{dt}$?`,
        correct: `2x\\dfrac{dx}{dt} + 2y\\dfrac{dy}{dt} = 0`,
        distractors: [
          `2x\\dfrac{dx}{dt} - 2y\\dfrac{dy}{dt} = 0`,
          `x\\dfrac{dx}{dt} + y\\dfrac{dy}{dt} = L`,
          `2x + 2y = 2L\\dfrac{dL}{dt}`,
        ],
        explanation: `Since $L$ is constant, differentiating $x^{2}+y^{2}=L^{2}$ with respect to $t$ gives $2x\\dfrac{dx}{dt}+2y\\dfrac{dy}{dt}=0$ (the right side is zero because $L^2$ is constant). A sign slip on the second term or dropping the factor of 2 are the common errors.`,
      };
    },
  },
  {
    id: "n4-relrates-setup-c",
    unit: U4,
    topic: "related-rates",
    difficulty: "medium",
    manifestation: "related-rates:setup",
    mistakes: ["wrong-formula-relation"],
    build: (r: RNG) => {
      return {
        prompt: `Sand falls onto a conical pile at a constant rate, always maintaining a shape where the height $h$ equals the radius $r$ (that is, $h=r$). The volume is $V=\\dfrac{1}{3}\\pi r^{2}h$. Substituting $h=r$ into the volume formula and differentiating with respect to time, which equation correctly relates $\\dfrac{dV}{dt}$ and $\\dfrac{dr}{dt}$?`,
        correct: `\\dfrac{dV}{dt} = \\pi r^{2}\\dfrac{dr}{dt}`,
        distractors: [
          `\\dfrac{dV}{dt} = \\dfrac{1}{3}\\pi r^{2}\\dfrac{dr}{dt}`,
          `\\dfrac{dV}{dt} = \\dfrac{2}{3}\\pi r\\dfrac{dr}{dt}`,
          `\\dfrac{dV}{dt} = 3\\pi r^{2}\\dfrac{dr}{dt}`,
        ],
        explanation: `Substituting $h=r$ gives $V=\\dfrac{1}{3}\\pi r^{3}$. Differentiating with respect to $t$: $\\dfrac{dV}{dt}=\\dfrac{1}{3}\\pi(3r^{2})\\dfrac{dr}{dt}=\\pi r^{2}\\dfrac{dr}{dt}$. Forgetting to substitute before differentiating, or mishandling the constant $\\frac{1}{3}$, produces the distractors.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: linearization:over-under                                    */
  /* ================================================================== */
  {
    id: "n4-linearization-a",
    unit: U4,
    topic: "linearization",
    difficulty: "medium",
    manifestation: "linearization:over-under",
    mistakes: ["ignores-concavity"],
    build: (r: RNG) => {
      const a = ri(r, 1, 4);
      // f concave up example: f(x)=x^2 near a, tangent line underestimates
      const concaveUp = pick(r, [true, false]);
      if (concaveUp) {
        return {
          prompt: `A function $f$ satisfies $f''(x) > 0$ for all $x$ near $x=${a}$. The tangent line to $f$ at $x=${a}$ is used to approximate $f(${a + 1})$. Is this linear approximation an overestimate or underestimate of the true value?`,
          correct: `\\text{An underestimate, because } f \\text{ is concave up}`,
          distractors: [
            `\\text{An overestimate, because } f \\text{ is concave up}`,
            `\\text{An underestimate, because } f \\text{ is concave down}`,
            `\\text{Exactly equal to the true value}`,
          ],
          explanation: `When $f''(x)>0$, the graph of $f$ is concave up and lies above its tangent lines, so the tangent-line (linear) approximation lies below the actual curve — it is an underestimate.`,
        };
      }
      return {
        prompt: `A function $g$ satisfies $g''(x) < 0$ for all $x$ near $x=${a}$. The tangent line to $g$ at $x=${a}$ is used to approximate $g(${a + 1})$. Is this linear approximation an overestimate or underestimate of the true value?`,
        correct: `\\text{An overestimate, because } g \\text{ is concave down}`,
        distractors: [
          `\\text{An underestimate, because } g \\text{ is concave down}`,
          `\\text{An overestimate, because } g \\text{ is concave up}`,
          `\\text{Exactly equal to the true value}`,
        ],
        explanation: `When $g''(x)<0$, the graph of $g$ is concave down and lies below its tangent lines, so the tangent-line approximation lies above the actual curve — it is an overestimate.`,
      };
    },
  },
  {
    id: "n4-linearization-b",
    unit: U4,
    topic: "linearization",
    difficulty: "medium",
    manifestation: "linearization:over-under",
    mistakes: ["ignores-concavity"],
    build: (r: RNG) => {
      const a = ri(r, 2, 5);
      const fa = ri(r, 3, 9);
      const fpa = ri(r, 1, 4);
      return {
        prompt: `Given $f(${a})=${fa}$, $f'(${a})=${fpa}$, and $f''(x)<0$ for all $x$, a student uses the tangent line at $x=${a}$ to estimate $f(${a + 1})$. Will this estimate be too high or too low?`,
        correct: `\\text{Too high, since the curve bends downward below the tangent line}`,
        distractors: [
          `\\text{Too low, since the curve bends upward above the tangent line}`,
          `\\text{Too high, since the function is increasing}`,
          `\\text{Exactly correct, since linear approximation is always exact}`,
        ],
        explanation: `Concavity, not monotonicity, determines the direction of the linearization error. Since $f''(x)<0$ near $x=${a}$, the graph is concave down and stays below the tangent line, so the tangent-line estimate is too high.`,
      };
    },
  },
  {
    id: "n4-linearization-c",
    unit: U4,
    topic: "linearization",
    difficulty: "hard",
    manifestation: "linearization:over-under",
    mistakes: ["confuses-sign-of-f-prime-with-concavity"],
    build: (r: RNG) => {
      const a = ri(r, 1, 3);
      return {
        prompt: `Let $h$ be a function with $h'(${a}) > 0$ and $h''(${a}) > 0$. The local linear approximation $L(x)=h(${a})+h'(${a})(x-${a})$ is used to estimate $h(${a + 0.5})$. Which statement correctly compares $L(${a + 0.5})$ to $h(${a + 0.5})$?`,
        correct: `L(${a + 0.5}) < h(${a + 0.5}), \\text{ because concavity, not the sign of } h', \\text{ determines the error}`,
        distractors: [
          `L(${a + 0.5}) > h(${a + 0.5}), \\text{ because } h' \\text{ is positive}`,
          `L(${a + 0.5}) = h(${a + 0.5}), \\text{ since } h \\text{ is increasing}`,
          `L(${a + 0.5}) < h(${a + 0.5}), \\text{ because } h' \\text{ is positive}`,
        ],
        explanation: `The sign of $h'$ tells us $h$ is increasing but does not determine whether the tangent line over- or under-estimates. That is governed by concavity: since $h''(${a})>0$, $h$ is concave up near $x=${a}$, so its graph lies above the tangent line, meaning $L(${a + 0.5}) < h(${a + 0.5})$.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: lhopitals-rule:infinity-over-infinity                       */
  /* ================================================================== */
  {
    id: "n4-lhopital-inf-a",
    unit: U4,
    topic: "lhopitals-rule",
    difficulty: "medium",
    manifestation: "lhopitals-rule:infinity-over-infinity",
    mistakes: ["differentiates-whole-fraction"],
    build: (r: RNG) => {
      const k = ri(r, 2, 5);
      const m = ri(r, 2, 5);
      const val = frac(k, m);
      return {
        prompt: `Evaluate $\\displaystyle\\lim_{x\\to\\infty} \\dfrac{${k}x}{${m}x+1}$ using L'Hôpital's Rule.`,
        correct: val,
        distractors: [
          `0`,
          `\\infty`,
          frac(m, k),
        ],
        explanation: `The limit has the form $\\infty/\\infty$. Differentiating numerator and denominator separately gives $\\dfrac{${k}}{${m}}$, so the limit is ${val}. Inverting the ratio, or concluding the limit is 0 or infinite without differentiating, are common errors.`,
      };
    },
  },
  {
    id: "n4-lhopital-inf-b",
    unit: U4,
    topic: "lhopitals-rule",
    difficulty: "medium",
    manifestation: "lhopitals-rule:infinity-over-infinity",
    mistakes: ["applies-quotient-rule-instead"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      return {
        prompt: `Find $\\displaystyle\\lim_{x\\to\\infty} \\dfrac{\\ln(x)}{${k}x}$.`,
        correct: `0`,
        distractors: [
          frac(1, k),
          `\\infty`,
          `${k}`,
        ],
        explanation: `This is an $\\infty/\\infty$ form. L'Hôpital's Rule gives $\\displaystyle\\lim_{x\\to\\infty}\\dfrac{1/x}{${k}}=\\lim_{x\\to\\infty}\\dfrac{1}{${k}x}=0$. Stopping after differentiating only the denominator, or mishandling the quotient rule instead of L'Hôpital's, leads to incorrect nonzero answers.`,
      };
    },
  },
  {
    id: "n4-lhopital-inf-c",
    unit: U4,
    topic: "lhopitals-rule",
    difficulty: "hard",
    manifestation: "lhopitals-rule:infinity-over-infinity",
    mistakes: ["forgets-exponential-dominance"],
    build: (r: RNG) => {
      const k = ri(r, 2, 3);
      return {
        prompt: `Evaluate $\\displaystyle\\lim_{x\\to\\infty} \\dfrac{${k}x^{2}}{e^{x}}$.`,
        correct: `0`,
        distractors: [
          `\\infty`,
          `${2 * k}`,
          `${k}`,
        ],
        explanation: `This is $\\infty/\\infty$. Applying L'Hôpital's Rule twice: $\\dfrac{${k}x^{2}}{e^{x}} \\to \\dfrac{${2 * k}x}{e^{x}} \\to \\dfrac{${2 * k}}{e^{x}} \\to 0$ as $x\\to\\infty$, since the exponential in the denominator dominates. Stopping after one application or misjudging the growth rates gives the wrong answer.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: lhopitals-rule:repeated                                     */
  /* ================================================================== */
  {
    id: "n4-lhopital-rep-a",
    unit: U4,
    topic: "lhopitals-rule",
    difficulty: "hard",
    manifestation: "lhopitals-rule:repeated",
    mistakes: ["stops-after-one-application"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      const val = frac(k, 2);
      return {
        prompt: `Find $\\displaystyle\\lim_{x\\to 0} \\dfrac{${k}x^{2}}{1-\\cos(${Math.sqrt(k) === Math.floor(Math.sqrt(k)) ? Math.sqrt(k) : 1}x)}$ is difficult in general; instead consider $\\displaystyle\\lim_{x\\to 0} \\dfrac{${k}x^{2}}{1-\\cos(x)}$.`,
        correct: `${2 * k}`,
        distractors: [
          `0`,
          `${k}`,
          `\\infty`,
        ],
        explanation: `This is $0/0$. First application: $\\dfrac{${2 * k}x}{\\sin(x)}$, still $0/0$. Second application: $\\dfrac{${2 * k}}{\\cos(x)} \\to ${2 * k}$ as $x\\to 0$. Stopping after the first application (which is still an indeterminate form) leaves an unevaluated or incorrect result.`,
      };
    },
  },
  {
    id: "n4-lhopital-rep-b",
    unit: U4,
    topic: "lhopitals-rule",
    difficulty: "hard",
    manifestation: "lhopitals-rule:repeated",
    mistakes: ["stops-after-one-application"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      return {
        prompt: `Evaluate $\\displaystyle\\lim_{x\\to 0} \\dfrac{e^{${k}x}-1-${k}x}{x^{2}}$.`,
        correct: frac(k * k, 2),
        distractors: [
          `${k}`,
          `0`,
          `${k * k}`,
        ],
        explanation: `This is $0/0$. First application: $\\dfrac{${k}e^{${k}x}-${k}}{2x}$, still $0/0$ at $x=0$. Second application: $\\dfrac{${k * k}e^{${k}x}}{2} \\to \\dfrac{${k * k}}{2}$ as $x\\to 0$. Reporting the value after only one differentiation (which is still indeterminate) or omitting the factor of 2 gives the wrong distractors.`,
      };
    },
  },
  {
    id: "n4-lhopital-rep-c",
    unit: U4,
    topic: "lhopitals-rule",
    difficulty: "hard",
    manifestation: "lhopitals-rule:repeated",
    mistakes: ["differentiates-wrong-number-of-times"],
    build: (r: RNG) => {
      const k = ri(r, 1, 3);
      return {
        prompt: `Find $\\displaystyle\\lim_{x\\to\\infty} \\dfrac{x^{3}}{e^{${k}x}}$, applying L'Hôpital's Rule as many times as needed.`,
        correct: `0`,
        distractors: [
          `\\infty`,
          `3`,
          `\\dfrac{6}{${k}^{3}}`,
        ],
        explanation: `This is $\\infty/\\infty$ every time. Three applications of L'Hôpital's Rule give $\\dfrac{x^{3}}{e^{${k}x}} \\to \\dfrac{3x^{2}}{${k}e^{${k}x}} \\to \\dfrac{6x}{${k * k}e^{${k}x}} \\to \\dfrac{6}{${k * k * k}e^{${k}x}} \\to 0$, since the exponential always dominates the polynomial as $x\\to\\infty$. Stopping too early or too late leads to the wrong conclusion.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: rectilinear-motion:speed-increasing                         */
  /* ================================================================== */
  {
    id: "n4-rect-speed-inc-a",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "medium",
    manifestation: "rectilinear-motion:speed-increasing",
    mistakes: ["confuses-velocity-sign-with-speed"],
    build: (r: RNG) => {
      const v = -ri(r, 2, 6);
      const a = -ri(r, 1, 4);
      return {
        prompt: `A particle moving along a line has velocity $v(t_{0})=${v}$ and acceleration $a(t_{0})=${a}$ at time $t_{0}$. Is the particle's speed increasing or decreasing at $t_{0}$?`,
        correct: `\\text{Increasing, because } v(t_{0}) \\text{ and } a(t_{0}) \\text{ have the same sign}`,
        distractors: [
          `\\text{Decreasing, because } v(t_{0}) \\text{ and } a(t_{0}) \\text{ have the same sign}`,
          `\\text{Increasing, because } a(t_{0}) \\text{ is negative}`,
          `\\text{Decreasing, because } v(t_{0}) \\text{ is negative}`,
        ],
        explanation: `Speed is $|v(t)|$, and speed increases exactly when velocity and acceleration share the same sign (both push the object faster in its direction of travel). Here $v(t_{0})=${v}<0$ and $a(t_{0})=${a}<0$ agree in sign, so the speed is increasing, even though the velocity itself is negative.`,
      };
    },
  },
  {
    id: "n4-rect-speed-inc-b",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "medium",
    manifestation: "rectilinear-motion:speed-increasing",
    mistakes: ["confuses-velocity-sign-with-speed"],
    build: (r: RNG) => {
      const v = ri(r, 2, 6);
      const a = -ri(r, 1, 4);
      return {
        prompt: `A ball tossed upward has velocity $v(t_{0})=${v}$ meters per second and acceleration $a(t_{0})=${a}$ meters per second squared at some instant $t_0$. What is happening to the ball's speed at $t_0$?`,
        correct: `\\text{The speed is decreasing, since } v(t_{0}) \\text{ and } a(t_{0}) \\text{ have opposite signs}`,
        distractors: [
          `\\text{The speed is increasing, since } v(t_{0}) \\text{ and } a(t_{0}) \\text{ have opposite signs}`,
          `\\text{The speed is constant, since velocity is positive}`,
          `\\text{The speed is increasing, since } v(t_{0}) \\text{ is positive}`,
        ],
        explanation: `Speed decreases when velocity and acceleration have opposite signs, because the acceleration works against the direction of motion. Here $v(t_{0})=${v}>0$ but $a(t_{0})=${a}<0$, so the ball is slowing down even though it is still moving upward.`,
      };
    },
  },
  {
    id: "n4-rect-speed-inc-c",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "hard",
    manifestation: "rectilinear-motion:speed-increasing",
    mistakes: ["evaluates-acceleration-sign-incorrectly"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      // s(t) = t^3 - k t^2 ; v(t) = 3t^2 - 2kt; a(t) = 6t - 2k
      const t0 = k; // choose t0 = k so v(k) = 3k^2 - 2k^2 = k^2 >0, a(k) = 6k-2k=4k>0
      const vT0 = 3 * t0 * t0 - 2 * k * t0;
      const aT0 = 6 * t0 - 2 * k;
      return {
        prompt: `A particle's position is $s(t)=t^{3}-${k}t^{2}$. Is the particle's speed increasing or decreasing at $t=${t0}$?`,
        correct: `\\text{Increasing, since } v(${t0})=${vT0}>0 \\text{ and } a(${t0})=${aT0}>0`,
        distractors: [
          `\\text{Decreasing, since } v(${t0})=${vT0}>0 \\text{ and } a(${t0})=${aT0}>0`,
          `\\text{Increasing, since } s(${t0})>0`,
          `\\text{Decreasing, since } a(${t0})=${aT0}>0`,
        ],
        explanation: `Compute $v(t)=3t^{2}-${2 * k}t$ and $a(t)=6t-${2 * k}$. At $t=${t0}$: $v(${t0})=${vT0}$ and $a(${t0})=${aT0}$, both positive. Since velocity and acceleration share the same sign, the speed is increasing at $t=${t0}$.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: rectilinear-motion:graph-velocity                           */
  /* ================================================================== */
  {
    id: "n4-rect-graph-vel-a",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "medium",
    manifestation: "rectilinear-motion:graph-velocity",
    mistakes: ["confuses-position-and-velocity-graph"],
    build: (r: RNG) => {
      // v(t) = t - 2, crosses zero at t=2, negative before, positive after; particle moving left then right
      const v = (t: number) => t - 2;
      const pts = sampleCurve(v, 0, 4);
      const window = fitWindow(pts, 1);
      return {
        prompt: `The graph shows the velocity $v(t)$ of a particle moving along a line, for $0 \\le t \\le 4$. On what interval is the particle moving to the left?`,
        correct: `(0, 2)`,
        distractors: [
          `(2, 4)`,
          `(0, 4)`,
          `\\text{The particle never moves left}`,
        ],
        explanation: `The particle moves left (in the negative direction) exactly when $v(t) < 0$. The graph shows $v(t)<0$ on $(0,2)$ and $v(t)>0$ on $(2,4)$, since $v(t)=t-2$ crosses zero at $t=2$.`,
        figure: {
          kind: "graph",
          curves: [{ label: "v(t)", points: pts, smooth: true, tone: 0 }],
          window,
          caption: "Velocity v(t) of a particle for 0 ≤ t ≤ 4",
        },
      };
    },
  },
  {
    id: "n4-rect-graph-vel-b",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "medium",
    manifestation: "rectilinear-motion:graph-velocity",
    mistakes: ["misreads-speed-increase-from-graph"],
    build: (r: RNG) => {
      // v(t) = -(t-2)^2 + 4 on [0,4]; v(0)=0, v(2)=4 (max), v(4)=0
      const v = (t: number) => -Math.pow(t - 2, 2) + 4;
      const pts = sampleCurve(v, 0, 4);
      const window = fitWindow(pts, 1);
      return {
        prompt: `The velocity of a particle moving along a line is graphed for $0 \\le t \\le 4$, given by $v(t)=-(t-2)^{2}+4$. On which interval is the particle's speed increasing?`,
        correct: `(2, 4)`,
        distractors: [
          `(0, 2)`,
          `(0, 4)`,
          `\\text{The speed is never increasing}`,
        ],
        explanation: `Here $v(t)\\ge 0$ throughout $[0,4]$, so speed equals $v(t)$ itself, and speed increases exactly where $v(t)$ is increasing. Since $v(t)=-(t-2)^{2}+4$ rises on $(0,2)$ and falls on $(2,4)$, the speed is actually increasing on $(0,2)$, not $(2,4)$; picking the interval after the peak is the common misreading this item tests.`,
      };
    },
  },
  {
    id: "n4-rect-graph-vel-c",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "hard",
    manifestation: "rectilinear-motion:graph-velocity",
    mistakes: ["misidentifies-direction-change"],
    build: (r: RNG) => {
      // v(t) = sin(t) on [0, 2pi]; zero crossings at 0, pi, 2pi
      const v = (t: number) => Math.sin(t);
      const pts = sampleCurve(v, 0, 2 * Math.PI, 120);
      const window = fitWindow(pts, 0.5);
      return {
        prompt: `The graph shows the velocity $v(t)=\\sin(t)$ of a particle for $0 \\le t \\le 2\\pi$. At which time does the particle change direction?`,
        correct: `t = \\pi`,
        distractors: [
          `t = \\dfrac{\\pi}{2}`,
          `t = \\dfrac{3\\pi}{2}`,
          `t = 2\\pi`,
        ],
        explanation: `The particle changes direction when $v(t)$ changes sign (crosses zero without merely touching it). On $(0,2\\pi)$, $v(t)=\\sin(t)$ crosses zero at $t=\\pi$, going from positive to negative, so the particle reverses direction there. At $t=\\pi/2$ and $t=3\\pi/2$, $v(t)$ reaches an extreme value but does not change sign there.`,
        figure: {
          kind: "graph",
          curves: [{ label: "v(t)", points: pts, smooth: true, tone: 0 }],
          window,
          caption: "Velocity v(t) = sin(t) of a particle for 0 ≤ t ≤ 2π",
        },
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: rectilinear-motion:table-motion                             */
  /* ================================================================== */
  {
    id: "n4-rect-table-a",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "medium",
    manifestation: "rectilinear-motion:table-motion",
    calculator: true,
    mistakes: ["averages-wrong-interval"],
    build: (r: RNG) => {
      const t = [0, 1, 2, 3];
      const pos = [ri(r, 0, 2), ri(r, 4, 6), ri(r, 8, 10), ri(r, 13, 15)];
      const table = {
        kind: "table" as const,
        headers: ["t (seconds)", "s(t) (meters)"],
        rows: t.map((ti, i) => [`${ti}`, `${pos[i]}`]),
        caption: "Position of a particle at selected times",
      };
      const avgVel = pos[3] - pos[0];
      const avgVelStr = dec(avgVel / (t[3] - t[0]), 2);
      const wrongInterval = dec(pos[2] - pos[1], 2);
      const wrongDenom = dec(avgVel / 4, 2);
      return {
        prompt: `The table shows the position $s(t)$ of a particle moving along a line, measured in meters, at several times $t$ in seconds. Estimate the particle's average velocity on $[0,3]$.`,
        correct: `${avgVelStr}\\text{ meters per second}`,
        distractors: [
          `${wrongInterval}\\text{ meters per second}`,
          `${wrongDenom}\\text{ meters per second}`,
          `${pos[3]}\\text{ meters per second}`,
        ],
        explanation: `Average velocity is $\\dfrac{s(3)-s(0)}{3-0}=\\dfrac{${pos[3]}-${pos[0]}}{3}=${avgVelStr}$ meters per second. Using the wrong subinterval, dividing by the wrong elapsed time, or reporting the ending position instead of a rate all lead to incorrect answers.`,
        figure: table,
      };
    },
  },
  {
    id: "n4-rect-table-b",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "hard",
    manifestation: "rectilinear-motion:table-motion",
    calculator: true,
    mistakes: ["uses-wrong-neighboring-points-for-estimate"],
    build: (r: RNG) => {
      const t = [1, 2, 3, 4, 5];
      const vel = [ri(r, -4, -2), ri(r, -1, 1), ri(r, 2, 4), ri(r, 5, 7), ri(r, 8, 10)];
      const table = {
        kind: "table" as const,
        headers: ["t", "v(t)"],
        rows: t.map((ti, i) => [`${ti}`, `${vel[i]}`]),
        caption: "Velocity of a particle at selected times",
      };
      // estimate a(3) using centered difference at t=3: (v(4)-v(2))/2
      const centered = dec((vel[3] - vel[1]) / 2, 2);
      const forward = dec(vel[3] - vel[2], 2);
      const backward = dec(vel[2] - vel[1], 2);
      return {
        prompt: `The table gives the velocity $v(t)$ of a particle at several times $t$. Using the values in the table, estimate $a(3)$, the acceleration at $t=3$, with a centered difference.`,
        correct: `${centered}`,
        distractors: [`${forward}`, `${backward}`, `${vel[2]}`],
        explanation: `A centered difference approximates $a(3) \\approx \\dfrac{v(4)-v(2)}{4-2}=\\dfrac{${vel[3]}-${vel[1]}}{2}=${centered}$. Using only the forward pair $(v(4)-v(3))$ or backward pair $(v(3)-v(2))$ instead of the centered pair, or reporting $v(3)$ itself, are the common table-reading mistakes.`,
        figure: table,
      };
    },
  },
  {
    id: "n4-rect-table-c",
    unit: U4,
    topic: "rectilinear-motion",
    difficulty: "hard",
    manifestation: "rectilinear-motion:table-motion",
    calculator: true,
    mistakes: ["confuses-speed-with-velocity-in-table"],
    build: (r: RNG) => {
      const t = [0, 2, 4, 6];
      const vel = [ri(r, 3, 5), -ri(r, 1, 3), -ri(r, 4, 6), ri(r, 2, 4)];
      const table = {
        kind: "table" as const,
        headers: ["t", "v(t)"],
        rows: t.map((ti, i) => [`${ti}`, `${vel[i]}`]),
        caption: "Velocity of a particle at selected times",
      };
      const speeds = vel.map((v) => Math.abs(v));
      const maxSpeedIdx = speeds.indexOf(Math.max(...speeds));
      return {
        prompt: `The table gives the velocity $v(t)$ of a particle moving along a line at several times $t$. At which of these times is the particle's speed greatest?`,
        correct: `t = ${t[maxSpeedIdx]}`,
        distractors: t
          .map((ti, i) => `t = ${ti}`)
          .filter((_, i) => i !== maxSpeedIdx)
          .slice(0, 3),
        explanation: `Speed is $|v(t)|$, not $v(t)$ itself. Comparing $|${vel[0]}|, |${vel[1]}|, |${vel[2]}|, |${vel[3]}|$, the greatest is $|${vel[maxSpeedIdx]}|=${speeds[maxSpeedIdx]}$ at $t=${t[maxSpeedIdx]}$. A student who instead picks the largest signed velocity value, ignoring the sign, would choose the wrong time.`,
        figure: table,
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: rates-of-change-in-context:units                            */
  /* ================================================================== */
  {
    id: "n4-rates-units-a",
    unit: U4,
    topic: "rates-of-change-in-context",
    difficulty: "medium",
    manifestation: "rates-of-change-in-context:units",
    mistakes: ["wrong-units-for-derivative"],
    build: (r: RNG) => {
      const item = pick(r, [
        { quantity: "the water level of a reservoir", qUnit: "feet", tUnit: "days" },
        { quantity: "the number of bacteria in a culture", qUnit: "cells", tUnit: "hours" },
        { quantity: "the temperature of a cooling object", qUnit: "degrees Celsius", tUnit: "minutes" },
      ]);
      return {
        prompt: `Let $Q(t)$ represent ${item.quantity}, measured in ${item.qUnit}, where $t$ is measured in ${item.tUnit}. What are the correct units for $Q'(t)$?`,
        correct: `\\text{${item.qUnit} per ${item.tUnit}}`,
        distractors: [
          `\\text{${item.tUnit} per ${item.qUnit}}`,
          `\\text{${item.qUnit}}`,
          `\\text{${item.qUnit} per ${item.tUnit} squared}`,
        ],
        explanation: `The derivative $Q'(t)$ represents a rate of change of $Q$ with respect to $t$, so its units are always (units of $Q$) per (units of $t$), namely ${item.qUnit} per ${item.tUnit}. Inverting the ratio, dropping the rate entirely, or squaring the time unit (which belongs to a second derivative) are the typical mistakes.`,
      };
    },
  },
  {
    id: "n4-rates-units-b",
    unit: U4,
    topic: "rates-of-change-in-context",
    difficulty: "medium",
    manifestation: "rates-of-change-in-context:units",
    mistakes: ["confuses-derivative-with-second-derivative-units"],
    build: (r: RNG) => {
      const gal = ri(r, 20, 60);
      const min = ri(r, 2, 6);
      return {
        prompt: `Water drains from a tank so that its volume $V(t)$, in gallons, changes at a rate of $V'(t)$ gallons per minute. A student is asked for the units of $V''(t)$. What is the correct answer?`,
        correct: `\\text{gallons per minute squared}`,
        distractors: [
          `\\text{gallons per minute}`,
          `\\text{minutes per gallon squared}`,
          `\\text{gallons squared per minute}`,
        ],
        explanation: `$V''(t)$ is the rate of change of $V'(t)$ with respect to $t$, so its units are (units of $V'$) per (units of $t$) = gallons per minute, per minute = gallons per minute squared. Keeping the units of the first derivative, or squaring the wrong quantity, are the usual errors. (Example values: draining roughly $${gal}$ gallons over $${min}$ minutes illustrates the first-derivative units, but the question asks about the second derivative.)`,
      };
    },
  },
  {
    id: "n4-rates-units-c",
    unit: U4,
    topic: "rates-of-change-in-context",
    difficulty: "medium",
    manifestation: "rates-of-change-in-context:units",
    mistakes: ["wrong-units-for-derivative"],
    build: (r: RNG) => {
      return {
        prompt: `The cost $C(x)$, in dollars, of producing $x$ units of a product is a differentiable function of $x$. In the context of this problem, what does $C'(50)$ represent, including correct units?`,
        correct: `\\text{The approximate cost, in dollars per unit, of producing one additional unit near } x=50`,
        distractors: [
          `\\text{The total cost, in dollars, of producing 50 units}`,
          `\\text{The number of units, per dollar, produced near } x=50`,
          `\\text{The approximate cost, in dollars, of producing 50 units}`,
        ],
        explanation: `$C'(50)$ is a rate of change with units of dollars per unit; it approximates the marginal cost — the additional cost of producing one more unit near $x=50$ — not the total cost itself, and not a quantity measured in units per dollar.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 4: rates-of-change-in-context:compare-rates                    */
  /* ================================================================== */
  {
    id: "n4-rates-compare-a",
    unit: U4,
    topic: "rates-of-change-in-context",
    difficulty: "medium",
    manifestation: "rates-of-change-in-context:compare-rates",
    calculator: true,
    mistakes: ["compares-values-instead-of-rates"],
    build: (r: RNG) => {
      const t = [0, 1, 2, 3];
      const popA = [ri(r, 100, 120), ri(r, 130, 150), ri(r, 165, 185), ri(r, 220, 240)];
      const popB = [ri(r, 300, 320), ri(r, 320, 340), ri(r, 345, 365), ri(r, 375, 395)];
      const table = {
        kind: "table" as const,
        headers: ["t (years)", "Population A", "Population B"],
        rows: t.map((ti, i) => [`${ti}`, `${popA[i]}`, `${popB[i]}`]),
        caption: "Two population sizes over time",
      };
      const rateA = dec((popA[3] - popA[0]) / 3, 1);
      const rateB = dec((popB[3] - popB[0]) / 3, 1);
      const faster = rateA > rateB ? "A" : "B";
      return {
        prompt: `The table shows the sizes of two populations, A and B, over time $t$ in years. Based on the average rates of change over $[0,3]$, which population is growing faster?`,
        correct: `\\text{Population ${faster}}`,
        distractors: [
          `\\text{Population ${faster === "A" ? "B" : "A"}}`,
          `\\text{They are growing at the same rate}`,
          `\\text{Population ${faster === "A" ? "B" : "A"}, because it has more members at } t=3`,
        ],
        explanation: `Population A's average rate of change is $\\dfrac{${popA[3]}-${popA[0]}}{3}\\approx ${rateA}$ per year, while Population B's is $\\dfrac{${popB[3]}-${popB[0]}}{3}\\approx ${rateB}$ per year. Comparing rates (not raw sizes) shows Population ${faster} is growing faster, since a larger total size does not necessarily mean a faster rate of change.`,
        figure: table,
      };
    },
  },
  {
    id: "n4-rates-compare-b",
    unit: U4,
    topic: "rates-of-change-in-context",
    difficulty: "hard",
    manifestation: "rates-of-change-in-context:compare-rates",
    calculator: true,
    mistakes: ["picks-largest-raw-value-instead-of-slope"],
    build: (r: RNG) => {
      const t = [1, 2, 3, 4];
      const distCar = [ri(r, 10, 15), ri(r, 28, 33), ri(r, 44, 50), ri(r, 80, 90)];
      const distBike = [ri(r, 5, 8), ri(r, 15, 18), ri(r, 25, 28), ri(r, 35, 38)];
      const table = {
        kind: "table" as const,
        headers: ["t (hours)", "Car distance (miles)", "Bike distance (miles)"],
        rows: t.map((ti, i) => [`${ti}`, `${distCar[i]}`, `${distBike[i]}`]),
        caption: "Distance traveled by two vehicles over time",
      };
      const carRate = dec((distCar[3] - distCar[2]) / (t[3] - t[2]), 1);
      const bikeRate = dec((distBike[3] - distBike[2]) / (t[3] - t[2]), 1);
      const faster = carRate > bikeRate ? "car" : "bike";
      return {
        prompt: `The table shows total distance traveled by a car and a bike over time. Using the interval $[3,4]$, which vehicle has the greater instantaneous rate of change (speed) estimate at that time?`,
        correct: `\\text{The ${faster}}`,
        distractors: [
          `\\text{The ${faster === "car" ? "bike" : "car"}}`,
          `\\text{Both have the same rate}`,
          `\\text{The ${faster === "car" ? "bike" : "car"}, because it has traveled less total distance}`,
        ],
        explanation: `The average rate of change on $[3,4]$ approximates the instantaneous rate near $t=4$. The car's average rate is $\\dfrac{${distCar[3]}-${distCar[2]}}{1}=${carRate}$ mph, and the bike's is $\\dfrac{${distBike[3]}-${distBike[2]}}{1}=${bikeRate}$ mph, so the ${faster} has the greater rate — comparing total distance traveled instead of the slope over the interval is the error to avoid.`,
        figure: table,
      };
    },
  },
];
