/**
 * Unit 7 (differential equations) and Unit 8 (applications of integration)
 * template families. Every family is an original construction generated from
 * a seeded RNG; no College Board wording is reused.
 */

import {
  frac,
  pick,
  ri,
  term,
  type QuestionTemplate,
  type RNG,
} from "../question-templates";
import { fitWindow, sampleCurve } from "../figures";

const U7 = "unit-7-differential-equations";
const U8 = "unit-8-applications-of-integration";

const coefTerm = (c: number, body: string): string => {
  if (c === 1) return body;
  if (c === -1) return `-${body}`;
  return `${c}${body}`;
};

const gcd = (a: number, b: number): number => (b ? gcd(b, Math.abs(a % b)) : Math.abs(a));

/** k*pi/d as a simplified LaTeX fraction (or bare k*pi if d==1). */
function piFrac(k: number, d: number): string {
  const g = gcd(k, d) || 1;
  const n = k / g;
  const den = d / g;
  const piPart = (m: number) => (m === 1 ? "\\pi" : m === -1 ? "-\\pi" : `${m}\\pi`);
  if (den === 1) return piPart(n);
  const absNumStr = Math.abs(n) === 1 ? "\\pi" : `${Math.abs(n)}\\pi`;
  return n < 0 ? `-\\frac{${absNumStr}}{${den}}` : `\\frac{${absNumStr}}{${den}}`;
}

export const UNIT_07_08_TEMPLATES: QuestionTemplate[] = [
  /* ================================================================== */
  /* Unit 7: slope-fields:impossible-curve                               */
  /* ================================================================== */
  {
    id: "n7-slope-impossible-a",
    unit: U7,
    topic: "slope-fields",
    difficulty: "medium",
    manifestation: "slope-fields:impossible-curve",
    mistakes: ["missing-term-in-slope"],
    build: (r: RNG) => {
      const a = ri(r, 1, 3);
      const b = ri(r, 1, 3);
      const k = ri(r, 1, 2);
      // horizontal tangent line: a x + b y = 0  =>  points (b*k, -a*k) lie on it
      const p1: [number, number] = [b * k, -a * k];
      const p2: [number, number] = [-b * k, a * k];
      const p3: [number, number] = [2 * b * k, -2 * a * k];
      const off: [number, number] = [b * k, -a * k + 1];
      return {
        prompt: `The slope field shown is for the differential equation $\\dfrac{dy}{dx}=${coefTerm(a, "x")}${term(b, "y")}$. At which of the following points is it impossible for a solution curve to have a horizontal tangent line?`,
        correct: `(${off[0]},${off[1]})`,
        distractors: [`(${p1[0]},${p1[1]})`, `(${p2[0]},${p2[1]})`, `(${p3[0]},${p3[1]})`],
        explanation: `A horizontal tangent requires $${coefTerm(a, "x")}${term(b, "y")}=0$. Points $(${p1[0]},${p1[1]})$, $(${p2[0]},${p2[1]})$, and $(${p3[0]},${p3[1]})$ satisfy this, but $(${off[0]},${off[1]})$ gives slope $${a * off[0] + b * off[1]}\\ne 0$, so a horizontal tangent is impossible there.`,
        figure: { kind: "slope-field", a, b, extent: 6 },
      };
    },
  },
  {
    id: "n7-slope-impossible-b",
    unit: U7,
    topic: "slope-fields",
    difficulty: "medium",
    manifestation: "slope-fields:impossible-curve",
    mistakes: ["confuses-defined-slope-with-vertical-tangent"],
    build: (r: RNG) => {
      const a = ri(r, 1, 3);
      const b = ri(r, 1, 3);
      return {
        prompt: `A slope field is generated by $\\dfrac{dy}{dx}=${coefTerm(a, "x")}${term(b, "y")}$. Which behavior is impossible for any solution curve of this equation?`,
        correct: `\\text{The curve has a vertical tangent line at some point.}`,
        distractors: [
          `\\text{The curve has a horizontal tangent line at some point.}`,
          `\\text{The curve passes through the origin.}`,
          `\\text{The curve is increasing on some interval.}`,
        ],
        explanation: `Since $${coefTerm(a, "x")}${term(b, "y")}$ is defined and finite for every $(x,y)$, the slope of a solution curve is always a finite real number, so a vertical tangent (undefined slope) can never occur.`,
        figure: { kind: "slope-field", a, b, extent: 6 },
      };
    },
  },
  {
    id: "n7-slope-impossible-c",
    unit: U7,
    topic: "slope-fields",
    difficulty: "hard",
    manifestation: "slope-fields:impossible-curve",
    mistakes: ["magnitude-vs-sign-confusion"],
    build: (r: RNG) => {
      const a = ri(r, 1, 3);
      const b = ri(r, 1, 3);
      const p: [number, number] = [ri(r, 1, 3), ri(r, 1, 3)];
      const q: [number, number] = [ri(r, -3, -1), ri(r, 1, 3)];
      const mp = a * p[0] + b * p[1];
      const mq = a * q[0] + b * q[1];
      const steeper = Math.abs(mp) > Math.abs(mq) ? p : q;
      return {
        prompt: `For $\\dfrac{dy}{dx}=${coefTerm(a, "x")}${term(b, "y")}$, at which point does a solution curve have the steeper (larger-magnitude) slope: $(${p[0]},${p[1]})$ or $(${q[0]},${q[1]})$?`,
        correct: `(${steeper[0]},${steeper[1]})`,
        distractors: [
          `(${(steeper === p ? q : p)[0]},${(steeper === p ? q : p)[1]})`,
          `\\text{The slopes are equal at both points.}`,
          `\\text{It cannot be determined from the equation.}`,
        ],
        explanation: `The slope at $(${p[0]},${p[1]})$ is $${mp}$ and at $(${q[0]},${q[1]})$ is $${mq}$. Since $|${mp}| ${Math.abs(mp) > Math.abs(mq) ? ">" : "<"} |${mq}|$, the curve is steeper at $(${steeper[0]},${steeper[1]})$.`,
        figure: { kind: "slope-field", a, b, extent: 6 },
      };
    },
  },

  /* ================================================================== */
  /* Unit 7: separable-differential-equations:separability                */
  /* ================================================================== */
  {
    id: "n7-separability-a",
    unit: U7,
    topic: "separable-differential-equations",
    difficulty: "easy",
    manifestation: "separable-differential-equations:separability",
    mistakes: ["procedure-selection"],
    build: (r: RNG) => {
      const k = ri(r, 2, 5);
      return {
        prompt: `Which of the following differential equations is separable?`,
        correct: `\\dfrac{dy}{dx}=${k}xy`,
        distractors: [`\\dfrac{dy}{dx}=x+y`, `\\dfrac{dy}{dx}=${k}x+y^{2}`, `\\dfrac{dy}{dx}=e^{x+y}+x`],
        explanation: `$\\dfrac{dy}{dx}=${k}xy$ can be written as a function of $x$ times a function of $y$, so it separates as $\\dfrac{dy}{y}=${k}x\\,dx$. The other equations combine $x$ and $y$ additively (or with an extra term) and cannot be factored that way.`,
      };
    },
  },
  {
    id: "n7-separability-b",
    unit: U7,
    topic: "separable-differential-equations",
    difficulty: "medium",
    manifestation: "separable-differential-equations:separability",
    mistakes: ["term-order-error"],
    build: (r: RNG) => {
      const n = ri(r, 2, 3);
      return {
        prompt: `A student wants to separate the variables in $\\dfrac{dy}{dx}=xy^{${n}}$. Which equation correctly separates the variables?`,
        correct: `\\dfrac{dy}{y^{${n}}}=x\\,dx`,
        distractors: [`\\dfrac{dx}{y^{${n}}}=y\\,dy`, `y^{${n}}\\,dy=x\\,dx`, `\\dfrac{dy}{x}=y^{${n}}\\,dx`],
        explanation: `Divide both sides by $y^{${n}}$ and multiply by $dx$: $\\dfrac{dy}{y^{${n}}}=x\\,dx$ places all $y$-terms with $dy$ and all $x$-terms with $dx$.`,
      };
    },
  },
  {
    id: "n7-separability-c",
    unit: U7,
    topic: "separable-differential-equations",
    difficulty: "medium",
    manifestation: "separable-differential-equations:separability",
    mistakes: ["exponent-law-error"],
    build: (r: RNG) => {
      const c = ri(r, 2, 4);
      return {
        prompt: `To separate $\\dfrac{dy}{dx}=${c}e^{x-y}$, a student first rewrites the right side as a product of a function of $x$ and a function of $y$. Which rewriting is correct?`,
        correct: `${c}e^{x}\\cdot e^{-y}`,
        distractors: [`${c}e^{x}\\cdot e^{y}`, `${c}(e^{x}-e^{y})`, `${c}e^{x-y}`],
        explanation: `By the exponent law $e^{x-y}=e^{x}e^{-y}$, so $${c}e^{x-y}=${c}e^{x}\\cdot e^{-y}$, which separates as $e^{y}\\,dy=${c}e^{x}\\,dx$.`,
      };
    },
  },

  /* ---- Newton's law of cooling (reuses separability manifestation) ---- */
  {
    id: "n7-cooling-a",
    unit: U7,
    topic: "separable-differential-equations",
    difficulty: "medium",
    manifestation: "separable-differential-equations:separability",
    mistakes: ["sign-slip", "forgot-shift"],
    build: (r: RNG) => {
      const A = ri(r, 60, 75);
      const k = ri(r, 2, 5);
      return {
        prompt: `Newton's law of cooling states that an object's temperature $T$ satisfies $\\dfrac{dT}{dt}=-${k}(T-${A})$, where ${A} is the ambient temperature. Which equation correctly separates the variables?`,
        correct: `\\dfrac{dT}{T-${A}}=-${k}\\,dt`,
        distractors: [
          `\\dfrac{dT}{T}=-${k}\\,dt`,
          `\\dfrac{dT}{${A}-T}=-${k}\\,dt`,
          `\\dfrac{dT}{T-${A}}=${k}\\,dt`,
        ],
        explanation: `Dividing both sides by $(T-${A})$ gives $\\dfrac{dT}{T-${A}}=-${k}\\,dt$. Dropping the constant $${A}$ or flipping either sign gives a different (incorrect) separation.`,
      };
    },
  },
  {
    id: "n7-cooling-b",
    unit: U7,
    topic: "separable-differential-equations",
    difficulty: "hard",
    manifestation: "separable-differential-equations:separability",
    mistakes: ["arithmetic-inversion", "forgot-logarithm", "sign-slip"],
    build: (r: RNG) => {
      const A = ri(r, 60, 70);
      const t1 = ri(r, 2, 6);
      return {
        prompt: `A cup of coffee cools in a room at ${A}\u00b0F. Its temperature satisfies $\\dfrac{dT}{dt}=k(T-${A})$. Data show that the coffee's excess temperature $T-${A}$ is cut in half after $${t1}$ minutes. What is $k$?`,
        correct: `-\\dfrac{\\ln 2}{${t1}}`,
        distractors: [`\\dfrac{\\ln 2}{${t1}}`, `-${t1}\\ln 2`, `-\\dfrac{2}{${t1}}`],
        explanation: `Since $T-${A}=(T_0-${A})e^{kt}$, halving the excess temperature means $e^{k\\cdot ${t1}}=\\tfrac12$, so $k=\\dfrac{\\ln(1/2)}{${t1}}=-\\dfrac{\\ln 2}{${t1}}$.`,
      };
    },
  },
  {
    id: "n7-cooling-c",
    unit: U7,
    topic: "separable-differential-equations",
    difficulty: "medium",
    manifestation: "separable-differential-equations:separability",
    mistakes: ["sign-confusion"],
    build: (r: RNG) => {
      const A = ri(r, 65, 75);
      return {
        prompt: `An object obeys $\\dfrac{dT}{dt}=k(T-${A})$ and is warmer than the surrounding air, which stays at ${A}\u00b0. For the object's temperature to decrease toward ${A}\u00b0 as $t\\to\\infty$, which must be true?`,
        correct: `k<0`,
        distractors: [`k>0`, `k=0`, `k=${A}`],
        explanation: `The solution is $T=${A}+(T_0-${A})e^{kt}$. For $T\\to ${A}$ as $t\\to\\infty$ we need $e^{kt}\\to 0$, which requires $k<0$.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 7: eulers-method:step-size                                      */
  /* ================================================================== */
  {
    id: "n7-euler-step-a",
    unit: U7,
    topic: "eulers-method",
    difficulty: "easy",
    manifestation: "eulers-method:step-size",
    track: "BC",
    mistakes: ["step-count-confusion"],
    build: (r: RNG) => {
      const x0 = ri(r, 0, 2);
      const width = ri(r, 1, 2);
      const h = pick(r, [0.25, 0.5]);
      const steps = Math.round(width / h);
      return {
        prompt: `Starting at $x=${x0}$, a student uses Euler's method with step size $h=${h}$ to approximate $y$ at $x=${x0 + width}$. How many steps are required?`,
        correct: `${steps}`,
        distractors: [`${Math.round(width / h) + 1}`, `${width}`, `${Math.round(1 / h)}`],
        explanation: `The number of steps is the total change in $x$ divided by the step size: $\\dfrac{${width}}{${h}}=${steps}$.`,
      };
    },
  },
  {
    id: "n7-euler-step-b",
    unit: U7,
    topic: "eulers-method",
    difficulty: "hard",
    manifestation: "eulers-method:step-size",
    track: "BC",
    mistakes: ["used-wrong-step-in-second-application"],
    build: (r: RNG) => {
      const x0 = 0;
      const y0 = ri(r, 1, 3);
      const k = ri(r, 1, 2);
      const h = 0.5;
      // dy/dx = k (constant slope), two steps of size 0.5
      const y1 = y0 + h * k * (x0 + 1); // f(x,y) = k*x, so first step uses x0
      const y2 = y1 + h * k * (x0 + h);
      return {
        prompt: `Given $\\dfrac{dy}{dx}=${k}x$ and $y(${x0})=${y0}$, use two Euler's-method steps of size $h=0.5$ to approximate $y(1)$.`,
        correct: `${y2}`,
        distractors: [`${y0 + 1 * k * x0}`, `${y1}`, `${y0 + h * k * (x0 + 1)}`],
        explanation: `Step 1: $y_1=${y0}+0.5(${k}\\cdot ${x0})=${y1}$ at $x=0.5$. Step 2: $y_2=${y1}+0.5(${k}\\cdot 0.5)=${y2}$, which approximates $y(1)$.`,
      };
    },
  },
  {
    id: "n7-euler-step-c",
    unit: U7,
    topic: "eulers-method",
    difficulty: "medium",
    manifestation: "eulers-method:step-size",
    track: "BC",
    mistakes: ["reverses-accuracy-relationship"],
    build: (r: RNG) => {
      const h1 = pick(r, [0.1, 0.25]);
      const h2 = pick(r, [0.5, 1]);
      return {
        prompt: `Euler's method is used to approximate a solution on the same interval twice: once with step size $h=${h1}$ and once with step size $h=${h2}$. Which approximation is generally more accurate?`,
        correct: `\\text{The approximation using } h=${h1}`,
        distractors: [
          `\\text{The approximation using } h=${h2}`,
          `\\text{Both are equally accurate.}`,
          `\\text{Accuracy does not depend on the step size.}`,
        ],
        explanation: `Euler's method error generally shrinks as the step size shrinks, so the smaller step size $h=${h1}$ typically gives the more accurate approximation.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 7: eulers-method:over-under                                     */
  /* ================================================================== */
  {
    id: "n7-euler-overunder-a",
    unit: U7,
    topic: "eulers-method",
    difficulty: "medium",
    manifestation: "eulers-method:over-under",
    track: "BC",
    mistakes: ["reverses-concavity-conclusion"],
    build: (r: RNG) => {
      const concaveUp = r() < 0.5;
      return {
        prompt: `A solution curve to a differential equation is known to satisfy $y''(x)${concaveUp ? ">" : "<"}0$ on an interval. As $x$ increases across this interval, Euler's method with a positive step size will produce approximations that:`,
        correct: concaveUp ? `\\text{underestimate the true values of } y` : `\\text{overestimate the true values of } y`,
        distractors: [
          concaveUp ? `\\text{overestimate the true values of } y` : `\\text{underestimate the true values of } y`,
          `\\text{match the true values of } y \\text{ exactly}`,
          `\\text{be sometimes greater and sometimes less, with no pattern}`,
        ],
        explanation: `Euler's method follows the tangent line at each step. If $y''${concaveUp ? ">" : "<"}0$ the curve is concave ${concaveUp ? "up" : "down"}, so the true curve lies ${concaveUp ? "above" : "below"} its tangent lines, meaning Euler's method ${concaveUp ? "underestimates" : "overestimates"} $y$.`,
      };
    },
  },
  {
    id: "n7-euler-overunder-b",
    unit: U7,
    topic: "eulers-method",
    difficulty: "hard",
    manifestation: "eulers-method:over-under",
    track: "BC",
    mistakes: ["computes-f-prime-instead-of-f-double-prime"],
    build: (r: RNG) => {
      const a = ri(r, 1, 3);
      const increasing = r() < 0.5;
      const fSign = increasing ? a : -a;
      return {
        prompt: `Suppose $\\dfrac{dy}{dx}=f(x)$ where $f'(x)${increasing ? ">" : "<"}0$ for all $x$ in an interval (so $f$ is ${increasing ? "increasing" : "decreasing"} there). What must be true about Euler's-method approximations on that interval?`,
        correct: increasing ? `\\text{They underestimate the true } y\\text{-values.}` : `\\text{They overestimate the true } y\\text{-values.}`,
        distractors: [
          increasing ? `\\text{They overestimate the true } y\\text{-values.}` : `\\text{They underestimate the true } y\\text{-values.}`,
          `\\text{They are exactly correct.}`,
          `\\text{No conclusion can be drawn.}`,
        ],
        explanation: `Since $y'=f(x)$, we get $y''=f'(x)$, which is ${increasing ? "positive" : "negative"}, so $y$ is concave ${increasing ? "up" : "down"}. This means the tangent-line (Euler) approximations lie ${increasing ? "below" : "above"} the true curve, i.e. they ${increasing ? "underestimate" : "overestimate"} it. (Slope sign of $f$, $${fSign > 0 ? "+" : "-"}$, is a distractor — concavity is decided by $f'$, not $f$.)`,
      };
    },
  },
  {
    id: "n7-euler-overunder-c",
    unit: U7,
    topic: "eulers-method",
    difficulty: "hard",
    manifestation: "eulers-method:over-under",
    track: "BC",
    mistakes: ["reverses-concavity-conclusion"],
    build: (r: RNG) => {
      const underestimates = r() < 0.5;
      return {
        prompt: `On $[a,b]$, Euler's method is known to ${underestimates ? "underestimate" : "overestimate"} the true solution $y(x)$ at every step. What must be true about the concavity of $y$ on $[a,b]$?`,
        correct: underestimates ? `y''(x)>0 \\text{ on } [a,b]` : `y''(x)<0 \\text{ on } [a,b]`,
        distractors: [
          underestimates ? `y''(x)<0 \\text{ on } [a,b]` : `y''(x)>0 \\text{ on } [a,b]`,
          `y'(x)>0 \\text{ on } [a,b]`,
          `y(x)>0 \\text{ on } [a,b]`,
        ],
        explanation: `Tangent-line approximations fall below a curve that is concave up and above one that is concave down. Since Euler's method ${underestimates ? "underestimates" : "overestimates"} $y$, the curve must be concave ${underestimates ? "up" : "down"}, i.e. $y''${underestimates ? ">" : "<"}0$.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 7: eulers-method:formula-error                                  */
  /* ================================================================== */
  {
    id: "n7-euler-formula-a",
    unit: U7,
    topic: "eulers-method",
    difficulty: "medium",
    manifestation: "eulers-method:formula-error",
    track: "BC",
    mistakes: ["forgot-to-multiply-by-h"],
    build: (r: RNG) => {
      const x0 = ri(r, 0, 2);
      const y0 = ri(r, 1, 4);
      const h = pick(r, [0.5, 0.25]);
      const val = x0 + y0;
      return {
        prompt: `For $\\dfrac{dy}{dx}=x+y$, $y(${x0})=${y0}$, and step size $h=${h}$, which expression correctly gives the next Euler approximation $y_1$?`,
        correct: `${y0}+${h}(${x0}+${y0})`,
        distractors: [`${y0}+(${x0}+${y0})`, `${y0}+${h}(${x0 + h}+${y0})`, `${x0}+${h}(${x0}+${y0})`],
        explanation: `The Euler update is $y_1=y_0+h\\,f(x_0,y_0)=${y0}+${h}(${val})$; forgetting to multiply by $h$, evaluating $f$ at $x_0+h$ instead of $x_0$, or updating $x_0$ instead of $y_0$ are all common errors.`,
      };
    },
  },
  {
    id: "n7-euler-formula-b",
    unit: U7,
    topic: "eulers-method",
    difficulty: "medium",
    manifestation: "eulers-method:formula-error",
    track: "BC",
    mistakes: ["evaluates-f-at-wrong-point"],
    build: (r: RNG) => {
      const x0 = ri(r, 1, 3);
      const y0 = ri(r, 1, 3);
      const h = 0.5;
      const x1 = x0 + h;
      const y1 = y0 + h * (x0 * y0);
      return {
        prompt: `A student computes one Euler step for $\\dfrac{dy}{dx}=xy$, $y(${x0})=${y0}$, $h=${h}$, and writes $y_1=${y0}+${h}(${x1})(${y0})$. What error did the student make?`,
        correct: `\\text{Evaluated } f \\text{ at } x_1 \\text{ instead of } x_0`,
        distractors: [
          `\\text{Forgot to multiply by } h`,
          `\\text{Used } y_1 \\text{ instead of } y_0 \\text{ in } f`,
          `\\text{No error; the computation is correct}`,
        ],
        explanation: `The correct update uses the slope at the starting point: $y_1=y_0+h\\,f(x_0,y_0)=${y0}+${h}(${x0})(${y0})=${y1}$. Using $x_1=${x1}$ inside $f$ instead of $x_0$ is the error.`,
      };
    },
  },
  {
    id: "n7-euler-formula-c",
    unit: U7,
    topic: "eulers-method",
    difficulty: "hard",
    manifestation: "eulers-method:formula-error",
    track: "BC",
    mistakes: ["added-h-to-slope-instead-of-product"],
    build: (r: RNG) => {
      const x0 = ri(r, 0, 2);
      const y0 = ri(r, 2, 5);
      const h = 0.5;
      const slope = x0 + 2 * y0;
      const correct = y0 + h * slope;
      return {
        prompt: `For $\\dfrac{dy}{dx}=x+2y$, $y(${x0})=${y0}$, $h=${h}$, which of these is the correctly computed value of $y_1$?`,
        correct: `${correct}`,
        distractors: [`${y0 + h + slope}`, `${y0 * h + slope}`, `${h * slope}`],
        explanation: `$y_1=y_0+h\\,f(x_0,y_0)=${y0}+${h}(${slope})=${correct}$. Adding $h$ to the slope instead of multiplying, multiplying $y_0$ by $h$ instead of adding, or omitting $y_0$ entirely are common formula errors.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: average-value:graph                                          */
  /* ================================================================== */
  {
    id: "n8-avgval-graph-a",
    unit: U8,
    topic: "average-value",
    difficulty: "medium",
    manifestation: "average-value:graph",
    mistakes: ["forgot-divide-by-width", "wrong-width", "averaged-endpoints"],
    calculator: false,
    build: (r: RNG) => {
      const x0 = 0;
      const x1 = ri(r, 2, 4);
      const x2 = x1 + ri(r, 2, 4);
      const y0 = ri(r, 1, 6);
      const y1 = ri(r, 1, 6);
      const y2 = ri(r, 1, 6);
      const sum2 = (y0 + y1) * (x1 - x0) + (y1 + y2) * (x2 - x1);
      const width = x2 - x0;
      const pts: Array<[number, number]> = [
        [x0, y0],
        [x1, y1],
        [x2, y2],
      ];
      return {
        prompt: `The graph shows $f$ on $[${x0},${x2}]$ as a sequence of line segments through $(${x0},${y0})$, $(${x1},${y1})$, and $(${x2},${y2})$. What is the average value of $f$ on $[${x0},${x2}]$?`,
        correct: frac(sum2, 2 * width),
        distractors: [frac(sum2, width), frac(sum2, 2 * (x1 - x0)), frac(y0 + y1 + y2, 3)],
        explanation: `The average value is $\\dfrac{1}{${width}}\\int_{${x0}}^{${x2}}f(x)\\,dx$. Using the trapezoids, the integral is $${frac(sum2, 2)}$, so the average value is $${frac(sum2, 2 * width)}$.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: false }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },
  {
    id: "n8-avgval-graph-b",
    unit: U8,
    topic: "average-value",
    difficulty: "medium",
    manifestation: "average-value:graph",
    mistakes: ["forgot-divide-by-width", "wrong-width"],
    build: (r: RNG) => {
      const x0 = 0;
      const x1 = ri(r, 2, 3);
      const x2 = x1 + ri(r, 2, 3);
      const x3 = x2 + ri(r, 2, 3);
      const y0 = ri(r, 2, 5);
      const y1 = ri(r, 4, 8);
      const y2 = ri(r, 1, 4);
      const y3 = ri(r, 2, 6);
      const area2 = (y0 + y1) * (x1 - x0) + (y1 + y2) * (x2 - x1) + (y2 + y3) * (x3 - x2);
      const width = x3 - x0;
      const avgDec = Math.round((area2 / (2 * width)) * 100) / 100;
      const pts: Array<[number, number]> = [
        [x0, y0],
        [x1, y1],
        [x2, y2],
        [x3, y3],
      ];
      return {
        prompt: `The graph shows the temperature $T$ (in \u00b0C) of a room over $[${x0},${x3}]$ hours as connected line segments. To the nearest hundredth, what is the average temperature over $[${x0},${x3}]$?`,
        correct: `${avgDec}`,
        distractors: [
          `${Math.round((area2 / 2) * 100) / 100}`,
          `${Math.round((area2 / (2 * (x1 - x0))) * 100) / 100}`,
          `${Math.round(((y0 + y1 + y2 + y3) / 4) * 100) / 100}`,
        ],
        explanation: `Average value $=\\dfrac{1}{${width}}\\int_{${x0}}^{${x3}}T\\,dt$. Summing trapezoid areas gives $\\int T\\,dt=${frac(area2, 2)}$, so the average is $${frac(area2, 2 * width)}\\approx ${avgDec}$.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: false }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },
  {
    id: "n8-avgval-graph-c",
    unit: U8,
    topic: "average-value",
    difficulty: "hard",
    manifestation: "average-value:graph",
    mistakes: ["confused-avg-with-radius", "confused-avg-with-area"],
    build: (r: RNG) => {
      const R = ri(r, 2, 6);
      const pts = sampleCurve((x) => Math.sqrt(Math.max(0, R * R - x * x)), -R, R, 60);
      return {
        prompt: `The graph of $f(x)=\\sqrt{${R}^{2}-x^{2}}$ is a semicircle of radius ${R} on $[-${R},${R}]$. What is the average value of $f$ on this interval?`,
        correct: piFrac(R, 4),
        distractors: [piFrac(R, 2), piFrac(R, 8), piFrac(R * R, 2)],
        explanation: `The average value is $\\dfrac{1}{2${R}}\\int_{-${R}}^{${R}}f(x)\\,dx=\\dfrac{1}{2${R}}\\cdot\\dfrac{\\pi ${R}^{2}}{2}=${piFrac(R, 4)}$. Dividing by the radius instead of the diameter, or reporting the area instead of the average, gives the other choices.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: true }],
          window: { xMin: -R - 1, xMax: R + 1, yMin: -1, yMax: R + 1 },
        },
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: area-between-curves:switching-top                           */
  /* ================================================================== */
  {
    id: "n8-switch-top-a",
    unit: U8,
    topic: "area-between-curves",
    difficulty: "hard",
    manifestation: "area-between-curves:switching-top",
    mistakes: ["ignored-crossing", "counted-one-piece-only", "antiderivative-sign-error"],
    build: (r: RNG) => {
      const c = ri(r, 2, 5) * 2;
      const total = (c * c) / 2;
      const half = (c * c) / 4;
      const pts1 = sampleCurve((x) => x, 0, c, 10);
      const pts2 = sampleCurve((x) => c - x, 0, c, 10);
      return {
        prompt: `Let $f(x)=x$ and $g(x)=${c}-x$. What is the total area of the region between the two curves on $[0,${c}]$?`,
        correct: `${total}`,
        distractors: [`0`, `${half}`, `${3 * half * 2}`],
        explanation: `The curves cross at $x=${c / 2}$, with $g>f$ on $[0,${c / 2}]$ and $f>g$ on $[${c / 2},${c}]$. Splitting the integral gives $${half}+${half}=${total}$. Integrating $g-f$ over the whole interval without switching gives the wrong value of $0$ because the pieces cancel.`,
        figure: {
          kind: "graph",
          curves: [
            { points: pts1, smooth: false, tone: 0 },
            { points: pts2, smooth: false, tone: 1 },
          ],
          window: fitWindow([...pts1, ...pts2], 1),
        },
      };
    },
  },
  {
    id: "n8-switch-top-b",
    unit: U8,
    topic: "area-between-curves",
    difficulty: "hard",
    manifestation: "area-between-curves:switching-top",
    mistakes: ["no-split-integral"],
    build: (r: RNG) => {
      const c = ri(r, 2, 5) * 2;
      const m = c / 2;
      const pts1 = sampleCurve((x) => x, 0, c, 10);
      const pts2 = sampleCurve((x) => c - x, 0, c, 10);
      return {
        prompt: `Two lines $f(x)=x$ and $g(x)=${c}-x$ cross at $x=${m}$ on $[0,${c}]$. Which expression correctly sets up the total area between them?`,
        correct: `\\int_{0}^{${m}}(${c}-2x)\\,dx+\\int_{${m}}^{${c}}(2x-${c})\\,dx`,
        distractors: [
          `\\int_{0}^{${c}}(${c}-2x)\\,dx`,
          `\\int_{0}^{${m}}(2x-${c})\\,dx+\\int_{${m}}^{${c}}(${c}-2x)\\,dx`,
          `\\int_{0}^{${c}}(2x-${c})\\,dx`,
        ],
        explanation: `Since $g>f$ on $[0,${m}]$ the integrand there is $g-f=${c}-2x$, and since $f>g$ on $[${m},${c}]$ the integrand is $f-g=2x-${c}$. Using a single integral over the whole interval, or swapping which piece uses which integrand, are common setup errors.`,
        figure: {
          kind: "graph",
          curves: [
            { points: pts1, smooth: false, tone: 0 },
            { points: pts2, smooth: false, tone: 1 },
          ],
          window: fitWindow([...pts1, ...pts2], 1),
        },
      };
    },
  },
  {
    id: "n8-switch-top-c",
    unit: U8,
    topic: "area-between-curves",
    difficulty: "hard",
    manifestation: "area-between-curves:switching-top",
    mistakes: ["ignored-crossing"],
    build: (r: RNG) => {
      const c = ri(r, 2, 5) * 2;
      const total = (c * c) / 2;
      const half = (c * c) / 4;
      const pts1 = sampleCurve((x) => x, 0, c, 10);
      const pts2 = sampleCurve((x) => c - x, 0, c, 10);
      return {
        prompt: `Two companies' hourly profit rates (in thousands of dollars per hour) over a ${c}-hour period are $P_1(t)=t$ and $P_2(t)=${c}-t$. The company with the higher rate switches partway through. What is the total accumulated difference $|P_1-P_2|$ over $[0,${c}]$?`,
        correct: `${total}`,
        distractors: [`${half}`, `0`, `${c}`],
        explanation: `The rates are equal at $t=${c / 2}$. Splitting into $[0,${c / 2}]$ and $[${c / 2},${c}]$ and integrating $|P_1-P_2|$ on each piece gives $${half}+${half}=${total}$; using only one piece or failing to switch the integrand gives the other choices.`,
        figure: {
          kind: "graph",
          curves: [
            { points: pts1, smooth: false, tone: 0 },
            { points: pts2, smooth: false, tone: 1 },
          ],
          window: fitWindow([...pts1, ...pts2], 1),
        },
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: area-between-curves:signed-vs-geometric                      */
  /* ================================================================== */
  {
    id: "n8-signed-geo-a",
    unit: U8,
    topic: "area-between-curves",
    difficulty: "medium",
    manifestation: "area-between-curves:signed-vs-geometric",
    mistakes: ["signed-vs-absolute"],
    build: (r: RNG) => {
      const c = ri(r, 2, 6);
      const k = ri(r, 1, 3);
      // f(x) - g(x) = -k on [0,c] (g above f by k everywhere): signed integral negative
      const signed = -k * c;
      return {
        prompt: `On $[0,${c}]$, $g(x)-f(x)=${k}$ for every $x$ (so $g$ lies above $f$ the whole time). What is $\\displaystyle\\int_{0}^{${c}}\\bigl(f(x)-g(x)\\bigr)\\,dx$, and what is the geometric area between the curves?`,
        correct: `\\text{Signed integral}=${signed}\\text{, geometric area}=${k * c}`,
        distractors: [
          `\\text{Signed integral}=${k * c}\\text{, geometric area}=${k * c}`,
          `\\text{Signed integral}=${signed}\\text{, geometric area}=${signed}`,
          `\\text{Signed integral}=0\\text{, geometric area}=${k * c}`,
        ],
        explanation: `Since $f-g=-${k}$ everywhere, $\\int_{0}^{${c}}(f-g)\\,dx=-${k}(${c})=${signed}$, a negative signed value. The geometric area is always nonnegative and equals $\\int|f-g|\\,dx=${k * c}$.`,
      };
    },
  },
  {
    id: "n8-signed-geo-b",
    unit: U8,
    topic: "area-between-curves",
    difficulty: "medium",
    manifestation: "area-between-curves:signed-vs-geometric",
    mistakes: ["treats-signed-as-geometric"],
    build: (r: RNG) => {
      const c = ri(r, 2, 4) * 2;
      const half = (c * c) / 4;
      return {
        prompt: `Curves $f(x)=x$ and $g(x)=${c}-x$ cross at $x=${c / 2}$ on $[0,${c}]$. A student computes $\\int_{0}^{${c}}(f(x)-g(x))\\,dx=0$ and concludes that the region between the curves has zero area. What is wrong with this conclusion?`,
        correct: `\\text{The signed integral cancels, but the geometric area is } ${half + half} \\text{, not } 0`,
        distractors: [
          `\\text{Nothing is wrong; the area really is } 0`,
          `\\text{The student should have gotten a negative number instead}`,
          `\\text{The functions must be swapped before integrating}`,
        ],
        explanation: `Because $f-g$ is negative on part of $[0,${c}]$ and positive on the rest, the signed integral cancels to $0$. The actual (geometric) area requires $\\int|f-g|\\,dx$, splitting at the crossing point, which gives $${half}+${half}=${half + half}$.`,
      };
    },
  },
  {
    id: "n8-signed-geo-c",
    unit: U8,
    topic: "area-between-curves",
    difficulty: "medium",
    manifestation: "area-between-curves:signed-vs-geometric",
    mistakes: ["missing-absolute-value"],
    build: (r: RNG) => {
      const c = ri(r, 3, 8);
      return {
        prompt: `Curves $f$ and $g$ cross once in $(a,b)$, at $x=c$. Which expression gives the true geometric area between the curves on $[a,b]$?`,
        correct: `\\int_{a}^{c}|f(x)-g(x)|\\,dx+\\int_{c}^{b}|f(x)-g(x)|\\,dx`,
        distractors: [
          `\\int_{a}^{b}(f(x)-g(x))\\,dx`,
          `\\left|\\int_{a}^{b}(f(x)-g(x))\\,dx\\right|`,
          `\\int_{a}^{b}(g(x)-f(x))\\,dx`,
        ],
        explanation: `Because the sign of $f-g$ changes at the crossing point, the geometric area requires integrating the absolute value on each piece separately; integrating $f-g$ directly (with or without an outer absolute value) can undercount area lost to cancellation.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: volume-disks-and-washers:washer                              */
  /* ================================================================== */
  {
    id: "n8-washer-a",
    unit: U8,
    topic: "volume-disks-and-washers",
    difficulty: "medium",
    manifestation: "volume-disks-and-washers:washer",
    mistakes: ["swapped-radii", "missing-pi", "used-disk-not-washer"],
    build: (r: RNG) => {
      const k = ri(r, 3, 6);
      const b = ri(r, 1, 3);
      // region between y = x+k (outer) and y = k (inner, constant) on [0,b], revolved about x-axis
      // V = pi * int_0^b [(x+k)^2 - k^2] dx = pi * int (x^2+2kx) dx = pi*(b^3/3 + k b^2)
      const val = `\\pi\\left(\\dfrac{${b}^{3}}{3}+${k}\\cdot ${b}^{2}\\right)`;
      return {
        prompt: `The region bounded by $y=x+${k}$ and $y=${k}$ on $[0,${b}]$ is revolved about the $x$-axis. Which expression gives the resulting volume?`,
        correct: `\\pi\\int_{0}^{${b}}\\left[(x+${k})^{2}-${k}^{2}\\right]dx`,
        distractors: [
          `\\pi\\int_{0}^{${b}}\\left[${k}^{2}-(x+${k})^{2}\\right]dx`,
          `\\int_{0}^{${b}}\\left[(x+${k})^{2}-${k}^{2}\\right]dx`,
          `\\pi\\int_{0}^{${b}}(x+${k})^{2}\\,dx`,
        ],
        explanation: `The outer radius is $x+${k}$ (the farther curve from the axis) and the inner radius is $${k}$, giving the washer integral $\\pi\\int_{0}^{${b}}[(x+${k})^{2}-${k}^{2}]\\,dx$. Swapping the radii, dropping $\\pi$, or using only the outer radius (a disk, ignoring the hole) are common errors.`,
      };
    },
  },
  {
    id: "n8-washer-b",
    unit: U8,
    topic: "volume-disks-and-washers",
    difficulty: "hard",
    manifestation: "volume-disks-and-washers:washer",
    mistakes: ["forgot-shift-axis"],
    build: (r: RNG) => {
      const k = ri(r, 1, 3);
      const b = ri(r, 2, 4);
      return {
        prompt: `The region bounded by $y=\\sqrt{x}$ and $y=0$ on $[0,${b}]$ is revolved about the horizontal line $y=-${k}$. Which integral gives the volume?`,
        correct: `\\pi\\int_{0}^{${b}}\\left[(\\sqrt{x}+${k})^{2}-${k}^{2}\\right]dx`,
        distractors: [
          `\\pi\\int_{0}^{${b}}(\\sqrt{x})^{2}\\,dx`,
          `\\pi\\int_{0}^{${b}}\\left[(\\sqrt{x}-${k})^{2}-${k}^{2}\\right]dx`,
          `\\pi\\int_{0}^{${b}}\\left[${k}^{2}-(\\sqrt{x}+${k})^{2}\\right]dx`,
        ],
        explanation: `Since the axis $y=-${k}$ is below the region, each outer radius is $\\sqrt{x}-(-${k})=\\sqrt{x}+${k}$, and the inner radius (from the axis to $y=0$) is $${k}$. Ignoring the shift, using the wrong sign, or reversing the radii are common errors.`,
      };
    },
  },
  {
    id: "n8-washer-c",
    unit: U8,
    topic: "volume-disks-and-washers",
    difficulty: "hard",
    manifestation: "volume-disks-and-washers:washer",
    mistakes: ["used-x-instead-of-y"],
    build: (r: RNG) => {
      const k = ri(r, 2, 4);
      return {
        prompt: `The region bounded by $x=y^{2}$ and $x=${k}$ (for $y\\ge0$) is revolved about the $y$-axis. Which integral gives the volume?`,
        correct: `\\pi\\int_{0}^{\\sqrt{${k}}}\\left[${k}^{2}-(y^{2})^{2}\\right]dy`,
        distractors: [
          `\\pi\\int_{0}^{${k}}\\left[${k}^{2}-(y^{2})^{2}\\right]dx`,
          `\\pi\\int_{0}^{\\sqrt{${k}}}\\left[(y^{2})^{2}-${k}^{2}\\right]dy`,
          `\\pi\\int_{0}^{\\sqrt{${k}}}(y^{2})^{2}\\,dy`,
        ],
        explanation: `Revolving about the $y$-axis requires integrating with respect to $y$, from $y=0$ to $y=\\sqrt{${k}}$ (where the curves meet). The outer radius is $${k}$ and the inner radius is $y^{2}$, giving $\\pi\\int_{0}^{\\sqrt{${k}}}[${k}^{2}-(y^{2})^{2}]\\,dy$. Integrating in $x$ or swapping the radii are common errors.`,
      };
    },
  },

  /* ---- Shell method (reuses volume-disks-and-washers:washer) ---- */
  {
    id: "n8-shell-a",
    unit: U8,
    topic: "volume-disks-and-washers",
    difficulty: "hard",
    manifestation: "volume-disks-and-washers:washer",
    mistakes: ["missing-2pi", "missing-x-factor"],
    build: (r: RNG) => {
      const b = ri(r, 2, 4);
      // f(x) = x^2 on [0,b], revolved about y-axis via shells: V = 2*pi*int_0^b x*x^2 dx = 2pi*b^4/4 = pi*b^4/2
      const val = `\\dfrac{\\pi ${b}^{4}}{2}`;
      return {
        prompt: `The region under $y=x^{2}$ on $[0,${b}]$ is revolved about the $y$-axis. Using the shell method, what is the volume?`,
        correct: val,
        distractors: [`\\dfrac{\\pi ${b}^{4}}{4}`, `\\pi ${b}^{4}`, `\\dfrac{2\\pi ${b}^{3}}{3}`],
        explanation: `Shells give $V=2\\pi\\int_{0}^{${b}}x\\cdot x^{2}\\,dx=2\\pi\\int_{0}^{${b}}x^{3}\\,dx=2\\pi\\cdot\\dfrac{${b}^{4}}{4}=${val}$. Omitting the factor of $2\\pi$ or the extra $x$ (shell radius) factor gives the other choices.`,
      };
    },
  },
  {
    id: "n8-shell-b",
    unit: U8,
    topic: "volume-disks-and-washers",
    difficulty: "medium",
    manifestation: "volume-disks-and-washers:washer",
    mistakes: ["confused-shell-with-washer"],
    build: (r: RNG) => {
      const k = ri(r, 2, 5);
      const b = ri(r, 1, 3);
      return {
        prompt: `The region bounded by $y=${k}x$, the $x$-axis, and $x=${b}$ is revolved about the $y$-axis. Which integral correctly represents the volume by the shell method?`,
        correct: `2\\pi\\int_{0}^{${b}}x(${k}x)\\,dx`,
        distractors: [
          `\\pi\\int_{0}^{${b}}(${k}x)^{2}\\,dx`,
          `2\\pi\\int_{0}^{${b}}(${k}x)\\,dx`,
          `\\pi\\int_{0}^{${b}}x(${k}x)\\,dx`,
        ],
        explanation: `Each cylindrical shell at position $x$ has radius $x$, height $${k}x$, and thickness $dx$, contributing $2\\pi\\cdot(\\text{radius})(\\text{height})\\,dx=2\\pi x(${k}x)\\,dx$. Using the disk/washer formula $\\pi[f(x)]^2$ instead, or forgetting the radius factor $x$, are common mix-ups between the two methods.`,
      };
    },
  },
  {
    id: "n8-shell-c",
    unit: U8,
    topic: "volume-disks-and-washers",
    difficulty: "hard",
    manifestation: "volume-disks-and-washers:washer",
    mistakes: ["forgot-axis-shift"],
    build: (r: RNG) => {
      const k = ri(r, 1, 3);
      const b = ri(r, 2, 4);
      return {
        prompt: `The region under $y=\\sqrt{x}$ on $[0,${b}]$ is revolved about the vertical line $x=-${k}$. Which integral gives the volume by the shell method?`,
        correct: `2\\pi\\int_{0}^{${b}}(x+${k})\\sqrt{x}\\,dx`,
        distractors: [
          `2\\pi\\int_{0}^{${b}}x\\sqrt{x}\\,dx`,
          `2\\pi\\int_{0}^{${b}}(x-${k})\\sqrt{x}\\,dx`,
          `\\pi\\int_{0}^{${b}}(x+${k})^{2}\\,dx`,
        ],
        explanation: `Because the axis of revolution is shifted to $x=-${k}$, the shell radius becomes $x-(-${k})=x+${k}$, not just $x$. The volume is $2\\pi\\int_{0}^{${b}}(x+${k})\\sqrt{x}\\,dx$; forgetting the shift or using the disk formula are common errors.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: volume-known-cross-sections:setup-only                       */
  /* ================================================================== */
  {
    id: "n8-crosssec-a",
    unit: U8,
    topic: "volume-known-cross-sections",
    difficulty: "medium",
    manifestation: "volume-known-cross-sections:setup-only",
    mistakes: ["used-disk-formula", "missed-half-factor"],
    build: (r: RNG) => {
      const b = ri(r, 2, 5);
      const isTriangle = r() < 0.5;
      const pts = sampleCurve((x) => Math.sqrt(x), 0, b, 40);
      const shapeLabel = isTriangle ? "isosceles right triangles (legs on the base)" : "squares";
      const coefStr = isTriangle ? "\\dfrac{1}{2}" : "1";
      const correct = isTriangle
        ? `\\dfrac{1}{2}\\int_{0}^{${b}}x\\,dx`
        : `\\int_{0}^{${b}}x\\,dx`;
      return {
        prompt: `The base of a solid is the region under $y=\\sqrt{x}$ on $[0,${b}]$. Cross sections perpendicular to the $x$-axis are ${shapeLabel} with the segment from the $x$-axis to the curve as one full side (or leg). Which integral gives the volume?`,
        correct,
        distractors: [
          `\\pi\\int_{0}^{${b}}x\\,dx`,
          isTriangle ? `\\int_{0}^{${b}}x\\,dx` : `\\dfrac{1}{2}\\int_{0}^{${b}}x\\,dx`,
          `\\int_{0}^{${b}}\\sqrt{x}\\,dx`,
        ],
        explanation: `Each cross-sectional side length is $f(x)=\\sqrt{x}$, so the area is ${isTriangle ? "$\\tfrac12[f(x)]^2$ for the right triangle" : "$[f(x)]^2$ for the square"}, giving $[f(x)]^2=x$. Volume is $${correct}$. Using the disk formula $\\pi[f(x)]^2$, or swapping whether the $\\tfrac12$ factor applies, are common errors.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: true }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },
  {
    id: "n8-crosssec-b",
    unit: U8,
    topic: "volume-known-cross-sections",
    difficulty: "medium",
    manifestation: "volume-known-cross-sections:setup-only",
    mistakes: ["missing-sqrt3-over-4-coefficient"],
    build: (r: RNG) => {
      const k = ri(r, 1, 3);
      const b = ri(r, 2, 4);
      const pts = sampleCurve((x) => k * x, 0, b, 20);
      return {
        prompt: `The base of a solid is the region under $y=${k}x$ on $[0,${b}]$. Cross sections perpendicular to the $x$-axis are equilateral triangles with a side on the base. Which integral gives the volume?`,
        correct: `\\dfrac{\\sqrt{3}}{4}\\int_{0}^{${b}}(${k}x)^{2}\\,dx`,
        distractors: [
          `\\int_{0}^{${b}}(${k}x)^{2}\\,dx`,
          `\\dfrac{1}{2}\\int_{0}^{${b}}(${k}x)^{2}\\,dx`,
          `\\pi\\int_{0}^{${b}}(${k}x)^{2}\\,dx`,
        ],
        explanation: `An equilateral triangle with side $s$ has area $\\tfrac{\\sqrt3}{4}s^{2}$. With $s=${k}x$, the cross-sectional area is $\\tfrac{\\sqrt3}{4}(${k}x)^{2}$, so the volume is $\\tfrac{\\sqrt3}{4}\\int_{0}^{${b}}(${k}x)^{2}\\,dx$. Dropping the $\\tfrac{\\sqrt3}{4}$ coefficient (or using the wrong one) is a common error.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: false }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },
  {
    id: "n8-crosssec-c",
    unit: U8,
    topic: "volume-known-cross-sections",
    difficulty: "medium",
    manifestation: "volume-known-cross-sections:setup-only",
    mistakes: ["treated-side-as-diameter-wrong-factor"],
    build: (r: RNG) => {
      const b = ri(r, 2, 5);
      const pts = sampleCurve((x) => Math.sqrt(x), 0, b, 40);
      return {
        prompt: `The base of a solid is the region under $y=\\sqrt{x}$ on $[0,${b}]$. Cross sections perpendicular to the $x$-axis are semicircles with diameter stretching from the $x$-axis to the curve. Which integral gives the volume?`,
        correct: `\\dfrac{\\pi}{8}\\int_{0}^{${b}}x\\,dx`,
        distractors: [
          `\\dfrac{\\pi}{2}\\int_{0}^{${b}}x\\,dx`,
          `\\pi\\int_{0}^{${b}}x\\,dx`,
          `\\dfrac{\\pi}{4}\\int_{0}^{${b}}x\\,dx`,
        ],
        explanation: `With diameter $f(x)=\\sqrt{x}$, the radius is $\\tfrac12\\sqrt{x}$, so the semicircular area is $\\tfrac12\\pi\\left(\\tfrac12\\sqrt{x}\\right)^{2}=\\tfrac{\\pi}{8}x$. The volume is $\\tfrac{\\pi}{8}\\int_{0}^{${b}}x\\,dx$. Treating $f(x)$ as the radius instead of the diameter is the error behind the other choices.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: true }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: arc-length:compare-chord                                     */
  /* ================================================================== */
  {
    id: "n8-arc-chord-a",
    unit: U8,
    topic: "arc-length",
    difficulty: "medium",
    manifestation: "arc-length:compare-chord",
    track: "BC",
    mistakes: ["thinks-arc-equals-chord"],
    build: (r: RNG) => {
      const b = ri(r, 2, 5);
      const k = ri(r, 1, 2);
      const pts = sampleCurve((x) => k * x * x, 0, b, 40);
      return {
        prompt: `The graph shows $y=${k}x^{2}$ on $[0,${b}]$, which is not a straight line. How does the arc length of the curve on $[0,${b}]$ compare to the straight-line distance between its endpoints?`,
        correct: `\\text{The arc length is greater than the straight-line distance.}`,
        distractors: [
          `\\text{The arc length equals the straight-line distance.}`,
          `\\text{The arc length is less than the straight-line distance.}`,
          `\\text{No comparison is possible without more information.}`,
        ],
        explanation: `A straight segment is the shortest path between two points, and this curve is not straight, so its arc length must exceed the straight-line (chord) distance between its endpoints.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: true }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },
  {
    id: "n8-arc-chord-b",
    unit: U8,
    topic: "arc-length",
    difficulty: "medium",
    manifestation: "arc-length:compare-chord",
    track: "BC",
    mistakes: ["dropped-sqrt", "used-only-delta-x"],
    build: (r: RNG) => {
      const b = ri(r, 3, 6);
      const k = ri(r, 1, 2);
      const y0 = 0;
      const y1 = k * b;
      const chord = Math.sqrt(b * b + (y1 - y0) * (y1 - y0));
      const pts = sampleCurve((x) => k * x + Math.sin(x), 0, b, 40);
      return {
        prompt: `A curve runs from $(0,0)$ to $(${b},${y1})$ as shown. What is the straight-line (chord) distance between its endpoints?`,
        correct: `\\sqrt{${b}^{2}+${y1}^{2}}`,
        distractors: [`${b}+${y1}`, `${b}`, `\\sqrt{${b}+${y1}}`],
        explanation: `The chord distance uses the distance formula: $\\sqrt{(${b}-0)^{2}+(${y1}-0)^{2}}=\\sqrt{${b}^{2}+${y1}^{2}}\\approx ${Math.round(chord * 100) / 100}$. Since the pictured curve is not straight, its arc length must exceed this chord value.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: true }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },
  {
    id: "n8-arc-chord-c",
    unit: U8,
    topic: "arc-length",
    difficulty: "hard",
    manifestation: "arc-length:compare-chord",
    track: "BC",
    mistakes: ["ignores-triangle-inequality"],
    build: (r: RNG) => {
      const b = ri(r, 2, 5);
      const k = ri(r, 1, 2);
      const pts = sampleCurve((x) => k * Math.sin(x), 0, b, 40);
      return {
        prompt: `The curve shown wiggles between its endpoints rather than going straight from one to the other. A student claims the arc length integral $\\int_{0}^{${b}}\\sqrt{1+(f'(x))^{2}}\\,dx$ could come out smaller than the chord length between the endpoints. Is this possible?`,
        correct: `\\text{No; the arc length can never be less than the chord length.}`,
        distractors: [
          `\\text{Yes, if the curve is concave down.}`,
          `\\text{Yes, if } f'(x) \\text{ is negative somewhere.}`,
          `\\text{Yes, if the interval is short enough.}`,
        ],
        explanation: `A straight line segment is the shortest possible path between two points, so any curve's arc length is always at least as large as the chord (straight-line) distance between its endpoints, regardless of concavity or interval length.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: true }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: arc-length:context                                          */
  /* ================================================================== */
  {
    id: "n8-arc-context-a",
    unit: U8,
    topic: "arc-length",
    difficulty: "medium",
    manifestation: "arc-length:context",
    track: "BC",
    mistakes: ["confuses-with-displacement"],
    build: (r: RNG) => {
      const a = ri(r, 0, 2);
      const b = a + ri(r, 3, 6);
      return {
        prompt: `A hiking trail follows the curve $y=f(x)$ (miles) for $x$ from ${a} to ${b} (miles east). What does $\\displaystyle\\int_{${a}}^{${b}}\\sqrt{1+[f'(x)]^{2}}\\,dx$ represent?`,
        correct: `\\text{The total length of the trail from } x=${a} \\text{ to } x=${b}`,
        distractors: [
          `\\text{The straight-line distance from the start to the end of the trail}`,
          `\\text{The change in elevation of the trail}`,
          `\\text{The average steepness of the trail}`,
        ],
        explanation: `The arc-length integral sums the lengths of infinitesimal segments along the curve, giving the total distance traveled along the trail — not the straight-line distance between endpoints, and not elevation change.`,
      };
    },
  },
  {
    id: "n8-arc-context-b",
    unit: U8,
    topic: "arc-length",
    difficulty: "easy",
    manifestation: "arc-length:context",
    track: "BC",
    mistakes: ["confuses-units-with-area"],
    build: (r: RNG) => {
      return {
        prompt: `A cable hangs in the shape $y=f(x)$, where $x$ and $y$ are measured in meters. What are the units of $\\displaystyle\\int_{a}^{b}\\sqrt{1+[f'(x)]^{2}}\\,dx$?`,
        correct: `\\text{meters}`,
        distractors: [`\\text{square meters}`, `\\text{meters per second}`, `\\text{no units (it is a pure number)}`],
        explanation: `The arc-length integral measures length along the cable. Since $x$ and $y$ are both in meters, the result carries units of meters, not square meters (area) or a rate.`,
      };
    },
  },
  {
    id: "n8-arc-context-c",
    unit: U8,
    topic: "arc-length",
    difficulty: "medium",
    manifestation: "arc-length:context",
    track: "BC",
    mistakes: ["confuses-net-displacement-with-distance"],
    build: (r: RNG) => {
      const t1 = ri(r, 1, 3);
      const t2 = t1 + ri(r, 2, 5);
      return {
        prompt: `A particle moves along the curve $y=f(x)$ from $t=${t1}$ to $t=${t2}$, where $x(t)$ and $y(t)$ trace the path. The quantity $\\displaystyle\\int_{${t1}}^{${t2}}\\sqrt{1+[f'(x)]^{2}}\\,dx$ (evaluated along the path) gives:`,
        correct: `\\text{The total distance traveled by the particle}`,
        distractors: [
          `\\text{The particle's net displacement}`,
          `\\text{The particle's average velocity}`,
          `\\text{The particle's final position}`,
        ],
        explanation: `Arc length always measures total path length (distance traveled), which can exceed net displacement if the path is not a straight line — displacement, velocity, and position are different quantities entirely.`,
      };
    },
  },

  /* ---- Arc length in y (reuses arc-length manifestation, BC) ---- */
  {
    id: "n8-arclen-y-a",
    unit: U8,
    topic: "arc-length",
    difficulty: "hard",
    manifestation: "arc-length:setup",
    track: "BC",
    mistakes: ["used-dy-dx-instead-of-dx-dy", "missing-plus-1"],
    build: (r: RNG) => {
      const c = ri(r, 1, 3);
      return {
        prompt: `The curve $x=${c}y^{2}$ runs from $y=0$ to $y=2$. Since $x$ is easier to differentiate with respect to $y$ here, which integral correctly gives the arc length?`,
        correct: `\\int_{0}^{2}\\sqrt{1+\\left(\\dfrac{dx}{dy}\\right)^{2}}\\,dy`,
        distractors: [
          `\\int_{0}^{2}\\sqrt{1+\\left(\\dfrac{dy}{dx}\\right)^{2}}\\,dy`,
          `\\int_{0}^{2}\\left(\\dfrac{dx}{dy}\\right)^{2}\\,dy`,
          `\\int_{0}^{2}\\sqrt{1+\\dfrac{dx}{dy}}\\,dy`,
        ],
        explanation: `When integrating with respect to $y$, the arc-length formula uses $\\dfrac{dx}{dy}$ (not $\\dfrac{dy}{dx}$) inside the square root: $\\int\\sqrt{1+(dx/dy)^{2}}\\,dy$. Omitting the "+1" or squaring incorrectly are common errors.`,
      };
    },
  },
  {
    id: "n8-arclen-y-b",
    unit: U8,
    topic: "arc-length",
    difficulty: "hard",
    manifestation: "arc-length:setup",
    track: "BC",
    mistakes: ["forgot-2-3-coefficient", "used-1-3-coefficient", "swapped-bounds"],
    build: (r: RNG) => {
      const k = ri(r, 2, 3);
      const b = k * k - 1;
      const val = Math.round((2 / 3) * (k ** 3 - 1) * 1000) / 1000;
      return {
        prompt: `For $x=\\dfrac{2}{3}y^{3/2}$, the arc length from $y=0$ to $y=${b}$ is $\\displaystyle\\int_{0}^{${b}}\\sqrt{1+y}\\,dy$. Evaluate this integral.`,
        correct: frac(2 * (k ** 3 - 1), 3),
        distractors: [`${k ** 3 - 1}`, frac(k ** 3 - 1, 3), `-${frac(2 * (k ** 3 - 1), 3)}`],
        explanation: `$\\int_{0}^{${b}}\\sqrt{1+y}\\,dy=\\left[\\dfrac{2}{3}(1+y)^{3/2}\\right]_{0}^{${b}}=\\dfrac{2}{3}\\left(${k}^{3}-1\\right)=${frac(2 * (k ** 3 - 1), 3)}\\approx ${val}$. Omitting the $\\tfrac23$ coefficient, using $\\tfrac13$ instead, or swapping the bounds (giving a sign error) are common mistakes.`,
      };
    },
  },
  {
    id: "n8-arclen-y-c",
    unit: U8,
    topic: "arc-length",
    difficulty: "hard",
    manifestation: "arc-length:setup",
    track: "BC",
    mistakes: ["chooses-wrong-integration-variable"],
    build: (r: RNG) => {
      return {
        prompt: `The curve $x=y^{2}+1$ is not the graph of a function $y=f(x)$ passing the vertical line test on its full domain, but $x$ is a function of $y$. To find its arc length from $y=-1$ to $y=1$, which approach is correct?`,
        correct: `\\text{Integrate } \\sqrt{1+\\left(\\dfrac{dx}{dy}\\right)^{2}} \\text{ with respect to } y`,
        distractors: [
          `\\text{Solve for } y \\text{ in terms of } x \\text{ and integrate with respect to } x`,
          `\\text{Integrate } \\sqrt{1+\\left(\\dfrac{dy}{dx}\\right)^{2}} \\text{ with respect to } y`,
          `\\text{The arc length cannot be computed since } x=y^2+1 \\text{ is not a function of } x`,
        ],
        explanation: `Since $x$ is a single-valued function of $y$ here, the correct and simplest approach is to integrate the arc-length formula with respect to $y$, using $dx/dy$. Trying to solve for $y(x)$ would require splitting into two branches unnecessarily.`,
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: accumulation-in-context:graph-rate                           */
  /* ================================================================== */
  {
    id: "n8-accum-rate-a",
    unit: U8,
    topic: "accumulation-in-context",
    difficulty: "medium",
    manifestation: "accumulation-in-context:graph-rate",
    mistakes: ["forgot-initial-value", "used-rate-value-directly"],
    build: (r: RNG) => {
      const x0 = 0;
      const x1 = ri(r, 2, 3);
      const x2 = x1 + ri(r, 2, 3);
      const r0 = ri(r, 1, 4);
      const r1 = ri(r, 4, 8);
      const r2 = ri(r, 1, 5);
      const F0 = ri(r, 5, 10);
      const netChange2 = (r0 + r1) * (x1 - x0) + (r1 + r2) * (x2 - x1);
      const pts: Array<[number, number]> = [
        [x0, r0],
        [x1, r1],
        [x2, r2],
      ];
      return {
        prompt: `Water flows into a tank at rate $R(t)$ (liters/min), shown as connected line segments through $(${x0},${r0})$, $(${x1},${r1})$, $(${x2},${r2})$. If the tank holds $${F0}$ liters at $t=${x0}$, how much water does it hold at $t=${x2}$?`,
        correct: `${F0 + netChange2 / 2}`,
        distractors: [`${netChange2 / 2}`, `${F0 + r2}`, `${F0 + netChange2}`],
        explanation: `The amount at $t=${x2}$ is $${F0}+\\int_{${x0}}^{${x2}}R(t)\\,dt$. Summing trapezoid areas gives $\\int R\\,dt=${netChange2 / 2}$, so the total is $${F0}+${netChange2 / 2}=${F0 + netChange2 / 2}$ liters. Forgetting the initial amount, or using the final rate instead of the accumulated integral, are common errors.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: false }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },
  {
    id: "n8-accum-rate-b",
    unit: U8,
    topic: "accumulation-in-context",
    difficulty: "hard",
    manifestation: "accumulation-in-context:graph-rate",
    mistakes: ["ignored-sign-change"],
    build: (r: RNG) => {
      const x0 = 0;
      const x1 = ri(r, 2, 4);
      const x2 = x1 + ri(r, 2, 4);
      const rNeg = -ri(r, 2, 5);
      const rPos = ri(r, 2, 5);
      // rate goes from rNeg at x0 to 0 at x1 to rPos at x2 (linear)
      const area1 = 0.5 * rNeg * (x1 - x0); // negative area (below axis)
      const area2 = 0.5 * rPos * (x2 - x1);
      const net = area1 + area2;
      const pts: Array<[number, number]> = [
        [x0, rNeg],
        [x1, 0],
        [x2, rPos],
      ];
      return {
        prompt: `The rate of change of a population, $P'(t)$ (in hundreds per year), is graphed as line segments through $(${x0},${rNeg})$, $(${x1},0)$, $(${x2},${rPos})$. What is the net change in population from $t=${x0}$ to $t=${x2}$?`,
        correct: `${net}`,
        distractors: [`${Math.abs(area1) + area2}`, `${area2}`, `${-net}`],
        explanation: `Net change $=\\int_{${x0}}^{${x2}}P'(t)\\,dt$, the signed area under the graph. The triangle on $[${x0},${x1}]$ contributes $${area1}$ (below the axis) and the triangle on $[${x1},${x2}]$ contributes $${area2}$, for a net change of $${net}$ hundred people. Treating the first region as positive area ignores that the population was decreasing there.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: false }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },
  {
    id: "n8-accum-rate-c",
    unit: U8,
    topic: "accumulation-in-context",
    difficulty: "medium",
    manifestation: "accumulation-in-context:graph-rate",
    mistakes: ["read-final-rate-as-total"],
    build: (r: RNG) => {
      const x0 = 0;
      const x1 = ri(r, 3, 5);
      const rConst = ri(r, 2, 5);
      const pts: Array<[number, number]> = [
        [x0, rConst],
        [x1, rConst],
      ];
      const total = rConst * (x1 - x0);
      return {
        prompt: `The graph shows a constant flow rate $R(t)=${rConst}$ gallons/min for $t$ from $${x0}$ to $${x1}$ minutes. How many total gallons flow during this time?`,
        correct: `${total}`,
        distractors: [`${rConst}`, `${x1 - x0}`, `${rConst + (x1 - x0)}`],
        explanation: `Total amount $=\\int_{${x0}}^{${x1}}R(t)\\,dt=${rConst}\\times(${x1}-${x0})=${total}$ gallons. Reporting just the rate or just the elapsed time confuses a rate with an accumulated total.`,
        figure: {
          kind: "graph",
          curves: [{ points: pts, smooth: false }],
          window: fitWindow(pts, 1),
        },
      };
    },
  },

  /* ================================================================== */
  /* Unit 8: accumulation-in-context:units                                */
  /* ================================================================== */
  {
    id: "n8-accum-units-a",
    unit: U8,
    topic: "accumulation-in-context",
    difficulty: "easy",
    manifestation: "accumulation-in-context:units",
    mistakes: ["confuses-rate-units-with-total-units"],
    build: (r: RNG) => {
      return {
        prompt: `A pump's flow rate is $r(t)$, measured in gallons per minute, where $t$ is in minutes. What are the units of $\\displaystyle\\int_{2}^{8}r(t)\\,dt$?`,
        correct: `\\text{gallons}`,
        distractors: [`\\text{gallons per minute}`, `\\text{minutes}`, `\\text{gallons per minute squared}`],
        explanation: `Integrating a rate in gallons/minute with respect to $t$ in minutes multiplies the units: $\\frac{\\text{gallons}}{\\text{minute}}\\times\\text{minutes}=\\text{gallons}$, the total amount pumped.`,
      };
    },
  },
  {
    id: "n8-accum-units-b",
    unit: U8,
    topic: "accumulation-in-context",
    difficulty: "medium",
    manifestation: "accumulation-in-context:units",
    mistakes: ["misidentifies-derivative-as-total"],
    build: (r: RNG) => {
      return {
        prompt: `Let $A(t)$ be the number of liters of water (measured in liters, $t$ in hours) in a pool. A student is told $A'(3)=12$. What are the correct units of this value, and what does it represent?`,
        correct: `\\text{liters per hour; the instantaneous rate the pool's volume is changing at } t=3`,
        distractors: [
          `\\text{liters; the total volume in the pool at } t=3`,
          `\\text{hours; the time needed to fill the pool}`,
          `\\text{liters per hour squared; the rate at which the flow rate is changing}`,
        ],
        explanation: `Since $A$ is measured in liters and $t$ in hours, $A'(t)=dA/dt$ has units liters/hour and represents the instantaneous rate of change of volume — not the volume itself.`,
      };
    },
  },
  {
    id: "n8-accum-units-c",
    unit: U8,
    topic: "accumulation-in-context",
    difficulty: "medium",
    manifestation: "accumulation-in-context:units",
    mistakes: ["drops-units-in-word-problem"],
    build: (r: RNG) => {
      const a = ri(r, 1, 4);
      const b = a + ri(r, 3, 6);
      return {
        prompt: `A factory's production rate is $p(t)$ thousand units per day, with $t$ in days. A report states $\\int_{${a}}^{${b}}p(t)\\,dt=45$. What does this number represent, with correct units?`,
        correct: `\\text{45 thousand units produced between day } ${a} \\text{ and day } ${b}`,
        distractors: [
          `\\text{a production rate of 45 thousand units per day}`,
          `\\text{45 days of production}`,
          `\\text{the factory produced exactly 45 units total}`,
        ],
        explanation: `Integrating a rate in thousand-units/day over an interval measured in days yields a quantity in thousand units — the total production accumulated over $[${a},${b}]$, not a rate and not a plain count of days or raw units.`,
      };
    },
  },
];
