/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PhysicsCMechanicsRouteImport } from './routes/physics-c-mechanics'
import { Route as PhysicsCElectricityMagnetismRouteImport } from './routes/physics-c-electricity-magnetism'
import { Route as Physics2RouteImport } from './routes/physics-2'
import { Route as Physics1RouteImport } from './routes/physics-1'
import { Route as LatexMasterSheetRouteImport } from './routes/latex-master-sheet'
import { Route as FrqsByTypeRouteImport } from './routes/frqs-by-type'
import { Route as ExamStrategyRouteImport } from './routes/exam-strategy'
import { Route as CommonMistakesRouteImport } from './routes/common-mistakes'
import { Route as BcTrackRouteImport } from './routes/bc-track'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AbTrackRouteImport } from './routes/ab-track'
import { Route as R108PointsBreakdownRouteImport } from './routes/108-points-breakdown'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TopicRundownIndexRouteImport } from './routes/topic-rundown.index'
import { Route as QuestionNavigatorIndexRouteImport } from './routes/question-navigator.index'
import { Route as TopicRundownUnitIdRouteImport } from './routes/topic-rundown.$unitId'
import { Route as AuthenticatedPredictRouteImport } from './routes/_authenticated/predict'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as QuestionNavigatorUnitIdIndexRouteImport } from './routes/question-navigator.$unitId.index'
import { Route as QuestionNavigatorUnitIdTopicIdRouteImport } from './routes/question-navigator.$unitId.$topicId'
import { Route as AuthenticatedAdminPredictionsRouteImport } from './routes/_authenticated/admin/predictions'

const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicsCMechanicsRoute = PhysicsCMechanicsRouteImport.update({
  id: '/physics-c-mechanics',
  path: '/physics-c-mechanics',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicsCElectricityMagnetismRoute =
  PhysicsCElectricityMagnetismRouteImport.update({
    id: '/physics-c-electricity-magnetism',
    path: '/physics-c-electricity-magnetism',
    getParentRoute: () => rootRouteImport,
  } as any)
const Physics2Route = Physics2RouteImport.update({
  id: '/physics-2',
  path: '/physics-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Physics1Route = Physics1RouteImport.update({
  id: '/physics-1',
  path: '/physics-1',
  getParentRoute: () => rootRouteImport,
} as any)
const LatexMasterSheetRoute = LatexMasterSheetRouteImport.update({
  id: '/latex-master-sheet',
  path: '/latex-master-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const FrqsByTypeRoute = FrqsByTypeRouteImport.update({
  id: '/frqs-by-type',
  path: '/frqs-by-type',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamStrategyRoute = ExamStrategyRouteImport.update({
  id: '/exam-strategy',
  path: '/exam-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonMistakesRoute = CommonMistakesRouteImport.update({
  id: '/common-mistakes',
  path: '/common-mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const BcTrackRoute = BcTrackRouteImport.update({
  id: '/bc-track',
  path: '/bc-track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AbTrackRoute = AbTrackRouteImport.update({
  id: '/ab-track',
  path: '/ab-track',
  getParentRoute: () => rootRouteImport,
} as any)
const R108PointsBreakdownRoute = R108PointsBreakdownRouteImport.update({
  id: '/108-points-breakdown',
  path: '/108-points-breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicRundownIndexRoute = TopicRundownIndexRouteImport.update({
  id: '/topic-rundown/',
  path: '/topic-rundown/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionNavigatorIndexRoute = QuestionNavigatorIndexRouteImport.update({
  id: '/question-navigator/',
  path: '/question-navigator/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicRundownUnitIdRoute = TopicRundownUnitIdRouteImport.update({
  id: '/topic-rundown/$unitId',
  path: '/topic-rundown/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPredictRoute = AuthenticatedPredictRouteImport.update({
  id: '/predict',
  path: '/predict',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const QuestionNavigatorUnitIdIndexRoute =
  QuestionNavigatorUnitIdIndexRouteImport.update({
    id: '/question-navigator/$unitId/',
    path: '/question-navigator/$unitId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const QuestionNavigatorUnitIdTopicIdRoute =
  QuestionNavigatorUnitIdTopicIdRouteImport.update({
    id: '/question-navigator/$unitId/$topicId',
    path: '/question-navigator/$unitId/$topicId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminPredictionsRoute =
  AuthenticatedAdminPredictionsRouteImport.update({
    id: '/admin/predictions',
    path: '/admin/predictions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/108-points-breakdown': typeof R108PointsBreakdownRoute
  '/ab-track': typeof AbTrackRoute
  '/auth': typeof AuthRoute
  '/bc-track': typeof BcTrackRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/exam-strategy': typeof ExamStrategyRoute
  '/frqs-by-type': typeof FrqsByTypeRoute
  '/latex-master-sheet': typeof LatexMasterSheetRoute
  '/physics-1': typeof Physics1Route
  '/physics-2': typeof Physics2Route
  '/physics-c-electricity-magnetism': typeof PhysicsCElectricityMagnetismRoute
  '/physics-c-mechanics': typeof PhysicsCMechanicsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/predict': typeof AuthenticatedPredictRoute
  '/topic-rundown/$unitId': typeof TopicRundownUnitIdRoute
  '/question-navigator/': typeof QuestionNavigatorIndexRoute
  '/topic-rundown/': typeof TopicRundownIndexRoute
  '/admin/predictions': typeof AuthenticatedAdminPredictionsRoute
  '/question-navigator/$unitId/$topicId': typeof QuestionNavigatorUnitIdTopicIdRoute
  '/question-navigator/$unitId/': typeof QuestionNavigatorUnitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/108-points-breakdown': typeof R108PointsBreakdownRoute
  '/ab-track': typeof AbTrackRoute
  '/auth': typeof AuthRoute
  '/bc-track': typeof BcTrackRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/exam-strategy': typeof ExamStrategyRoute
  '/frqs-by-type': typeof FrqsByTypeRoute
  '/latex-master-sheet': typeof LatexMasterSheetRoute
  '/physics-1': typeof Physics1Route
  '/physics-2': typeof Physics2Route
  '/physics-c-electricity-magnetism': typeof PhysicsCElectricityMagnetismRoute
  '/physics-c-mechanics': typeof PhysicsCMechanicsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/predict': typeof AuthenticatedPredictRoute
  '/topic-rundown/$unitId': typeof TopicRundownUnitIdRoute
  '/question-navigator': typeof QuestionNavigatorIndexRoute
  '/topic-rundown': typeof TopicRundownIndexRoute
  '/admin/predictions': typeof AuthenticatedAdminPredictionsRoute
  '/question-navigator/$unitId/$topicId': typeof QuestionNavigatorUnitIdTopicIdRoute
  '/question-navigator/$unitId': typeof QuestionNavigatorUnitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/108-points-breakdown': typeof R108PointsBreakdownRoute
  '/ab-track': typeof AbTrackRoute
  '/auth': typeof AuthRoute
  '/bc-track': typeof BcTrackRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/exam-strategy': typeof ExamStrategyRoute
  '/frqs-by-type': typeof FrqsByTypeRoute
  '/latex-master-sheet': typeof LatexMasterSheetRoute
  '/physics-1': typeof Physics1Route
  '/physics-2': typeof Physics2Route
  '/physics-c-electricity-magnetism': typeof PhysicsCElectricityMagnetismRoute
  '/physics-c-mechanics': typeof PhysicsCMechanicsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/statistics': typeof StatisticsRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/predict': typeof AuthenticatedPredictRoute
  '/topic-rundown/$unitId': typeof TopicRundownUnitIdRoute
  '/question-navigator/': typeof QuestionNavigatorIndexRoute
  '/topic-rundown/': typeof TopicRundownIndexRoute
  '/_authenticated/admin/predictions': typeof AuthenticatedAdminPredictionsRoute
  '/question-navigator/$unitId/$topicId': typeof QuestionNavigatorUnitIdTopicIdRoute
  '/question-navigator/$unitId/': typeof QuestionNavigatorUnitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/108-points-breakdown'
    | '/ab-track'
    | '/auth'
    | '/bc-track'
    | '/common-mistakes'
    | '/exam-strategy'
    | '/frqs-by-type'
    | '/latex-master-sheet'
    | '/physics-1'
    | '/physics-2'
    | '/physics-c-electricity-magnetism'
    | '/physics-c-mechanics'
    | '/sitemap.xml'
    | '/statistics'
    | '/command-center'
    | '/practice'
    | '/predict'
    | '/topic-rundown/$unitId'
    | '/question-navigator/'
    | '/topic-rundown/'
    | '/admin/predictions'
    | '/question-navigator/$unitId/$topicId'
    | '/question-navigator/$unitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/108-points-breakdown'
    | '/ab-track'
    | '/auth'
    | '/bc-track'
    | '/common-mistakes'
    | '/exam-strategy'
    | '/frqs-by-type'
    | '/latex-master-sheet'
    | '/physics-1'
    | '/physics-2'
    | '/physics-c-electricity-magnetism'
    | '/physics-c-mechanics'
    | '/sitemap.xml'
    | '/statistics'
    | '/command-center'
    | '/practice'
    | '/predict'
    | '/topic-rundown/$unitId'
    | '/question-navigator'
    | '/topic-rundown'
    | '/admin/predictions'
    | '/question-navigator/$unitId/$topicId'
    | '/question-navigator/$unitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/108-points-breakdown'
    | '/ab-track'
    | '/auth'
    | '/bc-track'
    | '/common-mistakes'
    | '/exam-strategy'
    | '/frqs-by-type'
    | '/latex-master-sheet'
    | '/physics-1'
    | '/physics-2'
    | '/physics-c-electricity-magnetism'
    | '/physics-c-mechanics'
    | '/sitemap.xml'
    | '/statistics'
    | '/_authenticated/command-center'
    | '/_authenticated/practice'
    | '/_authenticated/predict'
    | '/topic-rundown/$unitId'
    | '/question-navigator/'
    | '/topic-rundown/'
    | '/_authenticated/admin/predictions'
    | '/question-navigator/$unitId/$topicId'
    | '/question-navigator/$unitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R108PointsBreakdownRoute: typeof R108PointsBreakdownRoute
  AbTrackRoute: typeof AbTrackRoute
  AuthRoute: typeof AuthRoute
  BcTrackRoute: typeof BcTrackRoute
  CommonMistakesRoute: typeof CommonMistakesRoute
  ExamStrategyRoute: typeof ExamStrategyRoute
  FrqsByTypeRoute: typeof FrqsByTypeRoute
  LatexMasterSheetRoute: typeof LatexMasterSheetRoute
  Physics1Route: typeof Physics1Route
  Physics2Route: typeof Physics2Route
  PhysicsCElectricityMagnetismRoute: typeof PhysicsCElectricityMagnetismRoute
  PhysicsCMechanicsRoute: typeof PhysicsCMechanicsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatisticsRoute: typeof StatisticsRoute
  TopicRundownUnitIdRoute: typeof TopicRundownUnitIdRoute
  QuestionNavigatorIndexRoute: typeof QuestionNavigatorIndexRoute
  TopicRundownIndexRoute: typeof TopicRundownIndexRoute
  QuestionNavigatorUnitIdTopicIdRoute: typeof QuestionNavigatorUnitIdTopicIdRoute
  QuestionNavigatorUnitIdIndexRoute: typeof QuestionNavigatorUnitIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics-c-mechanics': {
      id: '/physics-c-mechanics'
      path: '/physics-c-mechanics'
      fullPath: '/physics-c-mechanics'
      preLoaderRoute: typeof PhysicsCMechanicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics-c-electricity-magnetism': {
      id: '/physics-c-electricity-magnetism'
      path: '/physics-c-electricity-magnetism'
      fullPath: '/physics-c-electricity-magnetism'
      preLoaderRoute: typeof PhysicsCElectricityMagnetismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics-2': {
      id: '/physics-2'
      path: '/physics-2'
      fullPath: '/physics-2'
      preLoaderRoute: typeof Physics2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physics-1': {
      id: '/physics-1'
      path: '/physics-1'
      fullPath: '/physics-1'
      preLoaderRoute: typeof Physics1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latex-master-sheet': {
      id: '/latex-master-sheet'
      path: '/latex-master-sheet'
      fullPath: '/latex-master-sheet'
      preLoaderRoute: typeof LatexMasterSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frqs-by-type': {
      id: '/frqs-by-type'
      path: '/frqs-by-type'
      fullPath: '/frqs-by-type'
      preLoaderRoute: typeof FrqsByTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-strategy': {
      id: '/exam-strategy'
      path: '/exam-strategy'
      fullPath: '/exam-strategy'
      preLoaderRoute: typeof ExamStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-mistakes': {
      id: '/common-mistakes'
      path: '/common-mistakes'
      fullPath: '/common-mistakes'
      preLoaderRoute: typeof CommonMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bc-track': {
      id: '/bc-track'
      path: '/bc-track'
      fullPath: '/bc-track'
      preLoaderRoute: typeof BcTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ab-track': {
      id: '/ab-track'
      path: '/ab-track'
      fullPath: '/ab-track'
      preLoaderRoute: typeof AbTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/108-points-breakdown': {
      id: '/108-points-breakdown'
      path: '/108-points-breakdown'
      fullPath: '/108-points-breakdown'
      preLoaderRoute: typeof R108PointsBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic-rundown/': {
      id: '/topic-rundown/'
      path: '/topic-rundown'
      fullPath: '/topic-rundown/'
      preLoaderRoute: typeof TopicRundownIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-navigator/': {
      id: '/question-navigator/'
      path: '/question-navigator'
      fullPath: '/question-navigator/'
      preLoaderRoute: typeof QuestionNavigatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic-rundown/$unitId': {
      id: '/topic-rundown/$unitId'
      path: '/topic-rundown/$unitId'
      fullPath: '/topic-rundown/$unitId'
      preLoaderRoute: typeof TopicRundownUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/predict': {
      id: '/_authenticated/predict'
      path: '/predict'
      fullPath: '/predict'
      preLoaderRoute: typeof AuthenticatedPredictRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/question-navigator/$unitId/': {
      id: '/question-navigator/$unitId/'
      path: '/question-navigator/$unitId'
      fullPath: '/question-navigator/$unitId/'
      preLoaderRoute: typeof QuestionNavigatorUnitIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-navigator/$unitId/$topicId': {
      id: '/question-navigator/$unitId/$topicId'
      path: '/question-navigator/$unitId/$topicId'
      fullPath: '/question-navigator/$unitId/$topicId'
      preLoaderRoute: typeof QuestionNavigatorUnitIdTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/predictions': {
      id: '/_authenticated/admin/predictions'
      path: '/admin/predictions'
      fullPath: '/admin/predictions'
      preLoaderRoute: typeof AuthenticatedAdminPredictionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedPredictRoute: typeof AuthenticatedPredictRoute
  AuthenticatedAdminPredictionsRoute: typeof AuthenticatedAdminPredictionsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedPredictRoute: AuthenticatedPredictRoute,
  AuthenticatedAdminPredictionsRoute: AuthenticatedAdminPredictionsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R108PointsBreakdownRoute: R108PointsBreakdownRoute,
  AbTrackRoute: AbTrackRoute,
  AuthRoute: AuthRoute,
  BcTrackRoute: BcTrackRoute,
  CommonMistakesRoute: CommonMistakesRoute,
  ExamStrategyRoute: ExamStrategyRoute,
  FrqsByTypeRoute: FrqsByTypeRoute,
  LatexMasterSheetRoute: LatexMasterSheetRoute,
  Physics1Route: Physics1Route,
  Physics2Route: Physics2Route,
  PhysicsCElectricityMagnetismRoute: PhysicsCElectricityMagnetismRoute,
  PhysicsCMechanicsRoute: PhysicsCMechanicsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatisticsRoute: StatisticsRoute,
  TopicRundownUnitIdRoute: TopicRundownUnitIdRoute,
  QuestionNavigatorIndexRoute: QuestionNavigatorIndexRoute,
  TopicRundownIndexRoute: TopicRundownIndexRoute,
  QuestionNavigatorUnitIdTopicIdRoute: QuestionNavigatorUnitIdTopicIdRoute,
  QuestionNavigatorUnitIdIndexRoute: QuestionNavigatorUnitIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
