/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopicRundownRouteImport } from './routes/topic-rundown'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LatexMasterSheetRouteImport } from './routes/latex-master-sheet'
import { Route as FrqsByTypeRouteImport } from './routes/frqs-by-type'
import { Route as ExamStrategyRouteImport } from './routes/exam-strategy'
import { Route as CommonMistakesRouteImport } from './routes/common-mistakes'
import { Route as BcTrackRouteImport } from './routes/bc-track'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AbTrackRouteImport } from './routes/ab-track'
import { Route as R108PointsBreakdownRouteImport } from './routes/108-points-breakdown'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuestionNavigatorIndexRouteImport } from './routes/question-navigator.index'
import { Route as QuestionNavigatorUnitIdRouteImport } from './routes/question-navigator.$unitId'
import { Route as AuthenticatedCommandCenterRouteImport } from './routes/_authenticated/command-center'
import { Route as QuestionNavigatorUnitIdTopicIdRouteImport } from './routes/question-navigator.$unitId.$topicId'

const TopicRundownRoute = TopicRundownRouteImport.update({
  id: '/topic-rundown',
  path: '/topic-rundown',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LatexMasterSheetRoute = LatexMasterSheetRouteImport.update({
  id: '/latex-master-sheet',
  path: '/latex-master-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const FrqsByTypeRoute = FrqsByTypeRouteImport.update({
  id: '/frqs-by-type',
  path: '/frqs-by-type',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamStrategyRoute = ExamStrategyRouteImport.update({
  id: '/exam-strategy',
  path: '/exam-strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const CommonMistakesRoute = CommonMistakesRouteImport.update({
  id: '/common-mistakes',
  path: '/common-mistakes',
  getParentRoute: () => rootRouteImport,
} as any)
const BcTrackRoute = BcTrackRouteImport.update({
  id: '/bc-track',
  path: '/bc-track',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AbTrackRoute = AbTrackRouteImport.update({
  id: '/ab-track',
  path: '/ab-track',
  getParentRoute: () => rootRouteImport,
} as any)
const R108PointsBreakdownRoute = R108PointsBreakdownRouteImport.update({
  id: '/108-points-breakdown',
  path: '/108-points-breakdown',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionNavigatorIndexRoute = QuestionNavigatorIndexRouteImport.update({
  id: '/question-navigator/',
  path: '/question-navigator/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestionNavigatorUnitIdRoute = QuestionNavigatorUnitIdRouteImport.update({
  id: '/question-navigator/$unitId',
  path: '/question-navigator/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommandCenterRoute =
  AuthenticatedCommandCenterRouteImport.update({
    id: '/command-center',
    path: '/command-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const QuestionNavigatorUnitIdTopicIdRoute =
  QuestionNavigatorUnitIdTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => QuestionNavigatorUnitIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/108-points-breakdown': typeof R108PointsBreakdownRoute
  '/ab-track': typeof AbTrackRoute
  '/auth': typeof AuthRoute
  '/bc-track': typeof BcTrackRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/exam-strategy': typeof ExamStrategyRoute
  '/frqs-by-type': typeof FrqsByTypeRoute
  '/latex-master-sheet': typeof LatexMasterSheetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topic-rundown': typeof TopicRundownRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/question-navigator/$unitId': typeof QuestionNavigatorUnitIdRouteWithChildren
  '/question-navigator/': typeof QuestionNavigatorIndexRoute
  '/question-navigator/$unitId/$topicId': typeof QuestionNavigatorUnitIdTopicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/108-points-breakdown': typeof R108PointsBreakdownRoute
  '/ab-track': typeof AbTrackRoute
  '/auth': typeof AuthRoute
  '/bc-track': typeof BcTrackRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/exam-strategy': typeof ExamStrategyRoute
  '/frqs-by-type': typeof FrqsByTypeRoute
  '/latex-master-sheet': typeof LatexMasterSheetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topic-rundown': typeof TopicRundownRoute
  '/command-center': typeof AuthenticatedCommandCenterRoute
  '/question-navigator/$unitId': typeof QuestionNavigatorUnitIdRouteWithChildren
  '/question-navigator': typeof QuestionNavigatorIndexRoute
  '/question-navigator/$unitId/$topicId': typeof QuestionNavigatorUnitIdTopicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/108-points-breakdown': typeof R108PointsBreakdownRoute
  '/ab-track': typeof AbTrackRoute
  '/auth': typeof AuthRoute
  '/bc-track': typeof BcTrackRoute
  '/common-mistakes': typeof CommonMistakesRoute
  '/exam-strategy': typeof ExamStrategyRoute
  '/frqs-by-type': typeof FrqsByTypeRoute
  '/latex-master-sheet': typeof LatexMasterSheetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topic-rundown': typeof TopicRundownRoute
  '/_authenticated/command-center': typeof AuthenticatedCommandCenterRoute
  '/question-navigator/$unitId': typeof QuestionNavigatorUnitIdRouteWithChildren
  '/question-navigator/': typeof QuestionNavigatorIndexRoute
  '/question-navigator/$unitId/$topicId': typeof QuestionNavigatorUnitIdTopicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/108-points-breakdown'
    | '/ab-track'
    | '/auth'
    | '/bc-track'
    | '/common-mistakes'
    | '/exam-strategy'
    | '/frqs-by-type'
    | '/latex-master-sheet'
    | '/sitemap.xml'
    | '/topic-rundown'
    | '/command-center'
    | '/question-navigator/$unitId'
    | '/question-navigator/'
    | '/question-navigator/$unitId/$topicId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/108-points-breakdown'
    | '/ab-track'
    | '/auth'
    | '/bc-track'
    | '/common-mistakes'
    | '/exam-strategy'
    | '/frqs-by-type'
    | '/latex-master-sheet'
    | '/sitemap.xml'
    | '/topic-rundown'
    | '/command-center'
    | '/question-navigator/$unitId'
    | '/question-navigator'
    | '/question-navigator/$unitId/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/108-points-breakdown'
    | '/ab-track'
    | '/auth'
    | '/bc-track'
    | '/common-mistakes'
    | '/exam-strategy'
    | '/frqs-by-type'
    | '/latex-master-sheet'
    | '/sitemap.xml'
    | '/topic-rundown'
    | '/_authenticated/command-center'
    | '/question-navigator/$unitId'
    | '/question-navigator/'
    | '/question-navigator/$unitId/$topicId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  R108PointsBreakdownRoute: typeof R108PointsBreakdownRoute
  AbTrackRoute: typeof AbTrackRoute
  AuthRoute: typeof AuthRoute
  BcTrackRoute: typeof BcTrackRoute
  CommonMistakesRoute: typeof CommonMistakesRoute
  ExamStrategyRoute: typeof ExamStrategyRoute
  FrqsByTypeRoute: typeof FrqsByTypeRoute
  LatexMasterSheetRoute: typeof LatexMasterSheetRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopicRundownRoute: typeof TopicRundownRoute
  QuestionNavigatorUnitIdRoute: typeof QuestionNavigatorUnitIdRouteWithChildren
  QuestionNavigatorIndexRoute: typeof QuestionNavigatorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/topic-rundown': {
      id: '/topic-rundown'
      path: '/topic-rundown'
      fullPath: '/topic-rundown'
      preLoaderRoute: typeof TopicRundownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latex-master-sheet': {
      id: '/latex-master-sheet'
      path: '/latex-master-sheet'
      fullPath: '/latex-master-sheet'
      preLoaderRoute: typeof LatexMasterSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frqs-by-type': {
      id: '/frqs-by-type'
      path: '/frqs-by-type'
      fullPath: '/frqs-by-type'
      preLoaderRoute: typeof FrqsByTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-strategy': {
      id: '/exam-strategy'
      path: '/exam-strategy'
      fullPath: '/exam-strategy'
      preLoaderRoute: typeof ExamStrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/common-mistakes': {
      id: '/common-mistakes'
      path: '/common-mistakes'
      fullPath: '/common-mistakes'
      preLoaderRoute: typeof CommonMistakesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bc-track': {
      id: '/bc-track'
      path: '/bc-track'
      fullPath: '/bc-track'
      preLoaderRoute: typeof BcTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ab-track': {
      id: '/ab-track'
      path: '/ab-track'
      fullPath: '/ab-track'
      preLoaderRoute: typeof AbTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/108-points-breakdown': {
      id: '/108-points-breakdown'
      path: '/108-points-breakdown'
      fullPath: '/108-points-breakdown'
      preLoaderRoute: typeof R108PointsBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-navigator/': {
      id: '/question-navigator/'
      path: '/question-navigator'
      fullPath: '/question-navigator/'
      preLoaderRoute: typeof QuestionNavigatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/question-navigator/$unitId': {
      id: '/question-navigator/$unitId'
      path: '/question-navigator/$unitId'
      fullPath: '/question-navigator/$unitId'
      preLoaderRoute: typeof QuestionNavigatorUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/command-center': {
      id: '/_authenticated/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof AuthenticatedCommandCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/question-navigator/$unitId/$topicId': {
      id: '/question-navigator/$unitId/$topicId'
      path: '/$topicId'
      fullPath: '/question-navigator/$unitId/$topicId'
      preLoaderRoute: typeof QuestionNavigatorUnitIdTopicIdRouteImport
      parentRoute: typeof QuestionNavigatorUnitIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommandCenterRoute: typeof AuthenticatedCommandCenterRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommandCenterRoute: AuthenticatedCommandCenterRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface QuestionNavigatorUnitIdRouteChildren {
  QuestionNavigatorUnitIdTopicIdRoute: typeof QuestionNavigatorUnitIdTopicIdRoute
}

const QuestionNavigatorUnitIdRouteChildren: QuestionNavigatorUnitIdRouteChildren =
  {
    QuestionNavigatorUnitIdTopicIdRoute: QuestionNavigatorUnitIdTopicIdRoute,
  }

const QuestionNavigatorUnitIdRouteWithChildren =
  QuestionNavigatorUnitIdRoute._addFileChildren(
    QuestionNavigatorUnitIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  R108PointsBreakdownRoute: R108PointsBreakdownRoute,
  AbTrackRoute: AbTrackRoute,
  AuthRoute: AuthRoute,
  BcTrackRoute: BcTrackRoute,
  CommonMistakesRoute: CommonMistakesRoute,
  ExamStrategyRoute: ExamStrategyRoute,
  FrqsByTypeRoute: FrqsByTypeRoute,
  LatexMasterSheetRoute: LatexMasterSheetRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopicRundownRoute: TopicRundownRoute,
  QuestionNavigatorUnitIdRoute: QuestionNavigatorUnitIdRouteWithChildren,
  QuestionNavigatorIndexRoute: QuestionNavigatorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
